<!doctype html>
<html lang="pt-br">

<?= $this->loadview('admin/includes/head'); ?>
<style>
    .fundo-login {
        background-color: <?= $configuracoes["cor_primaria"]; ?>;
        position: absolute;
        height: 100%;
        width: 100%;
        top: 0;
    }

    .btn-acessar {
        background-color: <?= $configuracoes["cor_primaria"]; ?>;
        color: <?= $configuracoes["cor_terciaria"]; ?>;
        border: none;
        padding: 10px 20px;
        width: 100%;
        font-weight: bold;
        font-size: 15px;
        border-radius: 30px;
        transition: all 0.1s;
    }

    .btn-acessar:hover {
        opacity : 0.9; 
    }
</style>

<body>

    <!-- Begin page -->
    <div class="fundo-login"></div>
    <div class="wrapper-page">
        <div class="card card-pages">
            <div class="card-body">
                <div class="text-center m-t-20 m-b-30">
                    <a href="index.html" class="logo logo-admin">
                        <img src="<?= STATIC_URL; ?>/img/sistema/<?= $configuracoes["dir_galeria"] . "/" . $configuracoes["capa"] ?>" height="100">
                    </a>
                </div>
                <form class="form-horizontal m-t-20" method="post" id="form-login" action="javascript: return void();">

                    <div class="form-group">
                        <div class="col-12">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fas fa-envelope"></i>
                                </span>
                            </div>
                            <input class="form-control" type="text" required="" placeholder="Email" name="user">
                        </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-12">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fas fa-key"></i>
                                </span>
                            </div>
                            <input class="form-control" type="password" required="" placeholder="Senha" name="pass">
                        </div>
                        </div>
                    </div>

                    <div class="form-group text-center m-t-40">
                        <div class="col-12">
                            <button class="btn-acessar" id="bt-salvar" onclick="formSubmit('#form-login','<?= SITE_URL; ?>/login/processar',false,'Acessar');">Acessar</button>
                        </div>
                    </div>

                    <div id="resposta-form">
                    </div>
                    <!--Caixa de Alerta-->

                    <div class="form-group row m-t-30 m-b-0">
                        <div class="col-sm-7">
                            <a href="<?=SITE_URL;?>/login/esqueceu-senha" class="text-muted"><i class="fa fa-lock m-r-5"></i> Esqueceu sua senha?</a>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>



    <!-- jQuery  -->
    <?= $this->loadview('admin/includes/scripts'); ?>

</body>

</html>