<!doctype html>
<html lang="pt-br">

<?= $this->loadview('admin/includes/head'); ?>

<body>

    <!-- Begin page -->
    <div class="accountbg"></div>
    <div class="wrapper-page">
        <div class="card card-pages">
            <div class="card-body">
                <div class="text-center m-t-20 m-b-30">
                    <a href="index.html" class="logo logo-admin">
                        <img src="<?= TEMPLATE_HEXZY; ?>/images/logo-dark.png" height="150">
                    </a>
                </div>

                <form class="form-horizontal m-t-20" method="post" id="form-login" action="javascript: return void();">

                    <div class="form-group">
                        <div class="col-12">
                            <input class="form-control" type="text" required="" placeholder="Usuário" name="user">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-12">
                            <input class="form-control" type="password" required="" placeholder="Senha" name="pass">
                        </div>
                    </div>

                    <div class="form-group text-center m-t-40">
                        <div class="col-12">
                            <button class="btn btn-primary btn-block btn-lg waves-effect waves-light" onclick="formLogin('<?= SITE_URL; ?>/login/processar','#form-login');">ACESSAR</button>
                        </div>
                    </div>

                    <div class="alert alert-danger alert-dismissible fade">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                        <span class="alert-link"></span>
                    </div>
                    <!--Caixa de Alerta-->

                    <div class="form-group row m-t-30 m-b-0">
                        <div class="col-sm-7">
                            <a href="pages-recoverpw.html" class="text-muted"><i class="fa fa-lock m-r-5"></i> Esqueceu sua senha?</a>
                        </div>
                    </div>
                </form>
            </div>

        </div>
    </div>



    <!-- jQuery  -->
    <?= $this->loadview('admin/includes/scripts'); ?>

</body>

</html>