<?php
$dados["notificacoes"] = $notificacoes;
$dados["totalNotificacoesNaoLidas"] = $totalNotificacoesNaoLidas;
$menu = Session::get("menu");
?>
<!doctype html>
<html lang="pt-br">
<!--HEAD + CSS-->
<?= $this->loadview('admin/includes/head'); ?>

<body>
    <!--TOPO + MENU-->
    <?= $this->loadview('admin/includes/header', $dados); ?>

    <!--CONTEÚDO-->
    <div class="wrapper">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-md-8">

                                <ol class="breadcrumb">
                                    <?php foreach ($breadcrumb as $indice => $valor) : ?>
                                        <?php if (!empty($valor["url"])) : ?>
                                            <li class="breadcrumb-item"><a href="<?= $valor["url"]; ?>"><?= $valor["nome"]; ?></a></li>
                                        <?php else : ?>
                                            <li class="breadcrumb-item active"><a><?= $valor["nome"]; ?></a></li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ol>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-body">

                            <!--Conteúdo-->
                            <section>
                                <form id="cadastroForm" enctype="multipart/form-data" action="" onsubmit="return false;">
                                    <div class="container">

                                        <?php foreach ($menu["pai"] as $arrPai) : ?>
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <div class="card border-light mb-3">
                                                        <div class="card-header">
                                                            <div class="form-check">
                                                                <label class="form-check-label">
                                                                    <input class="form-check-input" type="checkbox" value="<?= $arrPai["id"]; ?>" name="pai[]" id="pai-<?= $arrPai["id"]; ?>" onclick="setarCheckbox('pai-<?= $arrPai["id"]; ?>');" <?= (isset($moduloSelecionado[$arrPai["id"]])) ? $moduloSelecionado[$arrPai["id"]]["visualizar"] : ""; ?>>
                                                                    <?= $arrPai["nome"]; ?>
                                                                </label>
                                                            </div>
                                                        </div>
                                                        <div class="card-body">
                                                            <div class="input-group mb-3">
                                                                <?php foreach ($arrPai["filhos"] as $arrFilho) : ?>
                                                                    <div class="col-lg-3">
                                                                        <fieldset class="form-group">
                                                                            <legend data-toggle="tooltip" title="Selecione o que o usuário terá acesso. Se não selecionar nenhum, ele não terá acesso ao módulo.">
                                                                                <i class="<?= $arrFilho["icone"]; ?>"></i> <?= $arrFilho["nome"]; ?>
                                                                            </legend>
                                                                            <div class="form-check">
                                                                                <label class="form-check-label">
                                                                                    <input class="form-check-input pai-<?= $arrPai["id"]; ?>" type="checkbox" value="visualizar" name="<?= $arrFilho["id"]; ?>[]" <?= (isset($moduloSelecionado[$arrFilho["id"]])) ? $moduloSelecionado[$arrFilho["id"]]["visualizar"] : ""; ?>>
                                                                                    Visualizar
                                                                                </label>
                                                                            </div>
                                                                            <div class="form-check">
                                                                                <label class="form-check-label">
                                                                                    <input class="form-check-input pai-<?= $arrPai["id"]; ?>" type="checkbox" value="cadastrar" name="<?= $arrFilho["id"]; ?>[]" <?= (isset($moduloSelecionado[$arrFilho["id"]])) ? $moduloSelecionado[$arrFilho["id"]]["cadastrar"] : ""; ?>>
                                                                                    Cadastrar
                                                                                </label>
                                                                            </div>
                                                                            <div class="form-check">
                                                                                <label class="form-check-label">
                                                                                    <input class="form-check-input pai-<?= $arrPai["id"]; ?>" type="checkbox" value="editar" name="<?= $arrFilho["id"]; ?>[]" <?= (isset($moduloSelecionado[$arrFilho["id"]])) ? $moduloSelecionado[$arrFilho["id"]]["editar"] : ""; ?>>
                                                                                    Editar
                                                                                </label>
                                                                            </div>
                                                                            <div class="form-check">
                                                                                <label class="form-check-label">
                                                                                    <input class="form-check-input pai-<?= $arrPai["id"]; ?>" type="checkbox" value="excluir" name="<?= $arrFilho["id"]; ?>[]" <?= (isset($moduloSelecionado[$arrFilho["id"]])) ? $moduloSelecionado[$arrFilho["id"]]["excluir"] : ""; ?>>
                                                                                    Excluir
                                                                                </label>
                                                                            </div>
                                                                        </fieldset>
                                                                    </div>
                                                                <?php endforeach; ?>
                                                                <!--Fim Campo input-->
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php endforeach; ?>
                                        <!--Fim container Pai-->

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="card border-light mb-3">
                                                    <div class="card-header">
                                                        <div class="form-check">
                                                            <label class="form-check-label">
                                                                <input class="form-check-input" type="checkbox" value="" checked="" name="unico" id="unico" onclick="setarCheckbox('unico');">
                                                                Módulos Independentes
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="card-body">
                                                        <div class="input-group mb-3">
                                                            <?php foreach ($menu["unico"] as $valor) : ?>
                                                                <div class="col-lg-3">
                                                                    <fieldset class="form-group">
                                                                    <legend data-toggle="tooltip" title="Selecione o que o usuário terá acesso. Se não selecionar nenhum, ele não terá acesso ao módulo.">
                                                                            <i class="<?= $valor["icone"]; ?>"></i> <?= $valor["nome"]; ?>
                                                                        </legend>
                                                                        <div class="form-check">
                                                                            <label class="form-check-label">
                                                                                <input class="form-check-input unico" type="checkbox" value="visualizar" name="<?= $valor["id"]; ?>[]" <?= (isset($moduloSelecionado[$valor["id"]])) ? $moduloSelecionado[$valor["id"]]["visualizar"] : ""; ?>>
                                                                                Visualizar
                                                                            </label>
                                                                        </div>
                                                                        <div class="form-check">
                                                                            <label class="form-check-label">
                                                                                <input class="form-check-input unico" type="checkbox" value="cadastrar" name="<?= $valor["id"]; ?>[]" <?= (isset($moduloSelecionado[$valor["id"]])) ? $moduloSelecionado[$valor["id"]]["cadastrar"] : ""; ?>>
                                                                                Cadastrar
                                                                            </label>
                                                                        </div>
                                                                        <div class="form-check">
                                                                            <label class="form-check-label">
                                                                                <input class="form-check-input unico" type="checkbox" value="editar" name="<?= $valor["id"]; ?>[]" <?= (isset($moduloSelecionado[$valor["id"]])) ? $moduloSelecionado[$valor["id"]]["editar"] : ""; ?>>
                                                                                Editar
                                                                            </label>
                                                                        </div>
                                                                        <div class="form-check">
                                                                            <label class="form-check-label">
                                                                                <input class="form-check-input unico" type="checkbox" value="excluir" name="<?= $valor["id"]; ?>[]" <?= (isset($moduloSelecionado[$valor["id"]])) ? $moduloSelecionado[$valor["id"]]["excluir"] : ""; ?>>
                                                                                Excluir
                                                                            </label>
                                                                        </div>
                                                                    </fieldset>
                                                                </div>
                                                            <?php endforeach; ?>
                                                            <!--Fim Campo input-->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Fim container Unico-->

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="card border-light mb-3">
                                                    <div class="card-header">
                                                        <div class="form-check">
                                                            <label class="form-check-label">
                                                                <input class="form-check-input" type="checkbox" value="" checked="" name="config" id="config" onclick="setarCheckbox('config');">
                                                                Configurações
                                                            </label>
                                                        </div>
                                                    </div>
                                                    <div class="card-body">
                                                        <div class="input-group mb-3">
                                                            <?php foreach ($menu["config"] as $valor) : ?>
                                                                <div class="col-lg-3">
                                                                    <fieldset class="form-group">
                                                                    <legend data-toggle="tooltip" title="Selecione o que o usuário terá acesso. Se não selecionar nenhum, ele não terá acesso ao módulo.">
                                                                            <i class="<?= $valor["icone"]; ?>"></i> <?= $valor["nome"]; ?>
                                                                        </legend>
                                                                        <div class="form-check">
                                                                            <label class="form-check-label">
                                                                                <input class="form-check-input config" type="checkbox" value="visualizar" name="<?= $valor["id"]; ?>[]" <?= (isset($moduloSelecionado[$valor["id"]])) ? $moduloSelecionado[$valor["id"]]["visualizar"] : ""; ?>>
                                                                                Visualizar
                                                                            </label>
                                                                        </div>
                                                                        <div class="form-check">
                                                                            <label class="form-check-label">
                                                                                <input class="form-check-input config" type="checkbox" value="cadastrar" name="<?= $valor["id"]; ?>[]" <?= (isset($moduloSelecionado[$valor["id"]])) ? $moduloSelecionado[$valor["id"]]["cadastrar"] : ""; ?>>
                                                                                Cadastrar
                                                                            </label>
                                                                        </div>
                                                                        <div class="form-check">
                                                                            <label class="form-check-label">
                                                                                <input class="form-check-input config" type="checkbox" value="editar" name="<?= $valor["id"]; ?>[]" <?= (isset($moduloSelecionado[$valor["id"]])) ? $moduloSelecionado[$valor["id"]]["editar"] : ""; ?>>
                                                                                Editar
                                                                            </label>
                                                                        </div>
                                                                        <div class="form-check">
                                                                            <label class="form-check-label">
                                                                                <input class="form-check-input config" type="checkbox" value="excluir" name="<?= $valor["id"]; ?>[]" <?= (isset($moduloSelecionado[$valor["id"]])) ? $moduloSelecionado[$valor["id"]]["excluir"] : ""; ?>>
                                                                                Excluir
                                                                            </label>
                                                                        </div>
                                                                    </fieldset>
                                                                </div>
                                                            <?php endforeach; ?>
                                                            <!--Fim Campo input-->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Fim container Config-->

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <button type="button" class="btn btn-success float-right botao-efeito" id="bt-salvar" onclick="formSubmit('#cadastroForm','<?= $urlAction; ?>',false);">
                                                    Salvar <i class="mdi mdi-check"></i>
                                                </button>
                                                <div id="resposta-form" class="float-right" style="margin: 0 10px 0 0;">
                                                    <!--Resposta do Server-->
                                                    <p>Campos com * são obrigatórios</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </section>


                        </div>
                    </div>
                </div>



            </div> <!-- end container-fluid -->
        </div>
    </div>
    <!--CONTEÚDO-->


    <!--FOOTER-->
    <?= $this->loadview('admin/includes/footer'); ?>

    <!--JAVSCRIPT-->
    <?= $this->loadview('admin/includes/scripts'); ?>

    <script>
        /*$(document).ready(function(){
            $('#whatsapp').mask('(00) 0 0000-0000');
            $('#nascimento').mask('00/00/0000');
        });*/
        //Lendo Enter do documento para chamar o form
        $("input[type='text']").on('keydown', function(event) {
            if (event.keyCode === 13){
                formSubmit('#cadastroForm','<?= $urlAction; ?>');
            }
        });        
    </script>
</body>

</html>