<section class="main-slider main-slider-two">
    <div class="swiper-container thm-swiper__slider" data-swiper-options='{"slidesPerView": 1, "loop": true,
                    "effect": "fade",
                    "pagination": {
                        "el": "#main-slider-pagination",
                        "type": "bullets",
                        "clickable": true
                    },
                    "navigation": {
                        "nextEl": "#main-slider__swiper-button-next",
                        "prevEl": "#main-slider__swiper-button-prev"
                    },
                    "autoplay": {
                        "delay": 10000
                    }}'>
        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <div class="image-layer" style="background-image: url(<?= TEMPLATE_MONIZ; ?>/images/backgrounds/main-slider-2-1.jpg);">
                </div>

                <div class="image-layer-overlay"></div>
                <div class="main-slider-two-shape-1"></div>
                <div class="main-slider-two-shape-2"></div>
                <!-- /.image-layer -->
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <div class="main-slider__content">
                                <p>Bem vindo ao nosso site</p>
                                <h2>Acesse nossa <br> apresentação online</h2>
                                <a href="<?= SITE_URL; ?>/portfolio/j6-solucoes-digitais.pdf" class="thm-btn"><span>Acessar apresentação</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="image-layer" style="background-image: url(<?= TEMPLATE_MONIZ; ?>/images/backgrounds/main-slider-2-2.jpg);">
                </div>

                <div class="image-layer-overlay"></div>
                <div class="main-slider-two-shape-1"></div>
                <div class="main-slider-two-shape-2"></div>
                <!-- /.image-layer -->
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <div class="main-slider__content">
                                <p>Na J6 soluções digitais você encontra</p>
                                <h2>Marketing digital <br> de qualidade</h2>
                                <a href="<?= SITE_URL; ?>/marketing-digital" class="thm-btn"><span>Quero saber mais</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="image-layer" style="background-image: url(<?= TEMPLATE_MONIZ; ?>/images/backgrounds/main-slider-2-3.jpg);">
                </div>

                <div class="image-layer-overlay"></div>
                <div class="main-slider-two-shape-1"></div>
                <div class="main-slider-two-shape-2"></div>
                <!-- /.image-layer -->
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <div class="main-slider__content">
                                <p>Na J6 soluções digitais você encontra</p>
                                <h2>Artes digitais <br> para o seu negócio</h2>
                                <a href="<?= SITE_URL; ?>/artes-digitais" class="thm-btn"><span>Quero saber mais</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="image-layer" style="background-image: url(<?= TEMPLATE_MONIZ; ?>/images/backgrounds/main-slider-2-4.jpg);">
                </div>

                <div class="image-layer-overlay"></div>
                <div class="main-slider-two-shape-1"></div>
                <div class="main-slider-two-shape-2"></div>
                <!-- /.image-layer -->
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <div class="main-slider__content">
                                <p>Na J6 soluções digitais você encontra</p>
                                <h2>Edição de<br> vídeos surpreendentes</h2>
                                <a href="<?= SITE_URL; ?>/edicao-de-videos" class="thm-btn"><span>Quero saber mais</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="image-layer" style="background-image: url(<?= TEMPLATE_MONIZ; ?>/images/backgrounds/main-slider-2-5.jpg);">
                </div>

                <div class="image-layer-overlay"></div>
                <div class="main-slider-two-shape-1"></div>
                <div class="main-slider-two-shape-2"></div>
                <!-- /.image-layer -->
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <div class="main-slider__content">
                                <p>Na J6 soluções digitais você encontra</p>
                                <h2>Desenvolvimento de <br> web sites profissionais</h2>
                                <a href="<?= SITE_URL; ?>/desenvolvimento-de-sites" class="thm-btn"><span>Quero saber mais</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="image-layer" style="background-image: url(<?= TEMPLATE_MONIZ; ?>/images/backgrounds/main-slider-2-6.jpg);">
                </div>

                <div class="image-layer-overlay"></div>
                <div class="main-slider-two-shape-1"></div>
                <div class="main-slider-two-shape-2"></div>
                <!-- /.image-layer -->
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 text-center">
                            <div class="main-slider__content">
                                <p>Na J6 soluções digitais você encontra</p>
                                <h2>Sistemas<br>  web para o seu negócio</h2>
                                <a href="<?= SITE_URL; ?>/sistemas-web" class="thm-btn"><span>Quero saber mais</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- If we need navigation buttons -->
        <div class="slider-bottom-box clearfix">
            <div class="swiper-pagination" id="main-slider-pagination"></div>
        </div>
    </div>
</section>