<footer class="site-footer">
    <div class="site-footer__top">
        <div class="site-footer-top-bg" style="background-image: url(<?= TEMPLATE_MONIZ; ?>/images/backgrounds/site-footer-bg.jpg)"></div>
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-lg-6 col-md-6 wow fadeInUp" data-wow-delay="100ms">
                    <div class="footer-widget__column footer-widget__about">
                        <div class="footer-widget__about-logo">
                            <a href="index.html"><img src="<?= TEMPLATE_MONIZ; ?>/images/resources/footer-logo.png" alt=""></a>
                        </div>
                        <p class="footer-widget__about-text">Soluções completas em serviços digitais, você encontra aqui!<br>Nos sigam nas redes sociais.</p>
                        <div class="footer-widget__about-social-list">
                            <a href="https://www.facebook.com/j6solucoesdigitais" class="clr-fb"><i class="fab fa-facebook"></i></a>
                            <a href="https://www.instagram.com/j6solucoesdigitais/" class="clr-ins"><i class="fab fa-instagram"></i></a>
                            <a href="https://www.linkedin.com/company/j6-solu%C3%A7%C3%B5es-digitais/?viewAsMember=true" class="clr-dri"><i class="fab fa-linkedin"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2 col-lg-6 col-md-6 wow fadeInUp" data-wow-delay="200ms">
                    <div class="footer-widget__column footer-widget__explore clearfix">
                        <h3 class="footer-widget__title">Explore</h3>
                        <ul class="footer-widget__explore-list list-unstyled">
                            <li><a href="<?=SITE_URL;?>/sobre">Sobre a J6 </a></li>
                            <li><a href="<?=SITE_URL;?>/blog">Blog</a></li>
                            <li><a href="<?=SITE_URL;?>/duvidas-e-solucoes">Dúvidas e Soluções</a></li>
                            <li><a href="<?=SITE_URL;?>/portfolio">Portfólio</a></li>
                            <li><a href="<?=SITE_URL;?>/fale-conosco">Fale Conosco</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-6 col-md-6 wow fadeInUp" data-wow-delay="400ms">
                    <div class="footer-widget__column footer-widget__contact">
                        <h3 class="footer-widget__title">Contato</h3>
                        <p class="footer-widget__contact-text">Balneário Piçarras, SC</p>
                        <div class="footer-widget__contact-info">
                            <p>
                                <a href="tel:47 99775-8281" class="footer-widget__contact-phone">(47) 99775-8281</a>
                                <a href="mailto:diretoria@j6.net.br" class="footer-widget__contact-mail">diretoria@j6.net.br</a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-6 col-md-6 wow fadeInUp" data-wow-delay="400ms">
                    <div class="footer-widget__column footer-widget__newsletter">
                        <h3 class="footer-widget__title">E a frase do dia é:</h3>
                        <div class="footer-widget__newsletter-bottom">
                            <div class="footer-widget__newsletter-bottom-text">
                                <p>As pessoas costumam dizer que a motivação não dura sempre. Bem, nem o efeito do banho, por isso recomenda-se diariamente.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="site-footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="site-footer-bottom__inner">
                        <p class="site-footer-bottom__copy-right">© <?= date('Y'); ?> <a href="https://www.j6.net.br">j6.net.br</a> <span class="d-none d-md-inline-block"> - Criado com <i class="far fa-heart"></i></span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>