<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Marketing Digital, Sites Profissionais, Sistemas Web - J6 Soluções Digitais</title>
    <!-- favicons Icons -->
    <link rel="icon" type="image/png" href="<?=TEMPLATE_MONIZ; ?>/images/favicons/favicon.png" />
    <meta name="description" content="J6 Soluções Digitais completa para sua empresa. Desenvolvimento de sites, sistemas web, marketing digital e artes offline." />

    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@300;400;700&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/animate/animate.min.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/fontawesome/css/all.min.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/jarallax/jarallax.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/jquery-magnific-popup/jquery.magnific-popup.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/nouislider/nouislider.min.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/nouislider/nouislider.pips.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/odometer/odometer.min.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/swiper/swiper.min.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/moniz-icons/style.css">
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/tiny-slider/tiny-slider.min.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/reey-font/stylesheet.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/owl-carousel/owl.carousel.min.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/owl-carousel/owl.theme.default.min.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/twentytwenty/twentytwenty.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/bxslider/jquery.bxslider.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/bootstrap-select/css/bootstrap-select.min.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/vegas/vegas.min.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/jquery-ui/jquery-ui.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/vendors/timepicker/timePicker.css" />

    <!-- template styles -->
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/css/moniz.css" />
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/css/moniz-responsive.css" />

    <!-- RTL Styles -->
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/css/moniz-rtl.css">

    <!-- color css -->
    <link rel="stylesheet" id="jssDefault" href="<?=TEMPLATE_MONIZ; ?>/css/colors/color-2.css">
    <link rel="stylesheet" id="jssMode" href="<?=TEMPLATE_MONIZ; ?>/css/modes/moniz-normal.css">

    <!-- toolbar css -->
    <link rel="stylesheet" href="<?=TEMPLATE_MONIZ; ?>/css/moniz-toolbar.css">

</head>