<header class="main-header-two clearfix">
    <nav class="main-menu main-menu-two clearfix">
        <div class="main-menu-two-wrapper clearfix">
            <div class="main-menu-two-wrapper__left">
                <div class="main-menu-two-wrapper__logo">
                    <a href="<?= SITE_URL; ?>"><img src="<?= TEMPLATE_MONIZ; ?>/images/resources/logo.png" alt="J6 Soluções Digitais"></a>
                </div>
                <div class="main-menu-two-wrapper__main-menu">
                    <a href="#" class="mobile-nav__toggler">
                        <span></span>
                    </a>
                    <ul class="main-menu__list">
                        <li class="dropdown">
                            <a href="<?=SITE_URL; ?>/marketing-digital" style="color:#01B7FF;">Marketing Digital</a>
                            <ul>
                                <li><a href="<?= SITE_URL; ?>/assessoria-de-marketing-digital">Assessoria de marketing digital</a></li>
                                <li><a href="<?= SITE_URL; ?>/gestao-de-redes-sociais">Gestão de Redes Sociais</a></li>
                                <li><a href="<?= SITE_URL; ?>/marketing-de-performance">Marketing de performance</a></li>
                        </li>
                    </ul>
                    </li>
                    <li class="dropdown">
                        <a href="<?=SITE_URL; ?>/artes-digitais" style="color:#FF1946;">Artes Digitais</a>
                        <ul>
                            <li><a href="<?= SITE_URL; ?>/artes-para-redes-sociais">Artes para redes sociais</a></li>
                            <li><a href="<?= SITE_URL; ?>/artes-para-email-e-whatsapp">Artes para email e whatsapp</a></li>
                            <li><a href="<?= SITE_URL; ?>/outras-artes">Outras artes</a></li>
                    </li>
                    </ul>
                    </li>
                    <li class="dropdown">
                        <a href="<?=SITE_URL; ?>/edicao-de-videos" style="color:#FFF319;">Edição de Vídeos</a>
                        <ul>
                            <li><a href="<?= SITE_URL; ?>/videos-para-redes-sociais">Vídeos para redes sociais</a></li>
                            <li><a href="<?= SITE_URL; ?>/videos-publicitarios">Vídeos publicitários</a></li>
                    </li>
                    </ul>
                    </li>
                    <li class="dropdown">
                        <a href="<?=SITE_URL; ?>/criacao-de-sites" style="color:#1285B3;">Criação de sites</a>
                        <ul>
                            <li><a href="<?= SITE_URL; ?>/desenvolvimento-de-sites" style="hover: background-color: #1285b3;">Desenvolvimento de sites</a></li>
                            <li><a href="<?= SITE_URL; ?>/manutencao-de-sites">Manutenção de sites</a></li>
                    </li>
                    </ul>
                    </li>
                    <li class="dropdown">
                        <a href="<?=SITE_URL; ?>/sistemas-web" style="color:#B3AA09;">Sistema web</a>
                        <ul>
                            <li><a href="<?= SITE_URL; ?>/desenvolvimento-de-sistemas-web">Desenvolvimento de sitemas web</a></li>
                    </li>
                    </ul>
                    </li>
                    </ul>
                </div>
            </div>
            <div class="main-menu-wrapper__right">
                <div class="main-menu-wrapper__right-contact-box">
                    <div class="main-menu-wrapper__right-contact-icon">
                        <i class="fas fa-smile"></i>
                    </div>
                    <div class="main-menu-wrapper__right-contact-number">
                        <a href="<?= SITE_URL; ?>/fale-conosco">Fale Conosco</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>