<div class="mobile-nav__wrapper">
        <div class="mobile-nav__overlay mobile-nav__toggler"></div>
        <!-- /.mobile-nav__overlay -->
        <div class="mobile-nav__content">
            <span class="mobile-nav__close mobile-nav__toggler"></span>

            <div class="logo-box">
                <a href="index.html" aria-label="logo image"><img src="<?=TEMPLATE_MONIZ; ?>/images/resources/logo.png" width="155"
                        alt="" /></a>
            </div>
            <!-- /.logo-box -->
            <div class="mobile-nav__container"></div>
            <!-- /.mobile-nav__container -->

            <ul class="mobile-nav__contact list-unstyled">
                <li>
                    <i class="fa fa-envelope"></i>
                    <a href="mailto:diretoria@j6.net.br">diretoria@j6.net.br</a>
                </li>
                <li>
                    <i class="fa fa-phone-alt"></i>
                    <a href="tel:47997758281">(47) 99775-8281</a>
                </li>
            </ul><!-- /.mobile-nav__contact -->
            <div class="mobile-nav__top">
                <div class="mobile-nav__social">
                    <a href="https://www.facebook.com/j6solucoesdigitais" class="fab fa-facebook-square"></a>
                    <a href="https://www.instagram.com/j6solucoesdigitais/" class="fab fa-instagram"></a>
                    <a href="https://www.linkedin.com/company/j6-solu%C3%A7%C3%B5es-digitais/?viewAsMember=true" class="fab fa-linkedin"></a>                    
                </div><!-- /.mobile-nav__social -->
            </div><!-- /.mobile-nav__top -->

        </div>
        <!-- /.mobile-nav__content -->
    </div>
    <!-- /.mobile-nav__wrapper -->

    <div id="hi-whatsapp" onclick="location.href='https://whatsa.me/5547997758281/?t=J6%20Solu%C3%A7%C3%B5es%20Digitais'">
        <i class="fab fa-whatsapp"></i>
    </div>