<?php
    //Recebendo dados do controller
    $dados["seo"] = $seo;
?>
<!DOCTYPE html>
<html lang="pt-br">

<?=$this->loadview('templates/inovex/includes/head',$dados);?>

<body>

    <?=$this->loadview('templates/inovex/includes/preloader');?>

    <div class="page-wrapper">

        <?=$this->loadview('templates/inovex/includes/navbar');?>

        <?=$this->loadview('templates/inovex/includes/banner_home');?>

        <?=$this->loadview('templates/inovex/includes/clientes_home');?>


        <section class="about-one">
            <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/bg-shape-1-1.png" class="error-404__bg-shape-1" alt="">
            <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/bg-shape-1-2.png" class="error-404__bg-shape-2" alt="">
            <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/bg-shape-1-3.png" class="error-404__bg-shape-3" alt="">

            <div class="error-404__bubble-1"></div><!-- /.error-404__bubble-1 -->
            <div class="error-404__bubble-2"></div><!-- /.error-404__bubble-2 -->
            <div class="error-404__bubble-3"></div><!-- /.error-404__bubble-3 -->
            <div class="error-404__bubble-4"></div><!-- /.error-404__bubble-4 -->
            <div class="error-404__bubble-5"></div><!-- /.error-404__bubble-5 -->
            <div class="error-404__bubble-6"></div><!-- /.error-404__bubble-6 -->
            <div class="error-404__bubble-7"></div><!-- /.error-404__bubble-7 -->
            <div class="error-404__bubble-8"></div><!-- /.error-404__bubble-8 -->
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="about-one__content">
                            <div class="block-title text-left">
                                <p class="color-2"><span>Why Choose Us?</span></p>
                                <h3>There Are Many SEO Sites <br> <span>But Why Choose Us?</span></h3>
                            </div><!-- /.block-title text-center -->
                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed eiusmod <br> tempor
                                incididunt labore.</p>
                            <div class="about-one__box-wrapper">
                                <div class="about-one__box">
                                    <div class="about-one__box-icon">
                                        <i class="fa fa-check"></i>
                                    </div><!-- /.about-one__box-icon -->
                                    <div class="about-one__box-content">
                                        <h3>Best Performence</h3>
                                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit <br> eiusmod tempor
                                            incididunt ut labore.</p>
                                    </div><!-- /.about-one__box-content -->
                                </div><!-- /.about-one__box -->
                                <div class="about-one__box">
                                    <div class="about-one__box-icon">
                                        <i class="fa fa-check"></i>
                                    </div><!-- /.about-one__box-icon -->
                                    <div class="about-one__box-content">
                                        <h3>Dedicated Team Member</h3>
                                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit <br> eiusmod tempor
                                            incididunt ut labore.</p>
                                    </div><!-- /.about-one__box-content -->
                                </div><!-- /.about-one__box -->
                                <div class="about-one__box">
                                    <div class="about-one__box-icon">
                                        <i class="fa fa-check"></i>
                                    </div><!-- /.about-one__box-icon -->
                                    <div class="about-one__box-content">
                                        <h3>24/7 Hours Support</h3>
                                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit <br> eiusmod tempor
                                            incididunt ut labore.</p>
                                    </div><!-- /.about-one__box-content -->
                                </div><!-- /.about-one__box -->
                            </div><!-- /.about-one__box-wrapper -->
                        </div><!-- /.about-one__content -->
                    </div><!-- /.col-lg-6 -->
                    <div class="col-lg-6 d-flex">
                        <div class="my-auto">
                            <div class="about-one__image wow slideInDown" data-wow-duration="1500ms">
                                <img src="<?=TEMPLATE_INOVEX;?>/images/mocups/about-1-moc-1.png" alt="">
                            </div><!-- /.about-one__image -->
                        </div><!-- /.my-auto -->
                    </div><!-- /.col-lg-6 -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </section><!-- /.about-one -->

        <section class="service-one service-one__home-three">
            <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/service-1-h3-shape-1.png" class="service-one__home-three__bg-1" alt="">
            <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/service-1-h3-shape-2.png" class="service-one__home-three__bg-2" alt="">
            <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/service-1-h3-shape-3.png" class="service-one__home-three__bg-3" alt="">
            <div class="container">
                <div class="block-title text-center">
                    <p><span>Our Services</span></p>
                    <h3>We Provided Best Digital <br> <span>Services</span></h3>
                </div><!-- /.block-title text-center -->
                <div class="row high-gutters">
                    <div class="col-lg-6 col-md-12 wow fadeInLeft" data-wow-duration="1500ms">
                        <div class="service-one__single">
                            <div class="service-one__icon">
                                <div class="service-one__icon-inner">
                                    <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/service-i-1.png" alt="">
                                </div><!-- /.service-one__icon-inner -->
                            </div><!-- /.service-one__icon -->
                            <div class="service-one__content">
                                <h3><a href="service-details.html">Content Marketing</a></h3>
                                <p>Lorem ipsum dolor amet consectetur adipisicing sed do eiusmod tempor. incididunt
                                    labore.</p>
                            </div><!-- /.service-one__content -->
                        </div><!-- /.service-one__single -->
                    </div><!-- /.col-lg-6 col-md-12 -->
                    <div class="col-lg-6 col-md-12 wow fadeInRight" data-wow-duration="1500ms">
                        <div class="service-one__single">
                            <div class="service-one__icon">
                                <div class="service-one__icon-inner">
                                    <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/service-i-2.png" alt="">
                                </div><!-- /.service-one__icon-inner -->
                            </div><!-- /.service-one__icon -->
                            <div class="service-one__content">
                                <h3><a href="service-details.html">Social Marketing</a></h3>
                                <p>Lorem ipsum dolor amet consectetur adipisicing sed do eiusmod tempor. incididunt
                                    labore.</p>
                            </div><!-- /.service-one__content -->
                        </div><!-- /.service-one__single -->
                    </div><!-- /.col-lg-6 col-md-12 -->
                    <div class="col-lg-6 col-md-12 wow fadeInLeft" data-wow-duration="1500ms">
                        <div class="service-one__single">
                            <div class="service-one__icon">
                                <div class="service-one__icon-inner">
                                    <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/service-i-3.png" alt="">
                                </div><!-- /.service-one__icon-inner -->
                            </div><!-- /.service-one__icon -->
                            <div class="service-one__content">
                                <h3><a href="service-details.html">SEO Optimization</a></h3>
                                <p>Lorem ipsum dolor amet consectetur adipisicing sed do eiusmod tempor. incididunt
                                    labore.</p>
                            </div><!-- /.service-one__content -->
                        </div><!-- /.service-one__single -->
                    </div><!-- /.col-lg-6 col-md-12 -->
                    <div class="col-lg-6 col-md-12 wow fadeInRight" data-wow-duration="1500ms">
                        <div class="service-one__single">
                            <div class="service-one__icon">
                                <div class="service-one__icon-inner">
                                    <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/service-i-4.png" alt="">
                                </div><!-- /.service-one__icon-inner -->
                            </div><!-- /.service-one__icon -->
                            <div class="service-one__content">
                                <h3><a href="service-details.html">PPC Advertising</a></h3>
                                <p>Lorem ipsum dolor amet consectetur adipisicing sed do eiusmod tempor. incididunt
                                    labore.</p>
                            </div><!-- /.service-one__content -->
                        </div><!-- /.service-one__single -->
                    </div><!-- /.col-lg-6 col-md-12 -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </section><!-- /.service-one -->


        <section class="testimonials-one testimonials-one__about-one testimonials-one__home-three">
            <div class="container">
                <div class="block-title text-left">
                    <p class="color-2"><span>Our Testimonial</span></p>
                    <h3>We Care Client’s Issues <br> <span>So We are Popular.</span></h3>
                </div><!-- /.block-title text-center -->
                <div class="testimonials-one__carousel thm__owl-carousel owl-carousel owl-theme" data-options='{
                    "items": 3, "margin": 40, "smartSpeed": 700, "autoplay": true, "autoplayTimeout": 5000,
                    "autoplayHoverPause": true, "nav": false, "dots": false, "loop": true, "responsive": {
                        "0": { "items": 1, "margin": 0},
                        "767": { "items": 1, "margin": 0},
                        "991": { "items": 2, "margin": 40},
                        "1199": { "items": 2, "margin": 40},
                        "1200": { "items": 3, "margin": 40}
                    }
                }'>
                    <div class="item">
                        <div class="testimonials-one__single">
                            <div class="testimonials-one__icon">
                                <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/testi-qoute-1-1.png" alt="">
                            </div><!-- /.testimonials-one__icon -->
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                                ut labore et dolore magna aliqua.Lorem ipsum magna aliqua.</p>
                            <h3>Derek Baldwin</h3>
                        </div><!-- /.testimonials-one__single -->
                    </div><!-- /.item -->
                    <div class="item">
                        <div class="testimonials-one__single">
                            <div class="testimonials-one__icon">
                                <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/testi-qoute-1-1.png" alt="">
                            </div><!-- /.testimonials-one__icon -->
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                                ut labore et dolore magna aliqua.Lorem ipsum magna aliqua.</p>
                            <h3>Charles Morris</h3>
                        </div><!-- /.testimonials-one__single -->
                    </div><!-- /.item -->
                    <div class="item">
                        <div class="testimonials-one__single">
                            <div class="testimonials-one__icon">
                                <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/testi-qoute-1-1.png" alt="">
                            </div><!-- /.testimonials-one__icon -->
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                                ut labore et dolore magna aliqua.Lorem ipsum magna aliqua.</p>
                            <h3>Eula Rowe</h3>
                        </div><!-- /.testimonials-one__single -->
                    </div><!-- /.item -->
                    <div class="item">
                        <div class="testimonials-one__single">
                            <div class="testimonials-one__icon">
                                <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/testi-qoute-1-1.png" alt="">
                            </div><!-- /.testimonials-one__icon -->
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                                ut labore et dolore magna aliqua.Lorem ipsum magna aliqua.</p>
                            <h3>Jose Flores</h3>
                        </div><!-- /.testimonials-one__single -->
                    </div><!-- /.item -->
                </div><!-- /.testimonials-one__carousel -->
            </div><!-- /.container -->
        </section><!-- /.testimonials-one -->

        <section class="faq-one__form-wrap faq-one__home-three faq-one">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="faq-one__form-image">
                            <img src="<?=TEMPLATE_INOVEX;?>/images/mocups/faq-moc-1-1.png" alt="">
                            <img src="<?=TEMPLATE_INOVEX;?>/images/mocups/faq-moc-1-2.png" alt="">
                        </div><!-- /.faq-one__form-image -->
                    </div><!-- /.col-lg-6 -->
                    <div class="col-lg-6 d-flex">
                        <div class="my-auto">
                            <div class="block-title text-left">
                                <p><span>Our FAQ’S</span></p>
                                <h3>Freequently Ask <br> <span>Questions.</span></h3>
                            </div><!-- /.block-title text-center -->
                            <div class="accrodion-grp" data-grp-name="career-one__accrodion">
                                <div class="accrodion ">
                                    <div class="accrodion-title">
                                        <h4>Can Users Choose to Install the SEO App?</h4>
                                    </div>
                                    <div class="accrodion-content">
                                        <div class="inner">
                                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit eusmod tempor
                                                incididunt labore dolore magna aliqua. enim minim veniam quis nostrud.
                                            </p>
                                        </div><!-- /.inner -->
                                    </div>
                                </div>
                                <div class="accrodion active">
                                    <div class="accrodion-title">
                                        <h4>Does Disabling SEO Free Up Space?</h4>
                                    </div>
                                    <div class="accrodion-content">
                                        <div class="inner">
                                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit eusmod tempor
                                                incididunt labore dolore magna aliqua. enim minim veniam quis nostrud.
                                            </p>
                                        </div><!-- /.inner -->
                                    </div>
                                </div>
                                <div class="accrodion">
                                    <div class="accrodion-title">
                                        <h4>Why are Mobile SEO Apps Important?</h4>
                                    </div>
                                    <div class="accrodion-content">
                                        <div class="inner">
                                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit eusmod tempor
                                                incididunt labore dolore magna aliqua. enim minim veniam quis nostrud.
                                            </p>
                                        </div><!-- /.inner -->
                                    </div>
                                </div>
                                <div class="accrodion">
                                    <div class="accrodion-title">
                                        <h4>How Does the Moodle SEO Work? </h4>
                                    </div>
                                    <div class="accrodion-content">
                                        <div class="inner">
                                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit eusmod tempor
                                                incididunt labore dolore magna aliqua. enim minim veniam quis nostrud.
                                            </p>
                                        </div><!-- /.inner -->
                                    </div>
                                </div>
                            </div>
                        </div><!-- /.my-auto -->
                    </div><!-- /.col-lg-6 -->
                </div><!-- /.row -->

            </div><!-- /.container -->
        </section><!-- /.faq-one__form-wrap -->

        <?=$this->loadview('templates/inovex/includes/blog_home');?>
        <?=$this->loadview('templates/inovex/includes/footer');?>

    </div><!-- /.page-wrapper -->

    <?=$this->loadview('templates/inovex/includes/scripts_search');?>

</body>

</html>