<?php
$dados["notificacoes"] = $notificacoes;
$dados["totalNotificacoesNaoLidas"] = $totalNotificacoesNaoLidas;
?>
<!doctype html>
<html lang="pt-br">
<!--HEAD + CSS-->
<?= $this->loadview('admin/includes/head'); ?>
<style>
    .numero-destaque {
        font-size: 80px;
        font-weight: bold;
        text-align: center;
    }
</style>

<body>
    <!--TOPO + MENU-->
    <?= $this->loadview('admin/includes/header', $dados); ?>

    <!--CONTEÚDO-->
    <div class="wrapper">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-md-8">
                                <h4 class="page-title m-0">
                                    <?= Common::getDiaSemana().", ".date("d/m/Y"); ?>
                                </h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-3 col-xl-3">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="m-t-0">Leads</h4>
                            <div style="min-height: 300px">
                                <div class="col-sm-12 numero-destaque"><?=$totalLeads; ?></div>
                                <h5>Recebidos</h5>
                                <ul class="list-group">
                                    <?php foreach($leads3Meses as $indice => $valor): ?>
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        <?=$indice; ?>
                                        <span class="badge badge-default badge-pill"><?=$valor["total"]; ?></span>
                                    </li>
                                    <?php endforeach; ?>
                                </ul>
                                <div class="col-sm-12" style="text-align: center; margin-top: 10px;">
                                    <a href="<?= SITE_URL; ?>/leads">
                                        <button type="button" class="btn btn-sistema">Acessar Leads</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3 col-xl-3">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="m-t-0">Blog</h4>
                            <div style="min-height: 300px">
                                <div class="col-sm-12 numero-destaque"><?=$totalBlog; ?></div>
                                <h5>Matérias</h5>
                                <ul class="list-group">
                                    <?php foreach($blog3Meses as $indice => $valor): ?>
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        <?=$indice; ?>
                                        <span class="badge badge-default badge-pill"><?=$valor["total"]; ?></span>
                                    </li>
                                    <?php endforeach; ?>
                                </ul>
                                <div class="col-sm-12" style="text-align: center; margin-top: 10px;">
                                    <a href="<?= SITE_URL; ?>/blog-admin">
                                        <button type="button" class="btn btn-sistema">Acessar Blog</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-xl-6">
                    <div class="card" style="min-height: 300px;">
                        <div class="card-body">
                            <div class="card-body user-card">
                                <div class="media-main">
                                    <a class="float-left" href="#">
                                        <img src="<?= STATIC_URL; ?>/img/sistema/<?= $configuracoes["dir_galeria"] . "/thumb450_" . $configuracoes["capa"]; ?>" class="logo-lg" height="75">
                                    </a>
                                    <div class="info pl-3">
                                        <h4 class="mt-3"><?= $configuracoes["cnpj"]; ?></h4>
                                        <p class="text-muted"><?= $configuracoes["razao_social"]; ?></p>
                                    </div>
                                </div>
                                <div class="clearfix"></div>

                                <p class="text-muted info-text"><?= $configuracoes["endereco"]; ?></p>
                                <hr>
                                <ul class="social-links list-inline m-b-0">
                                    <li class="list-inline-item">
                                        <a title="" data-placement="top" data-toggle="tooltip" class="tooltips" href="<?= $configuracoes["facebook"]; ?>" target="_blank" data-original-title="<?= $configuracoes["facebook"]; ?>"><i class="fab fa-facebook-f"></i></a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a title="" data-placement="top" data-toggle="tooltip" class="tooltips" href="<?= $configuracoes["instagram"]; ?>" target="_blank" data-original-title="<?= $configuracoes["instagram"]; ?>"><i class="fab fa-instagram"></i></a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a title="" data-placement="top" data-toggle="tooltip" class="tooltips" href="<?= $configuracoes["linkedin"]; ?>" target="_blank" data-original-title="<?= $configuracoes["linkedin"]; ?>"><i class="fab fa-linkedin"></i></a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a title="" data-placement="top" data-toggle="tooltip" class="tooltips" href="mailto:<?= $configuracoes["email"]; ?>" target="_blank" data-original-title="<?= $configuracoes["email"]; ?>"><i class="fa fa-envelope"></i></a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a title="" data-placement="top" data-toggle="tooltip" class="tooltips" href="<?= $configuracoes["site"]; ?>" target="_blank" data-original-title="<?= $configuracoes["site"]; ?>"><i class="far fa-hand-point-up"></i></a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a title="" data-placement="top" data-toggle="tooltip" class="tooltips" href="<?= Common::linkWhatsapp($configuracoes["telefone"]); ?>" target="_blank" data-original-title="<?= $configuracoes["telefone"]; ?>"><i class="fas fa-phone"></i></a>
                                    </li>
                                </ul>
                                <blockquote class="blockquote" style="margin-top: 20px;">
                                    <p><?=$fraseMotivacional["frase"]; ?></p>
                                    <footer class="blockquote-footer"><?=$fraseMotivacional["autor"]; ?></footer>
                                </blockquote>
                                <a href="<?= SITE_URL; ?>/busca/frase" class="btn btn-sistema" style="float: right;">
                                    <i class="fas fa-yin-yang"></i> Guru me inspire novamente
                                </a>                                
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- end container-fluid -->

            <div class="row">
                <div class="col-sm-8 col-xl-8">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="m-t-0">Mais Acessados do Sistema</h4>
                            <div class="row">
                                <?php foreach ($menuMaisAcessados as $valor) : ?>
                                    <a href="<?= SITE_URL,"/".$valor[0]["url"]; ?>" style="margin: 8px;">
                                        <button type="button" class="btn btn-sistema"><span class="badge badge-pill badge-secondary"><?=$valor[0]["qt"];?></span> <?= $valor[0]["nome"]; ?></button>
                                    </a>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 col-xl-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="card-body user-card">
                                <div class="media-main">
                                    <a class="float-left" href="#">
                                        <img class="thumb-lg rounded-circle" src="<?= Common::getImg("usuarios/{$usuario['dir_galeria']}/thumb150_{$usuario['capa']}", "user"); ?>" alt="">
                                    </a>
                                    <div class="info pl-3">
                                        <h4 class="mt-3"><?= $usuario["nome"]; ?></h4>
                                        <p class="text-muted">
                                            <?= $usuario["whatsapp"]; ?><br>
                                            <?= $usuario["email"]; ?>
                                        </p>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="row" style="margin-top: 10px;">
                                    <a href="<?= SITE_URL; ?>/meu-perfil/editar/<?= $usuario["id"]; ?>">
                                        <button type="button" class="btn btn-sistema">Editar meus dados</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- end container-fluid -->

        </div>
    </div>
    <!--CONTEÚDO-->


    <!--FOOTER-->
    <?= $this->loadview('admin/includes/footer'); ?>

    <!--JAVSCRIPT-->
    <?= $this->loadview('admin/includes/scripts'); ?>
</body>

</html>