<?php
$dados["notificacoes"] = $notificacoes;
$dados["totalNotificacoesNaoLidas"] = $totalNotificacoesNaoLidas;
?>
<!doctype html>
<html lang="pt-br">
<!--HEAD + CSS-->
<?= $this->loadview('admin/includes/head'); ?>
<style>
    .destaque-busca {
        font-size: 20px;
        font-weight: bold;
        text-align: center;
    }
</style>

<body>
    <!--TOPO + MENU-->
    <?= $this->loadview('admin/includes/header', $dados); ?>

    <!--CONTEÚDO-->
    <div class="wrapper">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12" style="margin: 30px 0;">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-md-8">
                                <h3 class="page-title m-0">
                                    <?= $titulo; ?>
                                </h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 col-xl-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row">
                                <blockquote class="blockquote" style="margin-top: 20px;">
                                    <p><?= $buscaPensador["frase"]; ?></p>
                                    <footer class="blockquote-footer"><?= $buscaPensador["autor"]; ?></footer>
                                </blockquote>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- end container-fluid -->

            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-sm">
                            </div>
                            <div class="col-sm bloco-botao-cadastro">
                                <a href="<?= SITE_URL; ?>/admin" class="btn btn-sistema-fechar" style="margin-right: 20px;">
                                    <i class="fas fa-arrow-left"></i> Voltar
                                </a>                                
                                <a href="<?= SITE_URL; ?>/busca/frase" class="btn btn-sistema">
                                    <i class="fas fa-yin-yang"></i> Guru me inspire novamente
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!--CONTEÚDO-->


    <!--FOOTER-->
    <?= $this->loadview('admin/includes/footer'); ?>

    <!--JAVSCRIPT-->
    <?= $this->loadview('admin/includes/scripts'); ?>
</body>

</html>