<?php
$dados["notificacoes"] = $notificacoes;
$dados["totalNotificacoesNaoLidas"] = $totalNotificacoesNaoLidas;
?>
<!doctype html>
<html lang="pt-br">
<!--HEAD + CSS-->
<?= $this->loadview('admin/includes/head'); ?>

<!-- DataTables -->
<link href="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
<link href="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/fixedHeader.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/scroller.bootstrap4.min.css" rel="stylesheet" type="text/css" />

<body>
    <!--TOPO + MENU-->
    <?= $this->loadview('admin/includes/header', $dados); ?>

    <!--CONTEÚDO-->
    <div class="wrapper">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-sm">

                                <ol class="breadcrumb">
                                    <?php foreach ($breadcrumb as $indice => $valor) : ?>
                                        <?php if (!empty($valor["url"])) : ?>
                                            <li class="breadcrumb-item"><a href="<?= $valor["url"]; ?>"><?= $valor["nome"]; ?></a></li>
                                        <?php else : ?>
                                            <li class="breadcrumb-item active"><a><?= $valor["nome"]; ?></a></li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ol>

                            </div>
                            <?php if ($cadastrar) : ?>
                                <div class="col-sm bloco-botao-cadastro">
                                    <a href="<?= $breadcrumb[0]["url"] ?>/cadastrar" class="btn-success botao-lista botao-lista botao-efeito">
                                        <i class="mdi mdi-gamepad-round"></i> NOVO CADASTRO
                                    </a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; width: 100%;">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Título</th>
                                        <th>Apelido</th>
                                        <th>Menu Topo</th>
                                        <th>Menu Rodapé</th>
                                        <th>Ordem</th>
                                        <th></th>
                                    </tr>
                                </thead>

                                <tbody>
                                    <?php foreach ($listagem as $indice => $valor) : ?>
                                        <tr>
                                            <td><?= $valor["id"]; ?></td>
                                            <td><?= Common::reduzirTexto($valor["titulo"]); ?></td>
                                            <td><?= Common::reduzirTexto($valor["pseudo_titulo"]); ?></td>
                                            <td>
                                                <?php if ($valor["id"] != 0) : ?>
                                                    <div class="radio radio-info form-check-inline" style="margin-left: 10px;">
                                                        <input type="radio" id="ativo-s-<?= $valor["id"] ?>" value="<?= $valor["id"]; ?>" name="ativo-<?= $valor["id"] ?>" <?= ($valor["menu_topo"] == "S") ? "checked=''" : ""; ?> onchange="ativarRegistro('<?= SITE_URL; ?>/menu-admin/ativar-registro/<?= $valor['id']; ?>/menu_topo');">
                                                        <label for="ativo-s-<?= $valor["id"] ?>">Sim </label>
                                                    </div>
                                                    <div class="radio radio-info form-check-inline">
                                                        <input type="radio" id="ativo-n-<?= $valor["id"] ?>" value="<?= $valor["id"]; ?>" name="ativo-<?= $valor["id"] ?>" <?= ($valor["menu_topo"] == "N") ? "checked=''" : ""; ?> onchange="ativarRegistro('<?= SITE_URL; ?>/menu-admin/ativar-registro/<?= $valor['id']; ?>/menu_topo');">
                                                        <label for="ativo-n-<?= $valor["id"] ?>">Não</label>
                                                    </div>
                                                <?php endif; ?>
                                            </td>
                                            <td>
                                                <?php if ($valor["id"] != 0) : ?>
                                                    <div class="radio radio-info form-check-inline" style="margin-left: 10px;">
                                                        <input type="radio" id="destaque-s-<?= $valor["id"] ?>" value="<?= $valor["id"]; ?>" name="destaque-<?= $valor["id"] ?>" <?= ($valor["menu_footer"] == "S") ? "checked=''" : ""; ?> onchange="ativarRegistro('<?= SITE_URL; ?>/menu-admin/ativar-registro/<?= $valor['id']; ?>/menu_footer');">
                                                        <label for="destaque-s-<?= $valor["id"] ?>">Sim </label>
                                                    </div>
                                                    <div class="radio radio-info form-check-inline">
                                                        <input type="radio" id="destaque-n-<?= $valor["id"] ?>" value="<?= $valor["id"]; ?>" name="destaque-<?= $valor["id"] ?>" <?= ($valor["menu_footer"] == "N") ? "checked=''" : ""; ?> onchange="ativarRegistro('<?= SITE_URL; ?>/menu-admin/ativar-registro/<?= $valor['id']; ?>/menu_footer');">
                                                        <label for="destaque-n-<?= $valor["id"] ?>">Não</label>
                                                    </div>
                                                <?php endif; ?>
                                            </td>
                                            <td>
                                                <?php if ($valor["id"] != 0) : ?>
                                                    <?= $valor["ordem"]; ?>
                                                <?php endif; ?>
                                            </td>
                                            <td>
                                                <?php if ($editar) : ?>
                                                    <a href="<?= SITE_URL; ?>/menu-admin/editar/<?= $valor['id']; ?>" class="botao-lista" title="Editar dados">
                                                        <i class="mdi mdi-lead-pencil"></i>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($excluir) : ?>
                                                    <a href="javascript:onclick=removerRegistro('<?= SITE_URL; ?>/menu-admin/remover/<?= $valor['id']; ?>','<?= $indice; ?>');" class="botao-lista" title="Excluir dados">
                                                        <i class="mdi mdi-close"></i>
                                                    </a>
                                                <?php endif; ?>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div> <!-- End Row -->
        </div>
    </div>
    <!--CONTEÚDO-->

    <!--FOOTER-->
    <?= $this->loadview('admin/includes/footer'); ?>

    <!--JAVSCRIPT-->
    <?= $this->loadview('admin/includes/scripts'); ?>

    <!-- Required datatable js-->
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Buttons examples -->
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/dataTables.buttons.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/buttons.bootstrap4.min.js"></script>

    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/jszip.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/pdfmake.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/vfs_fonts.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/buttons.html5.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/buttons.print.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/dataTables.fixedHeader.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/dataTables.keyTable.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/dataTables.scroller.min.js"></script>

    <!-- Responsive examples -->
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/dataTables.responsive.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/responsive.bootstrap4.min.js"></script>

    <!-- Datatable init js -->
    <script src="<?= TEMPLATE_HEXZY; ?>/pages/datatables.init.js"></script>
    <script>

    </script>
</body>

</html>