<section aria-label="footer" class="subfooter-white">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-xs-12">
                <div class="logo">
                    <img alt="logo" src="<?= TEMPLATE_BUILDSTATE; ?>/img/logo.png">
                </div>

                <p style="text-align: justify;">
                A J.Alves nasceu do sonho de ser a melhor loteadora do mercado, e a 45 anos estamos somando experiências e histórias nessa caminhada, transformando assim sonhos de famílias em realidade. Estamos inaugurando nossa nova sede que está localizada na Itoupava Central, Blumenau-SC.
                </p>
            </div>

            <div class="col-md-4 col-xs-12">

                <h3>
                    ÚLTIMAS NOTÍCIAS
                </h3>

                <div class="recent">
                    <a href="#">
                        <div class="date">
                            <div class="month">
                                <span class="date-month">05</span> <span class="name-month">JUL</span>
                            </div>
                        </div>

                        <div class="news">
                            J.Alves cria nota de esclarecimento a má serviço prestado a empresa.
                        </div>
                    </a>
                </div>

                <div class="recent">
                    <a href="#">
                        <div class="date">
                            <div class="month">
                                <span class="date-month">05</span> <span class="name-month">JUL</span>
                            </div>
                        </div>

                        <div class="news">
                            J.Alves cria nota de esclarecimento a má serviço prestado a empresa.
                        </div>
                    </a>
                </div>

                <div class="recent">
                    <a href="#">
                        <div class="date">
                            <div class="month">
                                <span class="date-month">05</span> <span class="name-month">JUL</span>
                            </div>
                        </div>

                        <div class="news">
                            J.Alves cria nota de esclarecimento a má serviço prestado a empresa.
                        </div>
                    </a>
                </div>

            </div>

            <div class="col-md-4 col-xs-12">
                <h3>
                    CONTATOS
                </h3>

                <address>
                    <span><i class="fa-solid fa-location-dot"></i> Rua Dr. Pedro Zimmermann, 4656 - Itoupava Central, Blumenau - SC, 89068-000</span>
                    <span><i class="fa-solid fa-phone"></i> (47) 3224-1048 (whatsapp)</span>
                    <span><i class="fa-solid fa-envelope"></i> <a href="mailto:contato@jalvesamarcadolote.com.br">contato@jalvesamarcadolote.com.br</a></span>
                </address>
            </div>
        </div>
    </div>
</section>
<!-- subfooter end -->

<!-- footer -->
<footer class="white">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                J.Alves - A marca do lote! &copy; Todos os direitos reservados.
            </div>

            <div class="col-sm-6">
                <div class="social-icons">
                    <a href="https://www.instagram.com/j.alvesamarcadolote"><span><i class="fa-brands fa-instagram"></i></span></a>
                    <a href="https://www.facebook.com/jalvesamarcadolote"><span><i class="fa-brands fa-facebook-f"></i></span></a>
                    <a href="https://goo.gl/maps/MEfpcapWaVzwV8nn6"><span><i class="fa-brands fa-google"></i></span></a>
                    <a href="https://www.youtube.com/channel/UCPGLG-rtynt6-J-bG2gxWoQ"><span><i class="fa-brands fa-youtube"></i></span></a>
                </div>
            </div>
        </div>
    </div>
</footer>

<div id="hi-whatsapp" onclick="location.href='https://api.whatsapp.com/send?phone=554732241048&amp;text=J.Alves A Marca do lote!'">
    <i class="fa fa-whatsapp"></i>
</div>