<head>
    <meta charset="utf-8">
    <title>Aqui um titulo do site</title>
    <meta content="" name="">
    <meta content="" name="">
    <meta content="" name="">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1" name="viewport">
    <!-- favicon -->
    <link href="<?= TEMPLATE_BUILDSTATE; ?>/img/favicon.png" rel="icon" sizes="32x32" type="image/png">
    <!-- Bootstrap CSS -->
    <link href="<?= TEMPLATE_BUILDSTATE; ?>/css/bootstrap.min.css" rel="stylesheet">
    <!-- font themify CSS -->
    <link rel="stylesheet" href="<?= TEMPLATE_BUILDSTATE; ?>/css/themify-icons.css">
    <!-- font awesome CSS -->
    <script src="https://kit.fontawesome.com/3e4c3e09c0.js" crossorigin="anonymous"></script>
    <!-- revolution slider css -->
    <link rel="stylesheet" type="text/css" href="<?= TEMPLATE_BUILDSTATE; ?>/css/fullscreen.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?= TEMPLATE_BUILDSTATE; ?>/rs-plugin/css/settings.css" media="screen" />
    <link rel="stylesheet" href="<?= TEMPLATE_BUILDSTATE; ?>/css/rev-settings.css" type="text/css">
    <!-- on3step CSS -->
    <link href="<?= TEMPLATE_BUILDSTATE; ?>/css/animated-on3step.css" rel="stylesheet">
    <link href="<?= TEMPLATE_BUILDSTATE; ?>/css/owl.carousel.css" rel="stylesheet">
    <link href="<?= TEMPLATE_BUILDSTATE; ?>/css/owl.theme.css" rel="stylesheet">
    <link href="<?= TEMPLATE_BUILDSTATE; ?>/css/owl.transitions.css" rel="stylesheet">
    <link href="<?= TEMPLATE_BUILDSTATE; ?>/css/on3step-style.css" rel="stylesheet">
    <link href="<?= TEMPLATE_BUILDSTATE; ?>/css/queries-on3step.css" media="all" rel="stylesheet" type="text/css">
</head>