      <!-- section projects -->
      <section class="whitepage no-top" id="projects" style="margin-top: 80px;">
        <div class="container">
          <div class="row">
                      
              <div class="col-md-6 col-xs-12 item int">
                <div class="projects-grid">
                  <a href="https://www.jalvesamarcadolote.com.br/alphaville">
                  <div class="hovereffect">
                    <img alt="imageportofolio" class="img-responsive" src="<?=TEMPLATE_BUILDSTATE; ?>/img/projects/img1.jpg">
                    <div class="overlay">
                      <h3>
                        CLIQUE E SAIBA MAIS
                      </h3>
                      <span class="fa fa-search" aria-hidden="true"></span>
                    </div>
                  </div></a>
                </div>
              </div>

              <div class="col-md-6 col-xs-12 item arc pers">
                <div class="projects-grid">
                  <a href="<?=TEMPLATE_BUILDSTATE; ?>/residencial-beneditto">
                  <div class="hovereffect">
                    <img alt="imageportofolio" class="img-responsive" src="<?=TEMPLATE_BUILDSTATE; ?>/img/projects/img2.jpg">
                    <div class="overlay">
                      <h3>
                        CLIQUE E SAIBA MAIS
                      </h3>
                      <span class="fa fa-search" aria-hidden="true"></span>
                    </div>
                  </div></a>
                </div>
              </div>

          </div>
        </div>
        
      </div>
      </section>
      <!-- section projects end -->