<div class="navbar navbar-default-white navbar-fixed-top">
    <div class="container">
        <div class="row">

            <!-- menu mobile display -->
            <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse">
                <span class="icon icon-bar"></span>
                <span class="icon icon-bar"></span>
                <span class="icon icon-bar"></span></button>

            <!-- logo -->
            <a class="navbar-brand white" href="<?=SITE_URL; ?>"><img alt="logo" src="<?= TEMPLATE_BUILDSTATE; ?>/img/logo-black.png"></a>

            <!-- mainmenu start -->
            <div class="white menu-init" id="main-menu">
                <nav id="menu-center">
                    <ul>
                        <li>
                            <a class="actived" href="<?=SITE_URL; ?>">Inicio</a>
                        </li>
                        <li>
                            <a href="#">Sobre</a>
                        </li>
                        <li>
                            <a href="#">Loteamentos</a>
                            <ul>
                                <li><a href="result.html">Alphaville Private Village</a></li>
                                <li><a href="result.html">Residencial Beneditto</a></li>
                            </ul>                            
                        </li>
                        <li>
                            <a href="#">Serviços</a>
                            <ul>
                                <li><a href="result.html">Topografia</a></li>
                                <li><a href="result.html">Terraplenagem</a></li>
                                <li><a href="result.html">Arquitetura</a></li>
                                <li><a href="result.html">Engenharia</a></li>
                                <li><a href="result.html">Escritura de Terreno</a></li>
                                <li><a href="result.html">Averbação de Imóveis</a></li>
                                <li><a href="result.html">Inventário</a></li>
                                <li><a href="result.html">Unificação e Retificação de Área</a></li> 
                            </ul>
                        </li>
                        <li>
                            <a href="#">Proprietário de Área</a>
                        </li>
                        <li class="btn"><a class="popup-form" href="#subwrap">Fale Conosco</a></li>
                    </ul>
                </nav>
            </div>
            <!-- mainmenu end -->

        </div>
    </div>
    <!-- container -->
</div>