<!-- plugin JS -->
<script src="<?= TEMPLATE_BUILDSTATE; ?>/plugin/jquery.js" type="text/javascript"></script>
<script src="<?= TEMPLATE_BUILDSTATE; ?>/plugin/pluginson3step.js" type="text/javascript"></script>
<!-- slider revolution  -->
<script type="<?= TEMPLATE_BUILDSTATE; ?>/text/javascript" src="rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
<!-- on3step JS -->
<script src="<?= TEMPLATE_BUILDSTATE; ?>/js/on3step.js" type="text/javascript"></script>
<script src="<?= TEMPLATE_BUILDSTATE; ?>/js/plugin-set.js" type="text/javascript"></script>