<div class="bgslider-owl" id="home">
    <div id="owl-slider-home" class="owl-carousel">

        <a href="#">
            <div class="item imgbg" style="background-image:url(<?= TEMPLATE_BUILDSTATE; ?>/img/img-slide-1.png)"></div>
        </a>
        <a href="#">
            <div class="item imgbg" style="background-image:url(<?= TEMPLATE_BUILDSTATE; ?>/img/img-slide-2.png)"></div>
        </a>

    </div>

</div>