<?php
$dadosHeader["tituloPagina"] = $tituloPagina; //Titulo da página
$dadosHeader["breadcrumb"] = $breadcrumb; //Cria os breadcrumbs da página


?>
<!DOCTYPE html>
<html lang="en">
    <head>
    <?php $this->loadView("admin/includes/headPadroes"); ?>
    </head>
    <body>
        <!--MENU-->
        <?php $this->loadView("admin/includes/menu"); ?>

        <!--breadcrumbs e titulo-->
        <?php $this->loadView("admin/includes/tituloPage", $dadosHeader); ?>

        <!--Conteúdo-->
        <section>
            <form id="cadastroForm" enctype="multipart/form-data" action="" onsubmit="return false;">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card border-light mb-3">
                          <div class="card-header">Foto</div>
                          <div class="card-body">
                            <div class="input-group mb-3">
                                <div class="col-lg-12">
                                    <div class="input-group mb-3">
                                        <?php foreach($galeria as $valor): ?>
                                        <a href="javascript:onclick=salvarCapaGaleria('<?=SITE_URL."/admin-produtos/salvar-capa-galeria/".$valor."/".$dados["id"]; ?>');">
                                            <img src="<?=STATIC_URL; ?>/img/admin/img/produtos/<?=$dados["dir_galeria"]; ?>/thumb120_<?=$valor; ?>" class="img-thumbnail img-galeria <?=($dados["capa"] == $valor) ? "img-galeria-selected" : ""; ?>">
                                        </a><br>
                                        <a href="javascript:onclick=excluirCapaGaleria('<?=SITE_URL."/admin-produtos/excluir-capa-galeria/".$dados["dir_galeria"]."/".$valor; ?>');">
                                            <span class="badge badge-danger">X</span>
                                        </a>
                                        <?php endforeach ?>                                        
                                    </div>                                    
                                </div>
                                <!--Fim Campo input-->
                                <div class="col-lg-6">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="fas fa-camera"></i>
                                            </span>
                                        </div>
                                        <input type="file" class="form-control" id="foto" name="foto" accept="image/x-png,image/gif,image/jpeg" multiple="">
                                    </div>                                    
                                </div>
                                <!--Fim Campo input-->
                                <div class="col-lg-12">
                                    <a href="javascript:onclick=excluirCapaGaleria('<?=SITE_URL."/admin-produtos/excluir-todas-fotos/".$dados["dir_galeria"]; ?>');" style="float: right; margin: 0 0 10px 0;">
                                        <span class="badge badge-danger">EXCLUIR TODAS AS FOTOS</span>
                                    </a>
                                </div>
                                <!--Fim Campo input-->                                
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
                <!--Fim Foto-->
                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card border-light mb-3">
                          <div class="card-header">Dados</div>
                          <div class="card-body">
                            <div class="input-group mb-3">
                                <div class="col-lg-2">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="fas fa-sort-numeric-up"></i>
                                            </span>
                                        </div>
                                        <input type="number" class="form-control" placeholder="Ordem" id="ordem-informacoes" name="ordem" value="<?=$dados["ordem"]; ?>">
                                    </div>
                                </div>                                
                                <!--Fim Campo input-->                                     
                                <div class="col-lg-10">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="fas fa-text-width"></i>
                                            </span>
                                        </div>
                                        <input type="text" class="form-control" placeholder="Título" id="titulo" name="titulo" value="<?=$dados["titulo"]; ?>">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="fas fa-text-width"></i>
                                            </span>
                                        </div>
                                        <input type="text" class="form-control" placeholder="Texto Curto" id="texto_curto" name="texto_curto" value="<?=$dados["texto_curto"]; ?>">
                                    </div>
                                </div>

                                <div class="col-lg-12">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="fas fa-text-width"></i>
                                            </span>
                                        </div>
                                        <textarea class="form-control" placeholder="Texto" id="texto" name="texto"><?=$dados["texto"]; ?></textarea>
                                    </div>
                                </div>

                                <!--Fim Campo input-->
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card border-light mb-3">
                          <div class="card-header">Categoria do Produto</div>
                          <div class="card-body">
                            <div class="input-group mb-3">
                                <div class="col-lg-6">
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text">
                                                <i class="far fa-eye"></i>
                                            </span>
                                        </div>
                                        <select name="categoria_id" class="custom-select" id="perfil">
                                            <option value="0">NENHUMA CATEGORIA</option>
                                            <?php foreach($categoria as $valor):?>
                                            <option value="<?=$valor["id"]; ?>" <?=($dados["categoria_id"] == $valor["id"]) ? "selected" : ""; ?>><?=$valor["categoria"]; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                                <!--Fim Campo input-->
                            </div>
                          </div>
                        </div>
                    </div>
                </div>                
                
                
                <div class="row">
                    <div class="col-lg-12">
                        <button type="button" class="btn btn-primary float-right" id="bt-salvar" onclick="formSubmitImage('#cadastroForm','<?=$urlAction; ?>');">
                            Salvar <i class="fas fa-check"></i>
                        </button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div id="resposta-form" class="float-right">
                            <!--Resposta do Server-->
                        </div>
                    </div>
                </div>
            </div>
            </form>
        </section>

        <!--RODAPÉ E SCRIPTS PADRÕES-->
        <?php $this->loadView("admin/includes/footerScripts"); ?>
    </body>
</html>
