<?php
$dadosHeader["tituloPagina"] = $tituloPagina; //Titulo da página
$dadosHeader["breadcrumb"] = $breadcrumb; //Cria os breadcrumbs da página
$tableActive = 1; //Criar cores linhas tabela

?>

<!DOCTYPE html>
<html lang="en">
    <head>
    <?php $this->loadView("admin/includes/headPadroes"); ?>
    </head>
    <body>
        <!--MENU-->
        <?php $this->loadView("admin/includes/menu"); ?>

        <!--breadcrumbs e titulo-->
        <?php $this->loadView("admin/includes/tituloPage", $dadosHeader); ?>

        <!--Conteúdo-->
        <section>
            <div class="container">
                <div class="row cadastrar-topo">
                    <div class="col-lg-8">
                        <div class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="text" placeholder="Digite Algo..." id="inputBusca" value="<?=$busca; ?>" onkeydown="redirEnter('<?=$urlAction; ?>/'+$('#inputBusca').val(),'#inputBusca')">
                            <button class="btn btn-secondary my-2 my-sm-0" onclick="javascript:redir('<?=$urlAction; ?>/'+$('#inputBusca').val());">
                                Pesquisar <i class="fas fa-search"></i>
                            </button>
                            <?php if(!empty($busca)): ?>
                            <button type="button" class="btn btn-link" style="color: red;" onclick="javascript:redir('<?=$urlAction; ?>');">
                                Limpar Busca X
                            </button>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <?php if($permissaoCadastro): ?>
                        <a href="<?=$actionCadastrar; ?>">
                            <button type="button" class="btn btn-success float-right">Novo <i class="fas fa-plus-circle"></i></button>
                        </a>
                        <?php endif;?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <table class="table table-hover">
                            <thead>
                                <tr class="table-primary">
                                    <th scope="col">Ordem</th>
                                    <th scope="col">Capa</th>
                                    <th scope="col">Título</th>
                                    <th scope="col">Texto Curto</th>
                                    <th scope="col">Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($lista as $indice => $valor): ?>
                                <?php $tableActive++; ?>
                                <tr class="<?=($tableActive%2) ? "table-active" : ""; ?>" id="row-<?=$valor["id"]; ?>">
                                    <td><?=$valor["ordem"];?></td>
                                    <?php if(is_file(STATIC_PATH."/img/admin/img/produtos/".$valor["dir_galeria"]."/thumb25_".$valor["capa"]) ): ?>
                                    <td><img src="<?=STATIC_URL; ?>/img/admin/img/produtos/<?=$valor["dir_galeria"]; ?>/thumb25_<?=$valor["capa"]; ?>"></td>
                                    <?php else: ?>
                                    <td><i class="fas fa-user-alt-slash"></i></td>
                                    <?php endif; ?>
                                    <td><?=$valor["titulo"];?></td>
                                    <td><?=$valor["texto_curto"];?></td>
                                    <td>
                                        <div class="ativo" id="caixa-acao-<?=$valor["id"];?>">
                                            <?php if($permissaoEditar): ?>
                                            <a href="<?=SITE_URL?>/admin-produtos/editar/<?=$valor["id"];?>">
                                                <i class="fas fa-edit" title="Editar"></i>
                                            </a>
                                            <?php endif; ?>
                                            <?php if($permissaoExcluir): ?>
                                            <a href="javascript:onclick=exibirConfirma(<?=$valor["id"]; ?>);">
                                                <i class="fas fa-trash-alt text-danger" title="Excluir"></i>
                                            </a>
                                            <?php endif; ?>
                                        </div>
                                        <div class="inativo" id="caixa-confirma-<?=$valor["id"];?>">
                                            <a href="javascript:onclick=removerRegistro('<?=SITE_URL;?>/admin-produtos/remover/<?=$valor["id"]; ?>','#row-<?=$valor["id"]; ?>');"><span class="badge badge-danger">Excluir</span></a>
                                            <a href="javascript:onclick=exibirAcao(<?=$valor["id"]; ?>);"><span class="badge badge-light">Cancelar</span></a>
                                        </div>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                                <?php if(count($lista) == 0): ?>
                                <tr>
                                    <td colspan="5" class="text-center table-active">
                                        Nenhum resultado encontrado!
                                    </td>
                                </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-3">
                        <div class="centralizado">
                            <label>Total de registros <span class="totalRegistros"><?=$totalRows; ?></span></label>
                            <?php if(count($pageView) > 1): ?>
                            <select class="custom-select" id="" onchange="redir(this.value);">
                              <?php foreach($pageView as $indice => $valor): ?>  
                                <option value="<?=$valor["url"]; ?>" <?=$valor["active"]; ?>>
                                    Página <?=$valor["page_number"]; ?>
                                </option>
                              <?php endforeach; ?>
                            </select>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>             
            </div>
        </section>

        <!--RODAPÉ E SCRIPTS PADRÕES-->
        <?php $this->loadView("admin/includes/footerScripts"); ?>
    </body>
</html>
