<?php
$dados["notificacoes"] = $notificacoes;
$dados["totalNotificacoesNaoLidas"] = $totalNotificacoesNaoLidas;
?>
<!doctype html>
<html lang="pt-br">
<!--HEAD + CSS-->
<?= $this->loadview('admin/includes/head'); ?>

<!-- DataTables -->
<link href="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
<link href="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/fixedHeader.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
<link href="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/scroller.bootstrap4.min.css" rel="stylesheet" type="text/css" />

<body>
    <!--TOPO + MENU-->
    <?= $this->loadview('admin/includes/header', $dados); ?>

    <!--CONTEÚDO-->
    <div class="wrapper">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-sm">

                                <ol class="breadcrumb">
                                    <?php foreach ($breadcrumb as $indice => $valor) : ?>
                                        <?php if (!empty($valor["url"])) : ?>
                                            <li class="breadcrumb-item"><a href="<?= $valor["url"]; ?>"><?= $valor["nome"]; ?></a></li>
                                        <?php else : ?>
                                            <li class="breadcrumb-item active"><a><?= $valor["nome"]; ?></a></li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ol>

                            </div>
                            <?php if ($cadastrar) : ?>
                                <div class="col-sm bloco-botao-cadastro">
                                    <a href="<?= $breadcrumb[0]["url"] ?>/cadastrar" class="btn-success botao-lista botao-lista botao-efeito">
                                        <i class="mdi mdi-gamepad-round"></i> NOVO CADASTRO
                                    </a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; width: 100%;">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Título</th>
                                        <th>Ativo</th>
                                        <th>Destaque</th>
                                        <th></th>
                                    </tr>
                                </thead>

                                <tbody>
                                    <?php foreach ($listagem as $indice => $valor) : ?>
                                        <tr>
                                            <td><?= $valor["id"]; ?></td>
                                            <td><?= Common::reduzirTexto($valor["titulo"]); ?></td>
                                            <td>
                                                <div class="radio radio-info form-check-inline" style="margin-left: 10px;">
                                                    <input type="radio" id="ativo-s-<?= $valor["id"] ?>" value="<?= $valor["id"]; ?>" name="ativo-<?= $valor["id"] ?>" <?= ($valor["ativo"] == "S") ? "checked=''" : ""; ?> onchange="ativarRegistro('<?= SITE_URL; ?>/paginas-extras/ativar-registro/<?= $valor['id']; ?>');">
                                                    <label for="ativo-s-<?= $valor["id"] ?>">Sim </label>
                                                </div>
                                                <div class="radio radio-info form-check-inline">
                                                    <input type="radio" id="ativo-n-<?= $valor["id"] ?>" value="<?= $valor["id"]; ?>" name="ativo-<?= $valor["id"] ?>" <?= ($valor["ativo"] == "N") ? "checked=''" : ""; ?> onchange="ativarRegistro('<?= SITE_URL; ?>/paginas-extras/ativar-registro/<?= $valor['id']; ?>');">
                                                    <label for="ativo-n-<?= $valor["id"] ?>">Não</label>
                                                </div>
                                            </td>
                                            <td>
                                                <div class="radio radio-info form-check-inline" style="margin-left: 10px;">
                                                    <input type="radio" id="destaque-s-<?= $valor["id"] ?>" value="<?= $valor["id"]; ?>" name="destaque-<?= $valor["id"] ?>" <?= ($valor["destaque"] == "S") ? "checked=''" : ""; ?> onchange="ativarRegistro('<?= SITE_URL; ?>/paginas-extras/ativar-registro/<?= $valor['id']; ?>/destaque');">
                                                    <label for="destaque-s-<?= $valor["id"] ?>">Sim </label>
                                                </div>
                                                <div class="radio radio-info form-check-inline">
                                                    <input type="radio" id="destaque-n-<?= $valor["id"] ?>" value="<?= $valor["id"]; ?>" name="destaque-<?= $valor["id"] ?>" <?= ($valor["destaque"] == "N") ? "checked=''" : ""; ?> onchange="ativarRegistro('<?= SITE_URL; ?>/paginas-extras/ativar-registro/<?= $valor['id']; ?>/destaque');">
                                                    <label for="destaque-n-<?= $valor["id"] ?>">Não</label>
                                                </div>
                                            </td>                                            
                                            <td>
                                                <a href="javascript:onclick=abrirModalDocumento('<?= SITE_URL; ?>/paginas-extras/ler-documento-modal/<?= $valor['id']; ?>','<?= $valor['id']; ?>');" class="botao-lista" data-toggle="tooltip" title="Olhar dados">
                                                    <i class="mdi mdi-eye"></i>
                                                </a>
                                                <?php if ($editar) : ?>
                                                    <a href="<?= SITE_URL; ?>/paginas-extras/editar/<?= $valor['id']; ?>" class="botao-lista" data-toggle="tooltip" title="Editar dados">
                                                        <i class="mdi mdi-lead-pencil"></i>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($excluir) : ?>
                                                    <a href="javascript:onclick=removerRegistro('<?= SITE_URL; ?>/paginas-extras/remover/<?= $valor['id']; ?>','<?= $indice; ?>');" class="botao-lista" data-toggle="tooltip" title="Excluir dados">
                                                        <i class="mdi mdi-close"></i>
                                                    </a>
                                                <?php endif; ?>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div> <!-- End Row -->



        </div>
    </div>
    <!--CONTEÚDO-->

    <!--MODAL-->
    <div class="modal fade olhar" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true" id="modal-documento">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title m-0" id="titulo-modal"> AQUI TO TITULO </h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-12" id="documento-modal">
                            AQUI O CONTEUDO
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12" id="galeria-modal">
                            AQUI A GALERIA
                        </div>
                    </div>                    
                </div>
                <div class="modal-footer">
                    <?php if ($editar) : ?>
                        <a href="<?= SITE_URL; ?>/paginas-extras/editar/" class="botao-lista" data-toggle="tooltip" title="Editar dados" id="href-modal">
                            <button type="button" class="btn btn-sistema">
                                <i class="mdi mdi-lead-pencil"></i> Editar
                            </button>
                        </a>
                    <?php endif; ?>
                    <button type="button" class="btn btn-sistema-fechar" data-dismiss="modal">
                        <i class="mdi mdi-close"></i> Fechar
                    </button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->    


    <!--FOOTER-->
    <?= $this->loadview('admin/includes/footer'); ?>

    <!--JAVSCRIPT-->
    <?= $this->loadview('admin/includes/scripts'); ?>

    <!-- Required datatable js-->
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Buttons examples -->
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/dataTables.buttons.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/buttons.bootstrap4.min.js"></script>

    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/jszip.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/pdfmake.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/vfs_fonts.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/buttons.html5.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/buttons.print.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/dataTables.fixedHeader.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/dataTables.keyTable.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/dataTables.scroller.min.js"></script>

    <!-- Responsive examples -->
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/dataTables.responsive.min.js"></script>
    <script src="<?= TEMPLATE_HEXZY; ?>/plugins/datatables/responsive.bootstrap4.min.js"></script>

    <!-- Datatable init js -->
    <script src="<?= TEMPLATE_HEXZY; ?>/pages/datatables.init.js"></script>
    <script>

    </script>
</body>

</html>