<?php if(count($banners) >= 1 ): ?>
<div id="theme-main-banner" class="banner-two">
    <?php foreach($banners as $valor): ?>
    <div data-src="<?= Common::getImg("banner/{$valor['dir_galeria']}/thumb1920_{$valor['capa']}"); ?>">
        <div class="camera_caption">
            <div class="container">
                <p class="wow fadeInUp animated"><?=$valor["pequeno_texto"]; ?></p>
                <h1 class="wow fadeInUp animated" data-wow-delay="0.2s"><?=$valor["grande_texto"]; ?></h1>
                <?php if(!empty($valor["url"])): ?>
                <a href="<?=$valor["url"]; ?>" class="theme-button-one wow fadeInUp animated" data-wow-delay="0.39s">SAIBA MAIS</a>
                <?php endif; ?>
            </div> <!-- /.container -->
        </div> <!-- /.camera_caption -->
    </div>
    <?php endforeach; ?>
    <?php if(count($banners) == 1): ?>
        <?php foreach($banners as $valor): ?>
        <div data-src="<?= Common::getImg("banner/{$valor['dir_galeria']}/thumb1920_{$valor['capa']}"); ?>">
        <div class="camera_caption">
            <div class="container">
                <p class="wow fadeInUp animated"><?=$valor["pequeno_texto"]; ?></p>
                <h1 class="wow fadeInUp animated" data-wow-delay="0.2s"><?=$valor["grande_texto"]; ?></h1>
                <?php if(!empty($valor["url"])): ?>
                <a href="<?=$valor["url"]; ?>" class="theme-button-one wow fadeInUp animated" data-wow-delay="0.39s">SAIBA MAIS</a>
                <?php endif; ?>
            </div> <!-- /.container -->
        </div> <!-- /.camera_caption -->
    </div>
    <?php break; ?>
    <?php endforeach; ?>        
    <?php endif; ?>
</div> <!-- /#theme-main-banner -->
<?php endif; ?>