<div id="theme-main-banner" class="banner-one">
    <div data-src="<?= TEMPLATE_CHARLES; ?>/images/home/banner-1.jpg">
        <div class="camera_caption">
            <div class="container">
                <p class="wow fadeInUp animated">Sua empresa 100% Conectada</p>
                <h1 class="wow fadeInUp animated" data-wow-delay="0.2s">Websites profissionais <br>de impacto</h1>
                <a href="#" class="theme-button-one wow fadeInUp animated" data-wow-delay="0.39s">SAIBA MAIS</a>
            </div> <!-- /.container -->
        </div> <!-- /.camera_caption -->
    </div>
    <div data-src="<?= TEMPLATE_CHARLES; ?>/images/home/slide-5.jpg">
        <div class="camera_caption">
            <div class="container">
                <p class="wow fadeInUp animated">Pequeno texto explicativo</p>
                <h1 class="wow fadeInUp animated" data-wow-delay="0.2s">FRASE DE IMPACTO</h1>
                <a href="#" class="theme-button-one wow fadeInUp animated" data-wow-delay="0.39s">SAIBA MAIS</a>
            </div> <!-- /.container -->
        </div> <!-- /.camera_caption -->
    </div>
</div> <!-- /#theme-main-banner -->