<div class="col-xl-3 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar">
    <div class="sidebar-container sidebar-search">
        <form action="#">
            <input type="text" placeholder="Procure no blog">
            <button><i class="fa fa-search" aria-hidden="true"></i></button>
        </form>
    </div> <!-- /.sidebar-search -->
    <div class="sidebar-container sidebar-categories">
        <h5 class="title">Categorias</h5>
        <ul>
            <li><a href="#">Tecnologia</a></li>
            <li><a href="#">Novidades da empresa</a></li>
            <li><a href="#">Dicas sobre sites</a></li>
            <li><a href="#">Novidades da cidade</a></li>
        </ul>
    </div> <!-- /.sidebar-categories -->

    <div class="sidebar-container sidebar-archives">
        <h5 class="title">Archives</h5>
        <ul>
            <li><a href="#">Janeiro 2022</a></li>
            <li><a href="#">Fevereiro 2022</a></li>
            <li><a href="#">Março 2022</a></li>
            <li><a href="#">Abril 2022</a></li>
        </ul>
    </div> <!-- /.sidebar-archives -->
    <div class="sidebar-tags">
        <h5 class="title">tags</h5>
        <ul class="clearfix">
            <li><a href="#">Negócios</a></li>
            <li><a href="#">Consultoria</a></li>
            <li><a href="#">Vendas</a></li>
            <li><a href="#">Startup</a></li>
            <li class="active"><a href="#">Marketing</a></li>
            <li><a href="#">Serviços</a></li>
            <li><a href="#">Resenhas</a></li>
            <li><a href="#">Vidaloka</a></li>
        </ul>
    </div> <!-- /.sidebar-tags -->

    <div class="view-all" style="margin-top: 20px;">
            <a href="<?=SITE_URL;?>/blog" class="theme-button-one">Matérias do BLOG</a>
    </div>

</div> <!-- /.col- -->