<div class="faq-section">
    <div class="overlay">
        <div class="container">
            <div class="theme-title-one">
                <h2>dúvidas</h2>
                <p>Abaixo as principais dúvidas dos nossos clientes, solucionadas para você;</p>
            </div> <!-- /.theme-title-one -->

            <div class="wrapper row no-gutters">
                <div class="col-xl-6 col-lg-7 order-last">
                    <div class="faq-content">
                        <div class="accordion-one">
                            <div class="panel-group theme-accordion" id="accordion">
                                <div class="panel">
                                    <div class="panel-heading">
                                        <h6 class="panel-title">
                                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
                                                1. What industries do you specialize in?</a>
                                        </h6>
                                    </div>
                                    <div id="collapse1" class="panel-collapse collapse">
                                        <div class="panel-body">
                                            <p>A tale of a fateful trip that started from this tropic port aboard this tiny ship today still wanted by the government they survive as soldiers of fortune to a deluxe you apartment.</p>
                                        </div>
                                    </div>
                                </div> <!-- /panel 1 -->
                                <div class="panel">
                                    <div class="panel-heading active-panel">
                                        <h6 class="panel-title">
                                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">
                                                2. You guarantee that our plan will raise capital?</a>
                                        </h6>
                                    </div>
                                    <div id="collapse2" class="panel-collapse collapse show">
                                        <div class="panel-body">
                                            <p>A tale of a fateful trip that started from this tropic port aboard this tiny ship today still wanted by the government they survive as soldiers of fortune to a deluxe you apartment.</p>
                                        </div>
                                    </div>
                                </div> <!-- /panel 2 -->
                                <div class="panel">
                                    <div class="panel-heading">
                                        <h6 class="panel-title">
                                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">
                                                3. Do you ever invest in your clients?</a>
                                        </h6>
                                    </div>
                                    <div id="collapse3" class="panel-collapse collapse">
                                        <div class="panel-body">
                                            <p>A tale of a fateful trip that started from this tropic port aboard this tiny ship today still wanted by the government they survive as soldiers of fortune to a deluxe you apartment.</p>
                                        </div>
                                    </div>
                                </div> <!-- /panel 3 -->
                                <div class="panel">
                                    <div class="panel-heading">
                                        <h6 class="panel-title">
                                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse4">
                                                4. What makes your financial projections special?</a>
                                        </h6>
                                    </div>
                                    <div id="collapse4" class="panel-collapse collapse">
                                        <div class="panel-body">
                                            <p>A tale of a fateful trip that started from this tropic port aboard this tiny ship today still wanted by the government they survive as soldiers of fortune to a deluxe you apartment.</p>
                                        </div>
                                    </div>
                                </div> <!-- /panel 4 -->
                                <div class="panel">
                                    <div class="panel-heading">
                                        <h6 class="panel-title">
                                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse5">
                                                5. Will you agree with everything I say?</a>
                                        </h6>
                                    </div>
                                    <div id="collapse5" class="panel-collapse collapse">
                                        <div class="panel-body">
                                            <p>A tale of a fateful trip that started from this tropic port aboard this tiny ship today still wanted by the government they survive as soldiers of fortune to a deluxe you apartment.</p>
                                        </div>
                                    </div>
                                </div> <!-- /panel 5 -->
                            </div> <!-- end #accordion -->
                        </div> <!-- End of .accordion-one -->
                    </div> <!-- /.faq-content -->
                </div> <!-- /.col- -->
                <div class="col-lg-6 col-12 order-lg-first">
                    <div class="img-box">
                        <a data-fancybox href="https://www.youtube.com/embed/r-AuLm7S3XE?rel=0&amshowinfo=0">
                            <img src="<?= TEMPLATE_CHARLES; ?>/images/home/16.jpg">
                        </a>
                    </div>
                </div>
            </div> <!-- /.wrapper -->
        </div> <!-- /.container -->
    </div> <!-- /.overlay -->
</div> <!-- /.faq-section -->

<div class="our-case section-spacing">
    <div class="container">
        <div class="view-all">
            <a href="<?=SITE_URL;?>/duvidas" class="theme-button-one">Todas as dúvidas</a>
        </div>
    </div>
</div>