<footer class="theme-footer-one theme-footer-two">
    <div class="top-footer">
        <div class="container">
            <div class="row">
                <div class="<?= (count($paginasExtras) >= 1) ? "col-lg-4" : ""; ?> col-sm-6 col-12 logo-widget">
                    <h6 style="margin: 20px 0 10px 0;">Nos sigam nas redes sociais</h6>
                    <p style="margin: 0 0 20px 0;"></p>
                    <ul class="social-icon">
                        <?php if (!empty($config["facebook"])) : ?>
                            <li><a href="<?= $config["facebook"]; ?>" target="_blank"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>
                        <?php endif; ?>
                        <?php if (!empty($config["instagram"])) : ?>
                            <li><a href="<?= $config["instagram"]; ?>" target="_blank"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
                        <?php endif; ?>
                        <?php if (!empty($config["linkedin"])) : ?>
                            <li><a href="<?= $config["linkedin"]; ?>" target="_blank"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
                        <?php endif; ?>
                        <?php if (!empty($config["youtube"])) : ?>
                            <li><a href="<?= $config["youtube"]; ?>" target="_blank"><i class="fab fa-youtube" aria-hidden="true"></i></a></li>
                        <?php endif; ?>
                        <?php if (!empty($config["twitter"])) : ?>
                            <li><a href="<?= $config["twitter"]; ?>" target="_blank"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
                        <?php endif; ?>
                    </ul>
                </div> <!-- /.logo-widget -->

                <div class="col-lg-2 col-sm-6 col-12 footer-list">
                    <h6 class="title">NAVEGAÇÃO EXTRA</h6>
                    <ul>
                        <?php foreach ($menuFooter as $valor) : ?>
                            <?php if (empty($valor["pseudo_titulo"])) : ?>
                                <li><a href="<?= SITE_URL . "/" . Common::slug($valor["titulo"]); ?>"><?= $valor["titulo"]; ?></a></li>
                            <?php else : ?>
                                <li><a href="<?= SITE_URL . "/" . Common::slug($valor["pseudo_titulo"]); ?>"><?= $valor["pseudo_titulo"]; ?></a></li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                </div> <!-- /.footer-list -->

                <?php if (count($paginasExtras) >= 1) : ?>
                    <div class="col-lg-3 col-sm-6 col-12 footer-list">
                        <h6 class="title">
                            <a href="<?= SITE_URL; ?>/pagina" style="color: <?= $config["cor_terciaria"]; ?>;">
                                PÁGINAS EXTRAS
                            </a>
                        </h6>
                        <ul>
                            <?php foreach ($paginasExtras as $valor) : ?>
                                <li>
                                    <a href="<?= SITE_URL; ?>/<?= Common::slug($valor["titulo"]); ?>" style="line-height: 20px;">
                                        <?= $valor["titulo"]; ?>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div> <!-- /.footer-list -->
                <?php endif; ?>

                <div class="col-lg-3 col-sm-6 col-12 contact-widget">
                    <h6 class="title">CONTATO</h6>
                    <ul>
                        <li>
                            <i class="flaticon-direction-signs"></i>
                            <?= $config["endereco"]; ?>
                        </li>
                        <li>
                            <i class="flaticon-multimedia-1"></i>
                            <a href="mailto:<?= $config["email"]; ?>"><?= $config["email"]; ?></a>
                        </li>
                        <li>
                            <i class="fa fa-phone" aria-hidden="true"></i>
                            <a href="tel:<?= $config["telefone"]; ?>"><?= $config["telefone"]; ?></a>
                        </li>
                    </ul>
                </div> <!-- /.contact-widget -->
            </div> <!-- /.row -->
        </div> <!-- /.container -->
    </div> <!-- /.top-footer -->
    <div class="bottom-footer">
        <div class="container">
            <span class="texto-publicidade-footer"><?= $config["texto_rodape"]; ?></span>
            <a href="<?= SITE_URL; ?>/admin" style="margin-left: 30px;" target="_blank">
                <span class="badge badge-secondary">Admin</span>
            </a>
        </div>
    </div> <!-- /.bottom-footer -->
</footer> <!-- /.theme-footer-two -->

<div id="hi-whatsapp" onclick="location.href='<?= Common::linkWhatsapp($config['telefone']); ?>'">
    <i class="fab fa-whatsapp"></i>
</div>
<?=$config["pixel"]; ?>