<footer class="theme-footer-one theme-footer-two">
    <div class="top-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-sm-6 col-12 logo-widget">
                    <div class="logo" style="text-align: center;">
                        <a href="<?=SITE_URL; ?>">
                            <img src="<?= TEMPLATE_CHARLES; ?>/images/logo/logo2.png">
                        </a>
                    </div>
                    <p>Tudo o que um sonho precisa para ser realizado é alguém que acredite que ele possa ser realizado.</p>
                    <ul class="social-icon">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                    </ul>
                </div> <!-- /.logo-widget -->

                <div class="col-lg-2 col-sm-6 col-12 footer-list">
                    <h6 class="title">NAVEGAÇÃO EXTRA</h6>
                    <ul>
                        <li><a href="<?=SITE_URL; ?>/equipe">Equipe</a></li>
                        <li><a href="<?=SITE_URL; ?>/blog">Blog</a></li>
                        <li><a href="<?=SITE_URL; ?>/projetos">Projetos</a></li>                        
                        <li><a href="<?=SITE_URL; ?>/duvidas">Dúvidas</a></li>
                        <li><a href="<?=SITE_URL; ?>/contato">Contato</a></li>
                    </ul>
                </div> <!-- /.footer-list -->


                <div class="col-lg-3 col-sm-6 col-12 footer-list">
                    <h6 class="title">PÁGINAS EXTRAS</h6>
                    <ul>
                        <li><a href="<?=SITE_URL; ?>/pagina/detalhes/politica-e-privacidade">Política e Privacidade</a></li>
                        <li><a href="<?=SITE_URL; ?>/pagina/detalhes/termos-de-uso">Termos de Uso</a></li>
                    </ul>
                </div> <!-- /.footer-list -->

                <div class="col-lg-3 col-sm-6 col-12 contact-widget">
                    <h6 class="title">CONTATO</h6>
                    <ul>
                        <li>
                            <i class="flaticon-direction-signs"></i>
                            Santa Catarina, Brasil
                        </li>
                        <li>
                            <i class="flaticon-multimedia-1"></i>
                            <a href="#">contato@querosite.com.br</a>
                        </li>
                        <li>
                            <i class="fa fa-phone" aria-hidden="true"></i>
                            <a href="#">(00) 0000-0000</a>
                        </li>
                    </ul>
                </div> <!-- /.contact-widget -->
            </div> <!-- /.row -->
        </div> <!-- /.container -->
    </div> <!-- /.top-footer -->
    <div class="bottom-footer">
        <div class="container">
            <a href="<?=SITE_DESENVOLVEDORA;?>">
                <p class="texto-publicidade-footer">Desenvolvido por querosite.digital <?=date("Y");?></p>
            </a>
        </div>
    </div> <!-- /.bottom-footer -->
</footer> <!-- /.theme-footer-two -->

<div id="hi-whatsapp" onclick="location.href='https://api.whatsapp.com/send?phone=554700000000&amp;text=Mensagem enviada pelo site. produto da empresa www.querosite.digital'">
    <i class="fa fa-whatsapp"></i>
</div>