<head>
		<meta charset="UTF-8">
		<!-- For IE -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<!-- For Resposive Device -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- For Window Tab Color -->
		<!-- Chrome, Firefox OS and Opera -->
		<meta name="theme-color" content="#fd7e14">
		<!-- Windows Phone -->
		<meta name="msapplication-navbutton-color" content="#fd7e14">
		<!-- iOS Safari -->
		<meta name="apple-mobile-web-app-status-bar-style" content="#fd7e14">
		<title>Sites Profissionais, Soluções Digitais, Websites, Hospedagem e muito mais - Querosite.digital</title>
		<!-- Favicon -->
		<link rel="icon" type="image/png" sizes="56x56" href="<?=TEMPLATE_CHARLES; ?>/images/fav-icon/icon.png">
		<!-- Main style sheet -->
		<link rel="stylesheet" type="text/css" href="<?=TEMPLATE_CHARLES; ?>/css/style.css">
		<!-- responsive style sheet -->
		<link rel="stylesheet" type="text/css" href="<?=TEMPLATE_CHARLES; ?>/css/responsive.css">

		<!-- Fix Internet Explorer ______________________________________-->
		<!--[if lt IE 9]>
			<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
			<script src="vendor/html5shiv.js"></script>
			<script src="vendor/respond.js"></script>
		<![endif]-->

	<style>
		
		/**--------------------- CORES DO SITE --------------------------*/
		/**Topo */
		.top-header{
			background: #008dd7 !important;
		}
		/** Cores ícones sociais topo*/
		.top-header .social-icon li a{
			color: #fff !important;
		}
		/**Slogan topo */
		.top-header .left-widget li{
			color: #fff !important;
		}
		/**Texto publicidade footer */
		.texto-publicidade-footer, .texto-publicidade-footer a{
			color:#ccc !important;
			font-size: 14px !important;
		}
		.texto-publicidade-footer a:hover{
			text-decoration: underline;
		}
		/**corpo do site */
		body{
			background-color: #fff !important;
			color: #000 !important;
		}
		/**Titulos banner home */
		.camera_caption h1{
			color: #fff !important;
		}
		/**Subtitulo banner home */
		#theme-main-banner .camera_caption p{
			color: #fff !important;
		}

		/**Menu */
		.header-two #mega-menu-holder>ul> li> a, .header-two #mega-menu-holder li .sub-toggle, .header-two #mega-menu-holder>ul> li> a:before{
			color: #000 !important;
		}
		/**Cor de fundo submenu */
		#mega-menu-holder ul.dropdown li a:before{
			background-color: #008dd7 !important;
			color: #000 !important;
		}
		/**busca Menu */
		.header-two .theme-menu-wrapper .right-widget .search-option .dropdown-toggle{
			color: #000 !important;
		}
		/**botão da busca MENU */
		.theme-menu-wrapper .right-widget .search-option form button{
			background-color: #008dd7 !important;
			color: #fff !important;
		}

		/**Botões de ação */
		.theme-button-one{
			background-color: #008dd7 !important;
			color: #fff !important;
		}
		.theme-button-one:hover{
			background-color: #0079b8 !important;
			color: #fff !important;
		}

		/**Informação abaixo do banner da home */
		.callout-banner{
			background-color: #0079b8 !important;
		}
		.callout-banner h3{
			color: #fff !important;
		}
		.callout-banner p{
			color: #fff !important;
		}

		/**Fundo Caixa empresa Home Destaque */
		.about-compnay-two .overlay{
			background-color: #008dd7 !important;
		}
		/**Titulo Fundo Caixa empresa home destaque */
		.about-compnay-two h2{
			color: #fff !important;
		}
		.about-compnay-two .text p{
			color: #fff !important;
		}
		.about-compnay-two button{
			background-color: #0079b8 !important;
		}

		/**Menu categoria produto/serviço selecionada */
		.theme-sidebar-one .service-categories ul li a:hover, .theme-sidebar-one .service-categories ul li.active a{
			background-color: #bbbbbb !important;
			border-color: #8e8e8e !important;
			color: #1a1a1a !important;
		}

		/**card produto/serviço cor transparencia frente */
		.our-case .single-case-block .hover-content{
			background-color: #daf2ff99 !important;
		}

		/**Botão de ação para single card produto/serviço */
		.our-case .single-case-block .hover-content .text .details{
			background-color: #fff !important;
		}
		.our-case .single-case-block .hover-content .text .details:hover{
			background-color: #008dd7 !important;
		}

		/**FAQ */
		.faq-section .overlay{
			background-color: #008dd7 !important;
		}
		.faq-section .overlay h2{
			color: #fff !important;
		}		
		.faq-section .theme-title-one p{
			color: #fff !important;
		}
		
		/**Cor data ultimas noticias */
		.date{
			background-color: #008dd7 !important;
			color: #fff !important;
		}
		/**Titulo ultimas noticias */
		.title{
			color: #000 !important;
		}
		/**Link saiba mais ultimas noticias */
		.read-more{
			color: #008dd7 !important;
		}

		/**BANNER CURTO */
		.short-banner{
			background-color: #008dd7 !important;
		}
		.short-banner h2{
			color: #fff !important;
		}

		/**FOOTER */
		.theme-footer-two, .top-footer{
			background-color: #0079b8 !important;
		}
		.theme-footer-two, .top-footer p{
			color: #fff !important;
		}
		.theme-footer-two .logo-widget .social-icon li a{
			color: #fff !important;
		}
		.theme-footer-one .top-footer .title{
			color: #fff !important;
		}
		.theme-footer-one .top-footer .footer-list ul li a{
			color: #fff !important;
		}
		.theme-footer-two .top-footer .footer-list ul li:before{
			color: #fff !important;
		}
		.date-footer{
			color: #fff !important;
			font-size: 14px !important;
		}
		.theme-footer-two .top-footer .contact-widget ul li{
			color: #fff !important;
		}
		.theme-footer-two .top-footer .contact-widget ul li a{
			color: #fff !important;
		}
		.theme-footer-one .bottom-footer{
			background-color: #005d8e !important;
		}
		.texto-publicidade-footer, .texto-publicidade-footer a{
			color: #fff !important;
		}


		/**------------------EMPRESA------------------*/

		/**Informação abaixo do banner da home */
		.callout-banner-institucional{
			background-color: #fff !important;
		}
		.callout-banner-institucional h3{
			color: #000 !important;
		}
		.callout-banner-institucional p{
			color: #404040 !important;
		}
		
		/**Fundo bloco missão visao valores */
		.why-we-best .overlay{
			background-color: #008dd7 !important;
		}
		.titulo-missao{
			color: #fff !important;
		}

		/**Cores do icones */
		.why-we-best .wrapper .best-list-item li .icon{
			color: #008dd7 !important;
		}
		/**Cores do texto */
		.cor-m-v-v{
			color: #000 !important;
		}
		/**Números final página */
		.single-counter-box .number{
			color: #008dd7 !important;
		}


		/**----------------EQUIPE--------------------------------- */

		/**Fundo box equipe*/
		.our-team .team-member .overlay{
			background-color: #008dd7 !important;
		}
		.our-team .team-member .overlay .hover-content p{
			color: #fff !important;
		}


		/**------------------DETALHES DE PRODUTOS OU SERVIÇOS------------ */
		.botao-pagamento{
			background-color: #20c218 !important;
		}
		.botao-pagamento:hover{
			background-color: #34d32c !important;
		}


		/**----------------GERAL DO SITE-------------------------- */

		/**Subtitulos site */
		h2,h3,h4,h5{
			color: #008dd7 !important;
		}

		/**URL de titulos */
		h5 a{
			color: #000 !important;
		}

		/**Textos do site */		
		p{
			color: #000 !important;
		}

		/**Titulo páginas internas */
		.theme-inner-banner{
			background-color: #008dd7 !important;
		}
		.theme-inner-banner h1{
			color: #fff !important;
			font-size: 40px !important;
			line-height: 40px !important;
			font-weight: 900 !important;
			text-transform: uppercase !important;
		}

		/**-----------RESPONSIVO------------------- */

		/**Titulo interno páginas */
		@media (max-width: 991px) {
			.theme-inner-banner h1{
				font-size: 30px !important;
			}
			.header-two .theme-menu-wrapper .bg-wrapper{
				padding: 12px 0;
			}	
		}
		


	</style>

</head>