<header class="header-two">

    
    <?php if($config["site_construcao"] != "S"): ?>
    <div class="theme-menu-wrapper">
        <div class="container">
            <div class="bg-wrapper clearfix">
                <div class="logo float-left">
                    <a href="<?=SITE_URL;?>">
                        <img src="<?= STATIC_URL; ?>/img/sistema/<?=$config["dir_galeria"]."/thumb450_".$config["capa"]; ?>" alt="<?=$config["nome_fantasia"]; ?>" class="imagem-menu">
                    </a>
                </div>
                <!-- ============== Menu Warpper ================ -->
                <div class="menu-wrapper float-left">
                    <nav id="mega-menu-holder" class="clearfix">
                        <ul>
                            <li><a href="<?=SITE_URL."/criacao-de-sites"; ?>" class="menu-criacao-de-sites">Criação de Sites</a></li>
                            <li><a href="<?=SITE_URL."/marketing-digital"; ?>" class="menu-marketing-digital">Marketing Digital</a></li>
                            <li><a href="<?=SITE_URL."/artes-offline"; ?>" class="menu-artes-offline">Artes Offline</a></li>
                            <li><a href="<?=SITE_URL."/sistemas-web"; ?>" class="menu-sistemas-web">Sistemas Web</a></li>                          
                        </ul>
                    </nav> <!-- /#mega-menu-holder -->
                </div> <!-- /.menu-wrapper -->
            </div> <!-- /.bg-wrapper -->
        </div> <!-- /.container -->
    </div> <!-- /.theme-menu-wrapper -->
    <?php endif; ?>
</header> <!-- /.header-two -->