<head>
		<meta charset="UTF-8">
		<!-- For IE -->
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<!-- For Resposive Device -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Windows Phone -->
		<meta name="msapplication-navbutton-color" content="#fd7e14">
		<!-- iOS Safari -->
		<meta name="apple-mobile-web-app-status-bar-style" content="#fd7e14">		

		<!--SEO-->
		<title><?=$seo["titulo"]; ?></title>
		<meta name="description" content="<?=$seo["descricao"]; ?>">

		

		<!-- Favicon -->
		<link rel="icon" type="image/png" sizes="56" href="<?= STATIC_URL; ?>/img/sistema/<?=$config["dir_galeria"]."/thumb56_".$config["capa"]; ?>">

		<link rel="stylesheet" type="text/css" href="<?=TEMPLATE_CHARLES; ?>/css/style.css">

		<link rel="stylesheet" type="text/css" href="<?=TEMPLATE_CHARLES; ?>/css/responsive.css">

		<link rel="stylesheet" type="text/css" href="<?=STATIC_URL; ?>/templates/hexzy/assets/css/icons.css">


	<style>
		
		/**--------------------- CORES DO SITE --------------------------*/

		/**Icones Home */
		.why-choose-us .single-block .icon{
			color: <?=$layout['cor_primaria']; ?> !important;
		}
		/**Topo */
		.top-header{
			background: <?=$layout['cor_primaria']; ?> !important;
		}
		/** Cores ícones sociais topo*/
		.top-header .social-icon li a{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		/**Slogan topo */
		.top-header .left-widget li{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		/**Texto publicidade footer */
		.texto-publicidade-footer, .texto-publicidade-footer a{
			color:#ccc !important;
			font-size: 14px !important;
		}
		.texto-publicidade-footer a:hover{
			text-decoration: underline;
		}
		/**corpo do site */
		body{
			background-color: #fff !important;
			color: #000 !important;
		}
		/**Titulos banner home */
		.camera_caption h1{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		/**Subtitulo banner home */
		#theme-main-banner .camera_caption p{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}

		/**Menu */

		/***BANNER HOME */
		@media (max-width: 650px) {
			/*.imgLoaded{
				width: 100% !important;
				height: auto !important;
				display: block !important;
			}*/
		}




		.menu-criacao-de-sites{
			color: #5027a2 !important;
		}
		.menu-marketing-digital{
			color: #1e97bf !important;
		}
		.menu-artes-offline{
			color: #c95481 !important;
		}
		.menu-sistemas-web{
			color: #7a6ead !important;
		}

		.menu-criacao-de-sites:hover,
		.menu-marketing-digital:hover,
		.menu-artes-offline:hover,
		.menu-sistemas-web:hover{
			-webkit-filter: drop-shadow(15px 10px 5px rgba(0,0,0,.3));
			filter: drop-shadow(15px 10px 5px rgba(0,0,0,.3));
		}		

		/*.header-two #mega-menu-holder>ul> li> a, .header-two #mega-menu-holder li .sub-toggle, .header-two #mega-menu-holder>ul> li> a:before{
			color: <?//=$layout['cor_primaria']; ?> !important;
		}*/
		/**busca Menu */
		.header-two .theme-menu-wrapper .right-widget .search-option .dropdown-toggle{
			color: <?=$layout['cor_primaria']; ?> !important;
		}
		/**botão da busca MENU */
		.theme-menu-wrapper .right-widget .search-option form button{
			background-color: <?=$layout['cor_primaria']; ?> !important;
			color: <?=$layout['cor_terciaria']; ?> !important;
		}

		/**Botões de ação */
		.theme-button-one{
			background-color: <?=$layout['cor_primaria']; ?>;
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		.theme-button-one:hover{
			background-color: <?=$layout['cor_secundaria']; ?> !important;
			color: <?=$layout['cor_terciaria']; ?> !important;
		}

		/**Informação abaixo do banner da home */
		.callout-banner{
			background-color: <?=$layout['cor_secundaria']; ?> !important;
		}
		.callout-banner h3{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		.callout-banner p{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}

		/**Fundo Caixa empresa Home Destaque */
		.about-compnay-two .overlay{
			background-color: <?=$layout['cor_primaria']; ?> !important;
		}
		/**Titulo Fundo Caixa empresa home destaque */
		.about-compnay-two h2{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		.about-compnay-two .text p{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		.about-compnay-two button{
			background-color: <?=$layout['cor_secundaria']; ?> !important;
		}

		/**Menu categoria produto/serviço selecionada */
		.theme-sidebar-one .service-categories ul li a:hover, .theme-sidebar-one .service-categories ul li.active a{
			background-color: <?=$layout['cor_primaria']; ?> !important;
			border-color: <?=$layout['cor_secundaria']; ?> !important;
			color: <?=$layout['cor_terciaria']; ?> !important;
		}

		.theme-sidebar-one .service-categories ul li a{
			border-color: <?=$layout['cor_primaria']; ?> !important;
			color: <?=$layout['cor_primaria']; ?> !important;
		}

		/**card produto/serviço cor transparencia frente */
		.our-case .single-case-block .hover-content{
			background-color: #daf2ff99 !important;
		}

		/**Botão de ação para single card produto/serviço */
		.our-case .single-case-block .hover-content .text .details{
			background-color: <?=$layout['cor_terciaria']; ?> !important;
		}
		.our-case .single-case-block .hover-content .text .details:hover{
			background-color: <?=$layout['cor_primaria']; ?> !important;
		}

		/**FAQ */
		.faq-section .overlay{
			background-color: <?=$layout['cor_primaria']; ?> !important;
		}
		.faq-section .overlay h2{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}		
		.faq-section .theme-title-one p{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		
		/**Cor data ultimas noticias */
		.date{
			background-color: <?=$layout['cor_primaria']; ?> !important;
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		/**Titulo ultimas noticias */
		.title{
			color: #000 !important;
		}
		/**Link saiba mais ultimas noticias */
		.read-more{
			color: <?=$layout['cor_primaria']; ?> !important;
		}

		/**BANNER CURTO */
		.short-banner{
			background-color: <?=$layout['cor_primaria']; ?> !important;
		}
		.short-banner h2{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}

		/**FOOTER */
		.theme-footer-two, .top-footer{
			background-color: <?=$layout['cor_primaria']; ?> !important;
		}
		.theme-footer-two, .top-footer p{
			color: <?=$layout['cor_terciaria']; ?> !important;
			font-weight: normal;
		}
		.theme-footer-two .logo-widget .social-icon li a{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		.theme-footer-one .top-footer .title{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		.theme-footer-one .top-footer .footer-list ul li a{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		.theme-footer-two .top-footer .footer-list ul li:before{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		.date-footer{
			color: <?=$layout['cor_terciaria']; ?> !important;
			font-size: 14px !important;
		}
		.theme-footer-two .top-footer .contact-widget ul li{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		.theme-footer-two .top-footer .contact-widget ul li a{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		.theme-footer-one .bottom-footer{
			background-color: <?=$layout['cor_primaria']; ?> !important;
		}
		.texto-publicidade-footer, .texto-publicidade-footer a{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}
		.logo-widget h6{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}


		/**------------------EMPRESA------------------*/

		/**Informação abaixo do banner da home */
		.callout-banner-institucional{
			background-color: <?=$layout['cor_terciaria']; ?> !important;
		}
		.callout-banner-institucional h3{
			color: #000 !important;
		}
		.callout-banner-institucional p{
			color: #404040 !important;
		}
		
		/**Fundo bloco missão visao valores */
		.why-we-best .overlay{
			background-color: <?=$layout['cor_primaria']; ?> !important;
		}
		.titulo-missao{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}

		/**Cores do icones */
		.why-we-best .wrapper .best-list-item li .icon{
			color: <?=$layout['cor_primaria']; ?> !important;
		}
		/**Cores do texto */
		.cor-m-v-v{
			color: #000 !important;
		}
		/**Números final página */
		.single-counter-box .number{
			color: <?=$layout['cor_primaria']; ?> !important;
		}


		/**----------------EQUIPE--------------------------------- */

		/**Fundo box equipe*/
		.our-team .team-member .overlay{
			background-color: <?=$layout['cor_primaria']; ?> !important;
		}
		.our-team .team-member .overlay .hover-content p{
			color: <?=$layout['cor_terciaria']; ?> !important;
		}


		/**------------------DETALHES DE PRODUTOS OU SERVIÇOS------------ */
		.botao-pagamento{
			background-color: #20c218 !important;
		}
		.botao-pagamento:hover{
			background-color: #34d32c !important;
		}


		/**----------------GERAL DO SITE-------------------------- */

		/**Subtitulos site */
		h2,h3,h4,h5{
			color: <?=$layout['cor_primaria']; ?>;
		}

		/**URL de titulos */
		h5 a{
			color: #000 !important;
		}

		/**Textos do site */		
		p{
			color: #000 !important;
			font-weight: normal !important;
		}

		/**Titulo páginas internas */
		.theme-inner-banner{
			background-color: <?=$layout['cor_primaria']; ?>;
		}
		.theme-inner-banner h1{
			color: <?=$layout['cor_terciaria']; ?> !important;
			font-size: 40px !important;
			line-height: 40px !important;
			font-weight: 900 !important;
			text-transform: uppercase !important;
		}

		/**MENU */
		.imagem-menu{
			margin-top: 10px; 
			max-width: 200px;
		}
		

		/**-----------RESPONSIVO------------------- */

		@media (max-width: 1400px) {
			#theme-main-banner{
				height: 500px !important;
			}
			.why-choose-us{
				margin-top: 60px !important;
			}
		}

		/**Titulo interno páginas */
		@media (max-width: 991px) {
			.theme-inner-banner h1{
				font-size: 30px !important;
			}
			.header-two .theme-menu-wrapper .bg-wrapper{
				padding: 12px 0;
			}
			.header-two .collapse-button .icon-bar{
				background-color: <?=$layout['cor_primaria']; ?> !important;
			}
			.header-two{
				height: 120px;
				width: 100%;
			}
			.bg-wrapper{
				height: 100px;
				background-color: #fff;
			}
			#theme-main-banner{
				height: 400px !important;
				top: 0 !important;
			}			
		}

		@media (max-width: 691px) {
			#theme-main-banner{
				height: 290px !important;
				top: 0 !important;
			}
			.why-choose-us{
				margin-top: 0 !important;
			}
		}

		.imgLoaded{
			width: 100% !important;
			height: auto !important;
			display: block !important;
			margin-left: 0 !important;
		}		
		#theme-main-banner .camera_overlayer{
			background: none !important;
		}	

		/***CSS ENVIADO PELO USUÁRIO */
		<?=$layout['css']; ?>


	</style>

</head>