<header class="header-two">
    <div class="top-header">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-8 col-12">
                    <ul class="left-widget">
                        <li style="margin: 0 10px 0 0;">Slogam da empresa aqui!</li>
                        <li><i class="flaticon-phone-call"></i> (00) 0000-0000</li>
                    </ul>
                </div>
                <div class="col-md-6 col-sm-4 col-12">
                    <ul class="social-icon">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-youtube" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
            </div> <!-- /.row -->
        </div> <!-- /.container -->
    </div> <!-- /.top-header -->

    <div class="theme-menu-wrapper">
        <div class="container">
            <div class="bg-wrapper clearfix">
                <div class="logo float-left"><a href="<?=SITE_URL;?>"><img src="<?= TEMPLATE_CHARLES; ?>/images/logo/logo.png" alt=""></a></div>
                <!-- ============== Menu Warpper ================ -->
                <div class="menu-wrapper float-left">
                    <nav id="mega-menu-holder" class="clearfix">
                        <ul class="clearfix">
                            <li><a href="<?=SITE_URL; ?>/empresa">A Empresa</a>
                            </li>
                            <li><a href="<?=SITE_URL; ?>/produtos">Produtos</a>
                                <ul class="dropdown">
                                    <li><a href="<?=SITE_URL; ?>/produtos#Linha-Home-1">Linha Home</a></li>
                                    <li><a href="<?=SITE_URL; ?>/produtos#Linha-Premium-5">Linha Premium</a></li>
                                    <li><a href="<?=SITE_URL; ?>/produtos#Linha-Delux-6">Linha Deluxe</a></li>
                                </ul>
                            </li>
                            <li><a href="<?=SITE_URL; ?>/servicos">Serviços</a></li>
                            <li><a href="<?=SITE_URL; ?>/projetos">Projetos</a></li>
                            <li><a href="<?=SITE_URL; ?>/clientes">Clientes</a></li>
                            <li><a href="<?=SITE_URL; ?>/contato">Contato</a></li>
                        </ul>
                    </nav> <!-- /#mega-menu-holder -->
                </div> <!-- /.menu-wrapper -->
                <div class="right-widget float-right">
                    <ul>
                        <li class="search-option">
                            <div class="dropdown">
                                <button type="button" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search" aria-hidden="true"></i></button>
                                <form action="#" class="dropdown-menu">
                                    <input type="text" Placeholder="Procure no site">
                                    <button><i class="fa fa-search"></i></button>
                                </form>
                            </div>
                        </li>
                    </ul>
                </div> <!-- /.right-widget -->
            </div> <!-- /.bg-wrapper -->
        </div> <!-- /.container -->
    </div> <!-- /.theme-menu-wrapper -->
</header> <!-- /.header-two -->