<div class="shop-details">
<div class="container">
    <div class="related-product shop-page">
        <div class="theme-title-one">
            <h2>Outros <?= $nomeControlador; ?></h2>
        </div> <!-- /.theme-title-one -->
        <div class="celarfix">
            <div class="related-product-slider">

                <?php for ($i = 0; $i < 10; $i++) : ?>
                    <div class="item">
                        <div class="single-product">
                            <div class="single-case-block">
                                <a href="<?= SITE_URL; ?>/<?= $nomeControlador; ?>/detalhes/nome-do-produto-aqui">
                                    <img src="<?= TEMPLATE_CHARLES; ?>/images/home/15.jpg">
                                </a>

                                <div class="float-left">
                                    <a href="<?= SITE_URL; ?>/<?= $nomeControlador; ?>/detalhes/nome-do-produto-aqui">
                                        <h5>Nome do produto aqui nessa aba.</h5>
                                    </a>
                                </div>
                            </div> <!-- /.single-case-block -->
                        </div> <!-- /.single-product -->
                    </div> <!-- /.col- -->
                <?php endfor; ?>

            </div> <!-- /.related-product-slider -->
        </div>
    </div> <!-- /.related-product -->
</div>
</div>