<script src="<?= TEMPLATE_CHARLES; ?>/vendor/jquery.2.2.3.min.js"></script>
<!-- Popper js -->
<script src="<?= TEMPLATE_CHARLES; ?>/vendor/popper.js/popper.min.js"></script>
<!-- Bootstrap JS -->
<script src="<?= TEMPLATE_CHARLES; ?>/vendor/bootstrap/js/bootstrap.min.js"></script>
<!-- Camera Slider -->
<script src='<?= TEMPLATE_CHARLES; ?>/vendor/Camera-master/scripts/jquery.mobile.customized.min.js'></script>
<script src='<?= TEMPLATE_CHARLES; ?>/vendor/Camera-master/scripts/jquery.easing.1.3.js'></script>
<script src='<?= TEMPLATE_CHARLES; ?>/vendor/Camera-master/scripts/camera.min.js'></script>
<!-- menu  -->
<script src="<?= TEMPLATE_CHARLES; ?>/vendor/menu/src/js/jquery.slimmenu.js"></script>
<!-- WOW js -->
<script src="<?= TEMPLATE_CHARLES; ?>/vendor/WOW-master/dist/wow.min.js"></script>
<!-- owl.carousel -->
<script src="<?= TEMPLATE_CHARLES; ?>/vendor/owl-carousel/owl.carousel.min.js"></script>
<!-- js count to -->
<script src="<?= TEMPLATE_CHARLES; ?>/vendor/jquery.appear.js"></script>
<script src="<?= TEMPLATE_CHARLES; ?>/vendor/jquery.countTo.js"></script>
<!-- Fancybox -->
<script src="<?= TEMPLATE_CHARLES; ?>/vendor/fancybox/dist/jquery.fancybox.js"></script>
<!-- Language Stitcher -->
<script src="<?= TEMPLATE_CHARLES; ?>/vendor/language-switcher/jquery.polyglot.language.switcher.js"></script>


<!-- Theme js -->
<script src="<?= TEMPLATE_CHARLES; ?>/js/theme.js"></script>