<?php
$dados["notificacoes"] = $notificacoes;
$dados["totalNotificacoesNaoLidas"] = $totalNotificacoesNaoLidas;
?>
<!doctype html>
<html lang="pt-br">
<!--HEAD + CSS-->
<?= $this->loadview('admin/includes/head'); ?>

<body>
    <!--TOPO + MENU-->
    <?= $this->loadview('admin/includes/header', $dados); ?>

    <!--CONTEÚDO-->
    <div class="wrapper">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-md-8">

                                <ol class="breadcrumb">
                                    <?php foreach ($breadcrumb as $indice => $valor) : ?>
                                        <?php if (!empty($valor["url"])) : ?>
                                            <li class="breadcrumb-item"><a href="<?= $valor["url"]; ?>"><?= $valor["nome"]; ?></a></li>
                                        <?php else : ?>
                                            <li class="breadcrumb-item active"><a><?= $valor["nome"]; ?></a></li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ol>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-body">

                            <!--Conteúdo-->
                            <section>
                                <form id="cadastroForm" enctype="multipart/form-data" action="" onsubmit="return false;">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="card border-light mb-3">
                                                    <div class="card-header">Imagens do blog (1920x780)</div>
                                                    <div class="card-body">
                                                        <div class="input-group mb-3">
                                                            <div class="col-lg-12">
                                                                <div class="input-group mb-3">
                                                                    <?php foreach ($galeria as $valor) : ?>
                                                                        <a href="javascript:onclick=salvarCapaGaleria('<?= SITE_URL . "/banner-principal/salvar-capa-galeria/" . $valor . "/" . $dadosBanco["id"]; ?>');">
                                                                            <img src="<?= STATIC_URL; ?>/img/banner/<?= $dadosBanco["dir_galeria"]; ?>/thumb420_<?= $valor; ?>" class="img-thumbnail img-galeria <?= ($dadosBanco["capa"] == $valor) ? "img-galeria-selected" : ""; ?>">
                                                                        </a><br>
                                                                        <a href="javascript:onclick=excluirCapaGaleria('<?= SITE_URL . "/banner-principal/excluir-capa-galeria/" . $dadosBanco["dir_galeria"] . "/" . $valor; ?>');">
                                                                            <span class="badge badge-danger">X</span>
                                                                        </a>
                                                                    <?php endforeach ?>
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Imagem do banner">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-camera"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="file" class="form-control" id="foto" name="foto" multiple="" accept="image/x-png,image/gif,image/jpeg">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            
                                                            <?php if($galeria): ?>
                                                            <div class="col-lg-6">
                                                            <button type="button" class="btn btn-danger float-right botao-efeito" onclick="excluirTodasFotosGaleria('<?=SITE_URL.'/banner-principal/excluir-todas-fotos/'.$dadosBanco['dir_galeria']; ?>');">
                                                                Remover todas as fotos <i class="mdi mdi-delete"></i>
                                                            </button>
                                                            </div>
                                                            <!--Fim Campo input-->  
                                                            <?php endif; ?>                                                          
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Fim Foto-->

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="card border-light mb-3">
                                                    <div class="card-header">Conteúdo do Banner</div>
                                                    <div class="card-body">
                                                        <div class="input-group mb-3">
                                                            <div class="col-lg-12">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Esse título não irá aparecer no site">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-pencil-alt"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Título *" id="titulo" name="titulo" value="<?= $dadosBanco["titulo"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Texto menor do banner">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-pencil-alt"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Pequeno Texto" id="pequeno_texto" name="pequeno_texto" value="<?= $dadosBanco["pequeno_texto"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Texto maior do banner">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-pencil-alt"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Grande Texto" id="grande_texto" name="grande_texto" value="<?= $dadosBanco["grande_texto"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-12">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Se inserir a URL, irá criar um botão de ação no banner">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-link"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="URL" id="url" name="url" value="<?= $dadosBanco["url"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Fim Dados Usuário-->

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="card border-light mb-3">
                                                    <div class="card-header">Configurações</div>
                                                    <div class="card-body">
                                                        <div class="input-group mb-3">
                                                        <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Se deixar Sim, irá aparecer o banner no site">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-tv"></i>
                                                                        </span>
                                                                    </div>
                                                                    <select name="ativo" class="custom-select" id="ativo">
                                                                        <option value="S" <?= ($dadosBanco["ativo"] == "S") ? "selected" : ""; ?>>Publicar: (Sim)</option>
                                                                        <option value="N" <?= ($dadosBanco["ativo"] == "N") ? "selected" : ""; ?>>Publicar: (Não)</option>
                                                                    </select>
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                        <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Ordem de exibição do banner">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-tv"></i>
                                                                        </span>
                                                                    </div>
                                                                    <select name="ordem" class="custom-select" id="ordem">
                                                                        <?php for($i=1; $i<20; $i++): ?>
                                                                        <option value="<?=$i;?>" <?= ($dadosBanco["ordem"] == $i) ? "selected" : ""; ?>>Ordem: (<?=$i;?>)</option>
                                                                        <?php endfor; ?>
                                                                    </select>
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Fim Documentos-->                                        

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <button type="button" class="btn btn-success float-right botao-efeito" id="bt-salvar" onclick="formSubmit('#cadastroForm','<?= $urlAction; ?>');">
                                                    Salvar <i class="mdi mdi-check"></i>
                                                </button>
                                                <div id="resposta-form" class="float-right" style="margin: 0 10px 0 0;">
                                                    <!--Resposta do Server-->
                                                    <p>Campos com * são obrigatórios</p>
                                                </div>                                                
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </section>


                        </div>
                    </div>
                </div>



            </div> <!-- end container-fluid -->
        </div>
    </div>
    <!--CONTEÚDO-->


    <!--FOOTER-->
    <?= $this->loadview('admin/includes/footer'); ?>

    <!--JAVSCRIPT-->
    <?= $this->loadview('admin/includes/scripts'); ?>

    <script>
        $(document).ready(function(){
            $('#whatsapp').mask('(00) 0 0000-0000');
            $('#nascimento').mask('00/00/0000');
            $('#cpf').mask('000.000.000-00');
        });
        //Lendo Enter do documento para chamar o form
        $("input[type='text']").on('keydown', function(event) {
            if (event.keyCode === 13){
                formSubmit('#cadastroForm','<?= $urlAction; ?>');
            }
        });                
    </script>
</body>

</html>