<!DOCTYPE html>
<html lang="pt-br">

<?php $this->loadview('templates/moniz/includes/head'); ?>

<body>


    <div class="preloader">
        <img class="preloader__image" width="120" src="<?=TEMPLATE_MONIZ; ?>/images/loader.png" />
    </div>
    <!-- /.preloader -->
    <div class="page-wrapper">

    <?php $this->loadview('templates/moniz/includes/header'); ?>



        <!-- Banner One Start -->
        <?php $this->loadview('templates/moniz/includes/banners-home'); ?>
        <!--Banner One End-->

        <!--Areas of Practice Start-->
        <section class="areas-of-practice">
            <div class="container">
                <div class="areas-of-practice__top">
                    <div class="row">
                        <div class="col-xl-6 col-lg-6">
                            <div class="areas-of-practice__top-left">
                                <div class="section-title text-left">
                                    <span class="section-title__tagline">Saiba mais como</span>
                                    <h2 class="section-title__title">Podemos ajudar o seu negócio.</h2>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-6">
                            <div class="areas-of-practice__top-right">
                                <p class="areas-of-practice__top-right-text">Veja abaixo um pouco mais como podemos ajudar o seu negócio, a ter uma presença online de confiança e mais profissional.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="areas-of-practice__bottom">
                    <div class="row">
                        <div class="col-xl-3 col-lg-6 col-md-6">
                            <!--Areas of Practice Single-->
                            <div class="areas-of-practice__single">
                                <div class="areas-of-practice__icon-box">
                                    <div class="areas-of-practice__icon">
                                        <span class="icon-color-sample"></span>
                                    </div>
                                    <div class="areas-of-practice__title">
                                        <h3><a href="<?=SITE_URL; ?>/desenvolvimento-de-sites">Websites Profissionais</a></h3>
                                    </div>
                                </div>
                                <p class="areas-of-practice__text">Criamos o site da sua empresa, de forma profissional e de alto desempenho no google.</p>
                                <a href="<?=SITE_URL; ?>/desenvolvimento-de-sites" class="areas-of-practice__read-more"><i
                                        class="icon-right-arrow"></i></a>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-6 col-md-6">
                            <!--Areas of Practice Single-->
                            <div class="areas-of-practice__single">
                                <div class="areas-of-practice__icon-box">
                                    <div class="areas-of-practice__icon">
                                        <span class="icon-front-end"></span>
                                    </div>
                                    <div class="areas-of-practice__title">
                                        <h3><a href="<?=SITE_URL; ?>/desenvolvimento-de-sistemas-web">Sistemas Web</a></h3>
                                    </div>
                                </div>
                                <p class="areas-of-practice__text">Desenvolvemos sistemas na nuvem para o seu negócio, 16 anos de experiência em desenvolvimento e startups.</p>
                                <a href="<?=SITE_URL; ?>/desenvolvimento-de-sistemas-web" class="areas-of-practice__read-more"><i
                                        class="icon-right-arrow"></i></a>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-6 col-md-6">
                            <!--Areas of Practice Single-->
                            <div class="areas-of-practice__single">
                                <div class="areas-of-practice__icon-box">
                                    <div class="areas-of-practice__icon">
                                        <span class="icon-online-shopping"></span>
                                    </div>
                                    <div class="areas-of-practice__title">
                                        <h3><a href="<?=SITE_URL; ?>/marketing-digital">Marketing Digital</a></h3>
                                    </div>
                                </div>
                                <p class="areas-of-practice__text">Trabalhamos com a gestão de redes sociais, mkt digital para sites com SEO, google orgânico e google ads.</p>
                                <a href="<?=SITE_URL; ?>/marketing-digital" class="areas-of-practice__read-more"><i
                                        class="icon-right-arrow"></i></a>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-6 col-md-6">
                            <!--Areas of Practice Single-->
                            <div class="areas-of-practice__single">
                                <div class="areas-of-practice__icon-box">
                                    <div class="areas-of-practice__icon">
                                        <span class="icon-graphic-design"></span>
                                    </div>
                                    <div class="areas-of-practice__title">
                                        <h3><a href="<?=SITE_URL; ?>/artes-digitais">Artes Digitais</a></h3>
                                    </div>
                                </div>
                                <p class="areas-of-practice__text">postagens para redes sociais, Logomarcas, Cartões de visita digitais, Catálogos online, banners para sites.</p>
                                <a href="<?=SITE_URL; ?>/artes-digitais" class="areas-of-practice__read-more"><i
                                        class="icon-right-arrow"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--Areas of Practice End-->

        <!--Build Business Start-->
        <section class="build-business">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6">
                        <div class="build-business__left">
                            <div class="build-business__left-bg"></div>
                            <div class="build-business__img wow fadeInLeft" data-wow-duration="1500ms">
                                <img src="<?=TEMPLATE_MONIZ; ?>/images/resources/build-business-img-1.jpg" alt="">
                                <div class="build-business__img-shape-1"></div>
                                <div class="build-business__img-shape-2"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6">
                        <div class="build-business__right">
                            <div class="section-title text-left">
                                <span class="section-title__tagline">J6 Também trabalha com</span>
                                <h2 class="section-title__title">Edição de vídeos profissionais</h2>
                            </div>
                            <p class="build-business__right-text">Trabalhamos desde da edição dos vídeos, a criação de roteiros super criativos e profissionais.</p>
                            <div class="build-business__points">
                                <div class="build-business__points-single">
                                    <div class="build-business__icon">
                                        <span class="icon-tick"></span>
                                    </div>
                                    <div class="build-business__text">
                                        <h4 class="build-business__title">Vídeos institucionais</h4>
                                        <p class="build-business__desc">Criamos vídeos institucionais para a sua empresa, seja para você usar nas suas mídias, enviar por email para seus clientes ou usar em uma propaganda de tv, apresentar seu negócio em vídeo sempre é uma boa maneira de se fazer.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="build-business__mission">
                                <div class="build-business__video">
                                    <img src="<?=TEMPLATE_MONIZ; ?>/images/resources/build-business-video-img.png" alt="">
                                    <a href="https://www.youtube.com/watch?v=o5wQqtnod-4"
                                        class="build-business__video-btn video-popup">
                                        <div class="build-business__video-icon">
                                            <span class="icon-play-button"></span>
                                        </div>
                                    </a>
                                </div>
                                <div class="build-business__video-text">
                                    <h4>Veja esse vt de propaganda para a tv do cliente Postos Meta.</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--Build Business End-->

        <!--Portfolio Two Start-->
        <section class="portfolio-two">
            <div class="container">
                <div class="section-title text-center">
                    <span class="section-title__tagline">Um pouco do que já entregamos</span>
                    <h2 class="section-title__title">Portfólio J6</h2>
                </div>
                <div class="portfolio-two__carousel owl-theme owl-carousel">
                    <?php for($i=0; $i<10; $i++): ?>
                    <div class="portfolio-one__single">
                        <div class="portfolio-one__img">
                            <img src="<?=TEMPLATE_MONIZ; ?>/images/resources/portfolio-2-1.jpg" alt="">
                            <div class="portfolio-one__experience">
                                <div class="portfolio-one__web-design">
                                    <p class="portfolio-one__web-design-title">Criação de sites</p>
                                </div>
                                <div class="portfolio-one__fimlor">
                                    <p class="portfolio-one__fimlor-title">
                                        <a href="<?=SITE_URL; ?>/portfolio/site-institucional-postos-meta">
                                            Site Institucional Postos Meta
                                        </a>
                                    </p>
                                </div>
                            </div>
                            <div class="portfolio-one__arrow">
                                <a href="<?=SITE_URL; ?>/portfolio/site-institucional-postos-meta"><span class="icon-right-arrow"></span></a>
                            </div>
                        </div>
                    </div>
                    <?php endfor; ?>
                    <!--Portfolio One Single-->
                </div>
            </div>
        </section>
        <!--Portfolio Two End-->

        <!--Web Solutions Start-->
        <section class="web-solutions">
            <div class="web-solutions-bg" style="background-image: url(<?=TEMPLATE_MONIZ; ?>/images/backgrounds/web-solutions-bg.jpg)">
            </div>
            <div class="container">
                <div class="section-title text-center">
                    <span class="section-title__tagline">Saiba o que podemos passar da nossa</span>
                    <h2 class="section-title__title">Experiência para o seu negócio</h2>
                </div>
                <div class="row">
                    <div class="col-xl-12">
                        <div class="web-solutions__box tabs-box">
                            <ul class="tab-btns tab-buttons clearfix list-unstyled">
                                <li data-tab="#business" class="tab-btn"><span>Experiência em sites e sistemas</span></li>
                                <li data-tab="#financial" class="tab-btn active-btn"><span>Experiência em mkt digital</span></li>
                                <li data-tab="#gobal" class="tab-btn"><span>Experiência em negócios</span></li>
                            </ul>
                            <div class="tabs-content">
                                <div class="tab" id="business">
                                    <div class="web-solutions__content">
                                        <div class="row">
                                            <div class="col-xl-6 col-lg-6">
                                                <div class="web-solutions__content-img">
                                                    <img src="<?=TEMPLATE_MONIZ; ?>/images/resources/web-solutions-content-img.jpg"
                                                        alt="">
                                                    <div class="web-solutions__trusted">
                                                        <div class="web-solutions__trusted-icon">
                                                            <i class="icon-relationship"></i>
                                                        </div>
                                                        <div class="web-solutions__trusted-text">
                                                            <h3>Temos aproximadamente <br>
                                                                <span class="odometer" data-count="6805">00</span>
                                                                dias de experiência.
                                                            </h3>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xl-6 col-lg-6">
                                                <div class="web-solutions__content-right">
                                                    <p class="web-solutions__content-desc">There are many variations of
                                                        passages of lorem ipsum available, but the majority have
                                                        suffered alteration in some form injected humour or randomised
                                                        words which don't look even believable. If you are going to use
                                                        a passage of Lorem Ipsum, you need to be sure there isn't
                                                        anything embarrassing hidden in the middle of text.</p>
                                                    <ul class="list-unstyled web-solutions__content-list">
                                                        <li>
                                                            <div class="icon">
                                                                <span class="icon-tick"></span>
                                                            </div>
                                                            <div class="text">
                                                                <p>Highly trained in administrative tasks</p>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <div class="icon">
                                                                <span class="icon-tick"></span>
                                                            </div>
                                                            <div class="text">
                                                                <p>Professionally managed and supported</p>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <div class="icon">
                                                                <span class="icon-tick"></span>
                                                            </div>
                                                            <div class="text">
                                                                <p>Proficient in google, and most popular productivity
                                                                    suites</p>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="tab active-tab" id="financial">
                                    <div class="web-solutions__content">
                                        <div class="row">
                                            <div class="col-xl-6 col-lg-6">
                                                <div class="web-solutions__content-img">
                                                    <img src="<?=TEMPLATE_MONIZ; ?>/images/resources/web-solutions-content-img.jpg"
                                                        alt="">
                                                    <div class="web-solutions__trusted">
                                                        <div class="web-solutions__trusted-icon">
                                                            <i class="icon-relationship"></i>
                                                        </div>
                                                        <div class="web-solutions__trusted-text">
                                                            <h3>Temos aproximadamente <br>
                                                                <span class="odometer" data-count="4015">00</span>
                                                                dias de experiência.
                                                            </h3>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xl-6 col-lg-6">
                                                <div class="web-solutions__content-right">
                                                    <p class="web-solutions__content-desc">There are many variations of
                                                        passages of lorem ipsum available, but the majority have
                                                        suffered alteration in some form injected humour or randomised
                                                        words which don't look even believable. If you are going to use
                                                        a passage of Lorem Ipsum, you need to be sure there isn't
                                                        anything embarrassing hidden in the middle of text.</p>
                                                    <ul class="list-unstyled web-solutions__content-list">
                                                        <li>
                                                            <div class="icon">
                                                                <span class="icon-tick"></span>
                                                            </div>
                                                            <div class="text">
                                                                <p>Highly trained in administrative tasks</p>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <div class="icon">
                                                                <span class="icon-tick"></span>
                                                            </div>
                                                            <div class="text">
                                                                <p>Professionally managed and supported</p>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <div class="icon">
                                                                <span class="icon-tick"></span>
                                                            </div>
                                                            <div class="text">
                                                                <p>Proficient in google, and most popular productivity
                                                                    suites</p>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="tab" id="gobal">
                                    <div class="web-solutions__content">
                                        <div class="row">
                                            <div class="col-xl-6 col-lg-6">
                                                <div class="web-solutions__content-img">
                                                    <img src="<?=TEMPLATE_MONIZ; ?>/images/resources/web-solutions-content-img.jpg"
                                                        alt="">
                                                    <div class="web-solutions__trusted">
                                                        <div class="web-solutions__trusted-icon">
                                                            <i class="icon-relationship"></i>
                                                        </div>
                                                        <div class="web-solutions__trusted-text">
                                                            <h3>Temos aproximadamente <br>
                                                                <span class="odometer" data-count="2190">00</span>
                                                                dias de experiência.
                                                            </h3>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xl-6 col-lg-6">
                                                <div class="web-solutions__content-right">
                                                    <p class="web-solutions__content-desc">There are many variations of
                                                        passages of lorem ipsum available, but the majority have
                                                        suffered alteration in some form injected humour or randomised
                                                        words which don't look even believable. If you are going to use
                                                        a passage of Lorem Ipsum, you need to be sure there isn't
                                                        anything embarrassing hidden in the middle of text.</p>
                                                    <ul class="list-unstyled web-solutions__content-list">
                                                        <li>
                                                            <div class="icon">
                                                                <span class="icon-tick"></span>
                                                            </div>
                                                            <div class="text">
                                                                <p>Highly trained in administrative tasks</p>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <div class="icon">
                                                                <span class="icon-tick"></span>
                                                            </div>
                                                            <div class="text">
                                                                <p>Professionally managed and supported</p>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <div class="icon">
                                                                <span class="icon-tick"></span>
                                                            </div>
                                                            <div class="text">
                                                                <p>Proficient in google, and most popular productivity
                                                                    suites</p>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--Web Solutions End-->

        <!--Watch Video Start-->
        <section class="watch-video">
            <div class="container">
                <div class="watch-video__inner">
                    <div class="watch-video__img">
                        <div class="watch-video__img-box">
                            <img src="<?=TEMPLATE_MONIZ; ?>/images/resources/watch-video-img.jpg" alt="">
                            <div class="watch-video-shape-1"></div>
                            <div class="watch-video-shape-2"></div>
                            <div class="watch-video__text">
                                <p>Watch Video</p>
                            </div>
                        </div>
                        <a href="https://www.youtube.com/watch?v=8DP4NgupAhI" class="video-popup">
                            <div class="watch-video__icon">
                                <span class="icon-play-button"></span>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </section>
        <!--Watch Video End-->

        <!--Core Features Start-->
        <section class="core-features">
            <div class="core-features-bg" style="background-image: url(<?=TEMPLATE_MONIZ; ?>/images/backgrounds/core-features-bg.jpg)">
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-6">
                        <div class="core-features__left">
                            <div class="section-title text-left">
                                <span class="section-title__tagline">Core features</span>
                                <h2 class="section-title__title">We take care your business growth</h2>
                            </div>
                            <div class="core-features__left-bottom">
                                <div class="core-features__left-bottom-img">
                                    <img src="<?=TEMPLATE_MONIZ; ?>/images/resources/core-features-left-bottom-img.jpg" alt="">
                                </div>
                                <div class="core-features__left-bottom-text">
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Have
                                        you done google research.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6">
                        <div class="core-features__promicess">
                            <ul class="list-unstyled core-features__promicess-list">
                                <li>
                                    <div class="text">
                                        <p>We promise to respect your time</p>
                                    </div>
                                    <div class="icon">
                                        <span class="icon-tick"></span>
                                    </div>
                                </li>
                                <li>
                                    <div class="text">
                                        <p>We hire only professionals you can trust</p>
                                    </div>
                                    <div class="icon">
                                        <span class="icon-tick"></span>
                                    </div>
                                </li>
                                <li>
                                    <div class="text">
                                        <p>We promise to provide up front pricing</p>
                                    </div>
                                    <div class="icon">
                                        <span class="icon-tick"></span>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--Core Features End-->

        <!--Blog Two Start-->
        <section class="blog-two">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-lg-6 col-xl-12">
                        <div class="blog-two__left">
                            <div class="section-title text-left">
                                <span class="section-title__tagline">Direct from the blog</span>
                                <h2 class="section-title__title">Latest articles directly from the blog</h2>
                            </div>
                            <p class="blog-two__text">There are many variations of passages of Lorem Ipsum available,
                                but the majority have in some form. </p>
                            <div class="blog-two__carousel__custom-nav">
                                <a href="#" class="left-btn"><span class="icon-left-arrow"></span></a>
                                <a href="#" class="right-btn"><span class="icon-right-arrow"></span></a>
                            </div><!-- /.blog-two__carousel__custom-nav -->
                        </div>

                    </div>

                </div>
            </div>
            <div class="blog-two__right">
                <div class="blog-two__right-bg"></div>
                <div class="blog-two__carousel owl-theme owl-carousel">
                    <div class="item">
                        <!--Blog One Single-->
                        <div class="blog-one__single">
                            <div class="blog-one__img-box">
                                <div class="blog-one__img">
                                    <img src="<?=TEMPLATE_MONIZ; ?>/images/blog/blog-2-1.jpg" alt="">
                                    <a href="blog-details.html">
                                        <span class="blog-one__plus"></span>
                                    </a>
                                </div>
                                <div class="blog-one__date-box">
                                    <p><span>20</span> May</p>
                                </div>
                            </div>
                            <div class="blog-one__content">
                                <ul class="list-unstyled blog-one__meta">
                                    <li><a href="blog-details.html"><i class="far fa-user-circle"></i> By
                                            admin</a></li>
                                    <li><a href="blog-details.html"><i class="far fa-comments"></i> 2
                                            Comments</a>
                                    </li>
                                </ul>
                                <h3 class="blog-one__title">
                                    <a href="blog-details.html">Basic rule of running web agency business</a>
                                </h3>
                                <p class="blog-one__text">Lorem ipsum is simply is text used by copytyping
                                    refreshing.</p>
                                <div class="blog-one__bottom">
                                    <div class="blog-one__read-btn">
                                        <a href="blog-details.html">Read more</a>
                                    </div>
                                    <div class="blog-one__arrow">
                                        <a href="blog-details.html"><span class="icon-right-arrow"></span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- /.item -->
                    <div class="item">
                        <!--Blog One Single-->
                        <div class="blog-one__single">
                            <div class="blog-one__img-box">
                                <div class="blog-one__img">
                                    <img src="<?=TEMPLATE_MONIZ; ?>/images/blog/blog-2-2.jpg" alt="">
                                    <a href="blog-details.html">
                                        <span class="blog-one__plus"></span>
                                    </a>
                                </div>
                                <div class="blog-one__date-box">
                                    <p><span>20</span> May</p>
                                </div>
                            </div>
                            <div class="blog-one__content">
                                <ul class="list-unstyled blog-one__meta">
                                    <li><a href="blog-details.html"><i class="far fa-user-circle"></i> By
                                            admin</a></li>
                                    <li><a href="blog-details.html"><i class="far fa-comments"></i> 2
                                            Comments</a>
                                    </li>
                                </ul>
                                <h3 class="blog-one__title">
                                    <a href="blog-details.html">Leverage frameworks to provide a robust</a>
                                </h3>
                                <p class="blog-one__text">Lorem ipsum is simply is text used by copytyping
                                    refreshing.</p>
                                <div class="blog-one__bottom">
                                    <div class="blog-one__read-btn">
                                        <a href="blog-details.html">Read more</a>
                                    </div>
                                    <div class="blog-one__arrow">
                                        <a href="blog-details.html"><span class="icon-right-arrow"></span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- /.item -->
                    <div class="item">
                        <!--Blog One Single-->
                        <div class="blog-one__single">
                            <div class="blog-one__img-box">
                                <div class="blog-one__img">
                                    <img src="<?=TEMPLATE_MONIZ; ?>/images/blog/blog-2-3.jpg" alt="">
                                    <a href="blog-details.html">
                                        <span class="blog-one__plus"></span>
                                    </a>
                                </div>
                                <div class="blog-one__date-box">
                                    <p><span>20</span> May</p>
                                </div>
                            </div>
                            <div class="blog-one__content">
                                <ul class="list-unstyled blog-one__meta">
                                    <li><a href="blog-details.html"><i class="far fa-user-circle"></i> By
                                            admin</a></li>
                                    <li><a href="blog-details.html"><i class="far fa-comments"></i> 2
                                            Comments</a>
                                    </li>
                                </ul>
                                <h3 class="blog-one__title">
                                    <a href="blog-details.html">Organically grow the holistic world view of</a>
                                </h3>
                                <p class="blog-one__text">Lorem ipsum is simply is text used by copytyping
                                    refreshing.</p>
                                <div class="blog-one__bottom">
                                    <div class="blog-one__read-btn">
                                        <a href="blog-details.html">Read more</a>
                                    </div>
                                    <div class="blog-one__arrow">
                                        <a href="blog-details.html"><span class="icon-right-arrow"></span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- /.item -->
                    <div class="item">
                        <!--Blog One Single-->
                        <div class="blog-one__single">
                            <div class="blog-one__img-box">
                                <div class="blog-one__img">
                                    <img src="<?=TEMPLATE_MONIZ; ?>/images/blog/blog-2-1.jpg" alt="">
                                    <a href="blog-details.html">
                                        <span class="blog-one__plus"></span>
                                    </a>
                                </div>
                                <div class="blog-one__date-box">
                                    <p><span>20</span> May</p>
                                </div>
                            </div>
                            <div class="blog-one__content">
                                <ul class="list-unstyled blog-one__meta">
                                    <li><a href="blog-details.html"><i class="far fa-user-circle"></i> By
                                            admin</a></li>
                                    <li><a href="blog-details.html"><i class="far fa-comments"></i> 2
                                            Comments</a>
                                    </li>
                                </ul>
                                <h3 class="blog-one__title">
                                    <a href="blog-details.html">Capitalize on low hanging fruit to identify </a>
                                </h3>
                                <p class="blog-one__text">Lorem ipsum is simply is text used by copytyping
                                    refreshing.</p>
                                <div class="blog-one__bottom">
                                    <div class="blog-one__read-btn">
                                        <a href="blog-details.html">Read more</a>
                                    </div>
                                    <div class="blog-one__arrow">
                                        <a href="blog-details.html"><span class="icon-right-arrow"></span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- /.item -->
                </div>
            </div>
        </section>
        <!--Blog Two End-->

        <!--CTA Two Start-->
        <section class="cta-two">
            <div class="cta-two-shape-1"></div>
            <div class="cta-two-shape-2"></div>
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="cta-two__inner">
                            <div class="cta-two__title">
                                <h2>Making your business ideas come true</h2>
                            </div>
                            <div class="cta-two__btn-box">
                                <span><a href="contact.html"
                                        class="thm-btn cta-two__btn thm-btn--dark thm-btn--dark--light-hover"><span>Free
                                            Consultation</span></a></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--CTA Two End-->

        <!--Site Footer One Start-->
        <?php $this->loadview('templates/moniz/includes/footer'); ?>
        <!--Site Footer One End-->

    </div><!-- /.page-wrapper -->


    <?php $this->loadview('templates/moniz/includes/navbarmobile'); ?>
    <?php $this->loadview('templates/moniz/includes/scripts'); ?>

</body>

</html>