<?php
$dados["notificacoes"] = $notificacoes;
$dados["totalNotificacoesNaoLidas"] = $totalNotificacoesNaoLidas;
?>
<!doctype html>
<html lang="pt-br">
<!--HEAD + CSS-->
<?= $this->loadview('admin/includes/head'); ?>

<body>
    <!--TOPO + MENU-->
    <?= $this->loadview('admin/includes/header', $dados); ?>

    <!--CONTEÚDO-->
    <div class="wrapper">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-md-8">

                                <ol class="breadcrumb">
                                    <?php foreach ($breadcrumb as $indice => $valor) : ?>
                                        <?php if (!empty($valor["url"])) : ?>
                                            <li class="breadcrumb-item"><a href="<?= $valor["url"]; ?>"><?= $valor["nome"]; ?></a></li>
                                        <?php else : ?>
                                            <li class="breadcrumb-item active"><a><?= $valor["nome"]; ?></a></li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ol>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-body">

                            <!--Conteúdo-->
                            <section>
                                <form id="cadastroForm" enctype="multipart/form-data" action="" onsubmit="return false;">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="card border-light mb-3">
                                                    <div class="card-header">Imagens da empresa (1000x855)</div>
                                                    <div class="card-body">
                                                        <div class="input-group mb-3">
                                                            <div class="col-lg-12">
                                                                <div class="input-group mb-3">
                                                                    <?php foreach ($galeria as $valor) : ?>
                                                                        <a href="javascript:onclick=salvarCapaGaleria('<?= SITE_URL . "/institucional-admin/salvar-capa-galeria/" . $valor . "/" . $dadosBanco["id"]; ?>');">
                                                                            <img src="<?= STATIC_URL; ?>/img/institucional/<?= $dadosBanco["dir_galeria"]; ?>/thumb585_<?= $valor; ?>" class="img-thumbnail img-galeria <?= ($dadosBanco["capa"] == $valor) ? "img-galeria-selected" : ""; ?>" width="200px">
                                                                        </a><br>
                                                                        <a href="javascript:onclick=excluirCapaGaleria('<?= SITE_URL . "/institucional-admin/excluir-capa-galeria/" . $dadosBanco["dir_galeria"] . "/" . $valor; ?>');">
                                                                            <span class="badge badge-danger">X</span>
                                                                        </a>
                                                                    <?php endforeach ?>
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Imagens da empresa">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-camera"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="file" class="form-control" id="foto" name="foto" multiple="" accept="image/x-png,image/gif,image/jpeg">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            
                                                            <?php if($galeria): ?>
                                                            <div class="col-lg-6">
                                                            <button type="button" class="btn btn-danger float-right botao-efeito" onclick="excluirTodasFotosGaleria('<?=SITE_URL.'/institucional-admin/excluir-todas-fotos/'.$dadosBanco['dir_galeria']; ?>');">
                                                                Remover todas as fotos <i class="mdi mdi-delete"></i>
                                                            </button>
                                                            </div>
                                                            <!--Fim Campo input-->  
                                                            <?php endif; ?>                                                          
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Fim Foto-->

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="card border-light mb-3">
                                                    <div class="card-header">História da empresa</div>
                                                    <div class="card-body">
                                                        <div class="input-group mb-3">
                                                            <div class="col-lg-12">
                                                                <div class="input-group mb-12">
                                                                    <span class="input-group-text" data-toggle="tooltip" title="Conte aqui um pouco da história da empresa">
                                                                        <i class="fas fa-text-width"></i>
                                                                    </span>                                                                    
                                                                    <textarea name="texto" id="texto" rows="15" placeholder="Conte aqui um pouco da história da empresa *" style="width: 100%;" class="form-control"><?=$dadosBanco["texto"]; ?></textarea>
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="card border-light mb-3">
                                                    <div class="card-header">Missão - Visão - Valores</div>
                                                    <div class="card-body">
                                                        <div class="input-group mb-3">
                                                            <div class="col-lg-12">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Missão">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-puzzle-piece"></i>
                                                                        </span>
                                                                    </div>
                                                                    <textarea name="missao" id="missao" rows="3" placeholder="Missão da empresa" style="width: 100%;" class="form-control"><?=$dadosBanco["missao"]; ?></textarea>
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                        </div>
                                                        <div class="col-lg-12">
                                                            <div class="input-group mb-3">
                                                                <div class="input-group-prepend" data-toggle="tooltip" title="Visão">
                                                                    <span class="input-group-text">
                                                                        <i class="far fa-lightbulb"></i>
                                                                    </span>
                                                                </div>
                                                                <textarea name="visao" id="visao" rows="3" placeholder="Visão da empresa" style="width: 100%;" class="form-control"><?=$dadosBanco["visao"]; ?></textarea>
                                                            </div>
                                                        </div>
                                                        <!--Fim Campo input-->
                                                        <div class="col-lg-12">
                                                            <div class="input-group mb-3">
                                                                <div class="input-group-prepend" data-toggle="tooltip" title="Valores">
                                                                    <span class="input-group-text">
                                                                        <i class="fas fa-medal"></i>
                                                                    </span>
                                                                </div>
                                                                <textarea name="valores" id="valores" rows="3" placeholder="Valores da empresa" style="width: 100%;" class="form-control"><?=$dadosBanco["valores"]; ?></textarea>
                                                            </div>
                                                        </div>
                                                        <!--Fim Campo input-->
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="card border-light mb-3">
                                                    <div class="card-header">Números espetaculares</div>
                                                    <div class="card-body">
                                                        <div class="input-group mb-3">
                                                            <?php for($i=1; $i<=8; $i++): 
                                                                
                                                                $varNumero = "numero_".$i;
                                                                $varTextoNumero = "texto_numero_".$i;
                                                                
                                                                ?>
                                                            <div class="col-lg-3">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Número que irá aparecer no site na página institucional">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-sort-numeric-up"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Número" id="<?=$varNumero;?>" name="<?=$varNumero;?>" value="<?= $dadosBanco[$varNumero]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-9">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Texto do número criado ao lado, informe o que o número representa.">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-text-height"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Texto do número" id="<?=$varTextoNumero;?>" name="<?=$varTextoNumero;?>" value="<?= $dadosBanco[$varTextoNumero]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <?php endfor; ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Fim Documentos-->                                           

                                                            

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <button type="button" class="btn btn-success float-right botao-efeito" id="bt-salvar" onclick="formSubmit('#cadastroForm','<?= $urlAction; ?>');">
                                                    Salvar <i class="mdi mdi-check"></i>
                                                </button>
                                                <div id="resposta-form" class="float-right" style="margin: 0 10px 0 0;">
                                                    <!--Resposta do Server-->
                                                    <p>Campos com * são obrigatórios</p>
                                                </div>                                                
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </section>


                        </div>
                    </div>
                </div>



            </div> <!-- end container-fluid -->
        </div>
    </div>
    <!--CONTEÚDO-->


    <!--FOOTER-->
    <?= $this->loadview('admin/includes/footer'); ?>

    <!--JAVSCRIPT-->
    <?= $this->loadview('admin/includes/scripts'); ?>

    <script>
        $(document).ready(function(){
            $('#numero_1').mask('0000000000');
            $('#numero_2').mask('0000000000');
            $('#numero_3').mask('0000000000');
            $('#numero_4').mask('0000000000');
            $('#numero_5').mask('0000000000');
            $('#numero_6').mask('0000000000');
            $('#numero_7').mask('0000000000');
            $('#numero_8').mask('0000000000');
        });
        //Lendo Enter do documento para chamar o form
        $("input[type='text']").on('keydown', function(event) {
            if (event.keyCode === 13){
                formSubmit('#cadastroForm','<?= $urlAction; ?>');
            }
        });                
    </script>
</body>

</html>