<?php
$dados["config"] = $config;
$dados["layout"] = $layout;
$dados["fraseMotivacional"] = $fraseMotivacional;
$dados["paginasExtras"] = $paginasExtras;
$dados["seo"] = $seo;
$dados["menuTopo"] = $menuTopo;
$dados["menuFooter"] = $menuFooter;
?>
<!DOCTYPE html>
<html lang="pt-br">
<?php $this->loadview('templates/charles/includes/head', $dados); ?>

<body>
	<div class="main-page-wrapper">

		<!-- ===================================================
				Loading Transition
			==================================================== -->
		<div id="loader-wrapper">
			<div id="loader"></div>
		</div>



		<!-- 
			=============================================
				Theme Header Two
			============================================== 
			-->
		<?php $this->loadview('templates/charles/includes/header', $dados); ?>


		<!-- 
			=============================================
				Theme Inner Banner
			============================================== 
			-->
		<div class="theme-inner-banner section-spacing">
			<div class="overlay">
				<div class="container">
					<h1><?=$menuPagina; ?></h1>
				</div> <!-- /.container -->
			</div> <!-- /.overlay -->
		</div> <!-- /.theme-inner-banner -->


		<!-- 
			=============================================
				BUSCA
			============================================== 
			-->
		<?php if(!empty($busca)): ?>
		<div class="callout-banner callout-banner-institucional no-bg">
			<div class="container clearfix">
				<h3 class="title">BUSCA</h3>
				<p>Você buscou pela palavra <strong><?=$busca; ?></strong>. Foram encontrado(s) <strong><?=$totalRows; ?> resultado(s)</strong></p>
			</div>
		</div> <!-- /.callout-banner -->
		<?php endif; ?>


		<!-- 
			=============================================
				Our Blog
			============================================== 
			-->
		<div class="blog-inner-page section-spacing">
			<div class="container">
				<div class="row">
					<div class="col-xl-9 col-lg-8 col-12 our-blog">
						<div class="post-wrapper">

							<?php foreach ($blog as $i => $valor) : ?>
								<div class="row" style="margin-bottom: 20px;">
									<div class="col-lg-6">
										<a href="<?= SITE_URL; ?>/<?=Common::slug($valor["titulo"]); ?>">
											<img src="<?= Common::getImg("blog/{$valor['dir_galeria']}/thumb870_{$valor['capa']}", "blog"); ?>" style="border-radius: 10px;">
										</a>
									</div>
									<div class="col-lg-6">
										<h3 class="title">
											<a href="<?= SITE_URL; ?>/<?=Common::slug($valor["titulo"]); ?>">
												<?= $valor["titulo"]; ?>
											</a>
										</h3>
										<div class="overlay">
										<a href="<?= SITE_URL; ?>/<?=Common::slug($valor["titulo"]); ?>">
												<?= Common::converteTimestamp($valor["data"]) ?>
											</a>
										</div>
										<div class="overlay">
										<a href="<?= SITE_URL; ?>/<?=Common::slug($valor["titulo"]); ?>">
											<button class="theme-button-one" style="margin: 20px 0 0 0;">
												Ler Matéria
											</button>
											</a>
										</div>
									</div> <!-- /.post-meta -->
								</div> <!-- /.single-blog -->
							<?php endforeach; ?>
						</div> <!-- /.post-wrapper -->

						<?php if(count($blog) == 0): ?>
						<div>
							<h2>Sua busca retornou nenhum resultados!</h2>
							<button class="theme-button-one" onclick="javascript:redir('<?= $urlAction; ?>');" style="margin: 20px 0 0 0;">
								Voltar ao Blog
							</button>
						</div>
						<?php endif; ?>

						<div class="theme-pagination">
							<ul>
								<?php foreach ($pageView as $valor) : ?>
									<li <?= $valor["active"]; ?>><a href="<?= $valor["url"]; ?>">
											<?= $valor["page_number"]; ?></a>
									</li>
								<?php endforeach; ?>
							</ul>
						</div>
					</div>


					<!-- ===================== Blog Sidebar ==================== -->
					<div class="col-xl-3 col-lg-4 col-md-6 col-sm-8 col-12 blog-sidebar">
						<div class="sidebar-container sidebar-search">
							<input class="form-control mr-sm-2" type="text" placeholder="Digite Algo..." id="inputBusca" value="" onkeydown="redirEnter('<?= $urlAction; ?>/'+$('#inputBusca').val(),'#inputBusca')" onkeyup="trocarEspaco($('#inputBusca').val());">
							<button class="theme-button-one" onclick="javascript:redir('<?= $urlAction; ?>/'+$('#inputBusca').val());" style="margin-top: 10px;">
								Pesquisar <i class="fas fa-search"></i>
							</button>
							<?php if (!empty($busca)) : ?>
								<button type="button" class="btn btn-link" style="color: red;" onclick="javascript:redir('<?= $urlAction; ?>');">
									Limpar Busca X
								</button>
							<?php endif; ?>

						</div> <!-- /.sidebar-search -->

						<div class="sidebar-tags">
							<h5 class="title">Hashtags</h5>
							<ul class="clearfix">
								<?php foreach($tags as $valor): ?>
								<li>
									<a href="<?=SITE_URL;?>/<?=Common::slug($menuPagina); ?>/materias/1/<?=Common::getStringtoUrl($valor); ?>">
										#<?=$valor; ?>
									</a>
								</li>
								<?php endforeach; ?>
							</ul>
						</div> <!-- /.sidebar-tags -->

					</div> <!-- /.col- -->

				</div> <!-- /.row -->
			</div> <!-- /.container -->
		</div> <!-- /.blog-inner-page -->




		<!--
			=====================================================
				Footer
			=====================================================
			-->
		<?php $this->loadview('templates/charles/includes/footer', $dados); ?>


		<!-- Optional JavaScript _____________________________  -->

		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<!-- jQuery -->
		<?php $this->loadview('templates/charles/includes/scripts'); ?>
		<script>
			function redir(url) {
				window.location.href = url;
			}

			function redirEnter(url, id) {
				$(id).on('keydown', function(e) {
					if (e.which === 13) {
						e.preventDefault();
						window.location.href = url;
					}
				});
			}

			function trocarEspaco(valorInput){
				let text = valorInput;
				let result = text.replace(" ", "-");
				$('#inputBusca').val(result);
			}

		</script>
	</div> <!-- /.main-page-wrapper -->
</body>

</html>