<!DOCTYPE html>
<html lang="pt-br">
<?php $this->loadview('templates/charles/includes/head'); ?>

	<body>
		<div class="main-page-wrapper">

			<!-- ===================================================
				Loading Transition
			==================================================== -->
			<div id="loader-wrapper">
				<div id="loader"></div>
			</div>

			

			<!-- 
			=============================================
				Theme Header Two
			============================================== 
			-->
			<?php $this->loadview('templates/charles/includes/header'); ?>


			<!-- 
			=============================================
				Theme Inner Banner
			============================================== 
			-->
			<div class="theme-inner-banner section-spacing">
				<div class="overlay">
					<div class="container">
						<h1>Saiba a importancia de ter um site para sua empresa</h1>
					</div> <!-- /.container -->
				</div> <!-- /.overlay -->
			</div> <!-- /.theme-inner-banner -->


			<!-- 
			=============================================
				Our Blog
			============================================== 
			-->
			<div class="blog-inner-page section-spacing">
				<div class="container">
					<div class="row">
						<div class="col-xl-9 col-lg-8 col-12 our-blog">
							<div class="post-wrapper">
								
								<div class="single-blog">
									<div class="">
										<a href="<?= TEMPLATE_CHARLES; ?>/images/portfolio/7.jpg" data-fancybox="gallery" class="fancybox">
											<img src="<?=TEMPLATE_CHARLES; ?>/images/blog/9.jpg" style="border-radius: 10px;">
										</a>
										<div class="overlay">
											<a href="javascript:void(0);" class="date" style="padding: 5px 15px; margin: 10px 0;">
												05/05/2022
											</a>
										</div>
									</div> <!-- /.image-box -->
									<div class="post-meta">
										<p>Aqui um breve texto da matéria que você está publicando, na verdade é o inicio do texto ele irá jogar aqui.Aqui um breve texto da matéria que você está publicando, na verdade é o inicio do texto ele irá jogar aqui.</p>
										<p>Aqui um breve texto da matéria que você está publicando, na verdade é o inicio do texto ele irá jogar aqui.Aqui um breve texto da matéria que você está publicando, na verdade é o inicio do texto ele irá jogar aqui.</p>
										<p>Aqui um breve texto da matéria que você está publicando, na verdade é o inicio do texto ele irá jogar aqui.Aqui um breve texto da matéria que você está publicando, na verdade é o inicio do texto ele irá jogar aqui.</p>
										<p>Aqui um breve texto da matéria que você está publicando, na verdade é o inicio do texto ele irá jogar aqui.Aqui um breve texto da matéria que você está publicando, na verdade é o inicio do texto ele irá jogar aqui.</p>
										<p>Aqui um breve texto da matéria que você está publicando, na verdade é o inicio do texto ele irá jogar aqui.Aqui um breve texto da matéria que você está publicando, na verdade é o inicio do texto ele irá jogar aqui.</p>
										<p>Aqui um breve texto da matéria que você está publicando, na verdade é o inicio do texto ele irá jogar aqui.Aqui um breve texto da matéria que você está publicando, na verdade é o inicio do texto ele irá jogar aqui.</p>
										<p>Aqui um breve texto da matéria que você está publicando, na verdade é o inicio do texto ele irá jogar aqui.Aqui um breve texto da matéria que você está publicando, na verdade é o inicio do texto ele irá jogar aqui.</p>
									</div> <!-- /.post-meta -->

								</div> <!-- /.single-blog -->

								<!--FOTOS EXTRAS-->
								<div class="inner-box">
									<div class="row">
										<?php for ($i = 0; $i < 3; $i++) : ?>
										<div class="col-sm-3">
											<a href="<?= TEMPLATE_CHARLES; ?>/images/portfolio/7.jpg" data-fancybox="gallery" class="fancybox">
												<img src="<?= TEMPLATE_CHARLES; ?>/images/portfolio/7.jpg">
											</a>
										</div>
										<?php endfor; ?>
									</div>
								</div>								

							</div> <!-- /.post-wrapper -->

						</div>

						<!-- ===================== Blog Sidebar ==================== -->
						<?php $this->loadview("templates/charles/includes/blog-sidebar"); ?>

					</div> <!-- /.row -->
				</div> <!-- /.container -->
			</div> <!-- /.blog-inner-page -->



			
			<!--
			=====================================================
				Footer
			=====================================================
			-->
			<?php $this->loadview('templates/charles/includes/footer'); ?>			


		<!-- Optional JavaScript _____________________________  -->

    	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    	<!-- jQuery -->
		<?php $this->loadview('templates/charles/includes/scripts'); ?>
		</div> <!-- /.main-page-wrapper -->
	</body>
</html>