<!DOCTYPE html>
<html lang="pt-br">
<?php $this->loadview('templates/charles/includes/head'); ?>

	<body>
		<div class="main-page-wrapper">

			<!-- ===================================================
				Loading Transition
			==================================================== -->
			<div id="loader-wrapper">
				<div id="loader"></div>
			</div>

			

			<!-- 
			=============================================
				Theme Header Two
			============================================== 
			-->
			<?php $this->loadview('templates/charles/includes/header'); ?>


			<!-- 
			=============================================
				Theme Inner Banner
			============================================== 
			-->
			<div class="theme-inner-banner section-spacing">
				<div class="overlay">
					<div class="container">
						<h1>Clientes</h1>
					</div> <!-- /.container -->
				</div> <!-- /.overlay -->
			</div> <!-- /.theme-inner-banner -->

			<!-- 
			=============================================
				Lista de Clientes
			============================================== 
			-->			
			<div class="container">
				<div class="row" style="margin-bottom: 70px;">
					<div class="col-sm-9 col-sm-12">
						<?php for ($i = 0; $i < 9; $i++) : ?>
						<div class="col-sm-4 float-left">
							<div class="single-case-block">
								<a href="https://www.sitedocliente.com.br" target="_blank">
									<img src="<?= TEMPLATE_CHARLES; ?>/images/home/15.jpg">
								</a>
							</div> <!-- /.single-case-block -->
						</div> <!-- /.col- -->
						<?php endfor; ?>
					</div>
				</div> <!-- /.row -->
        	</div> <!-- /.container -->			


			<!--
			=====================================================
				Footer
			=====================================================
			-->
			<?php $this->loadview('templates/charles/includes/footer'); ?>			


		<!-- Optional JavaScript _____________________________  -->

    	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    	<!-- jQuery -->
		<?php $this->loadview('templates/charles/includes/scripts'); ?>
		</div> <!-- /.main-page-wrapper -->
	</body>
</html>