<?php
	$dados["config"] = $config;
	$dados["layout"] = $layout;
	$dados["fraseMotivacional"] = $fraseMotivacional;
	$dados["paginasExtras"] = $paginasExtras;
	$dados["seo"] = $seo;
	$dados["menuTopo"] = $menuTopo;
	$dados["menuFooter"] = $menuFooter;
?>
<!DOCTYPE html>
<html lang="pt-br">
<?php $this->loadview('templates/charles/includes/head',$dados); ?>

<body>
	<div class="main-page-wrapper">

		<!-- ===================================================
				Loading Transition
			==================================================== -->
		<div id="loader-wrapper">
			<div id="loader"></div>
		</div>



		<!-- 
			=============================================
				Theme Header Two
			============================================== 
			-->
		<?php $this->loadview('templates/charles/includes/header',$dados); ?>



		<!--
			=====================================================
				Google Map
			=====================================================
			-->
		<!-- Google Map -->
		<div class="google-map section-spacing" style="width: 100%; text-align: center;">
			<?= $config["google_maps"]; ?>
		</div>


		<!-- 
			=============================================
				Conatct us Section
			============================================== 
			-->
		<div class="contact-us-section">
			<div class="container">
				<div class="theme-title-one">
					<h2><?=$menuPagina; ?></h2>
					<p>Entre em contato conosco e tire suas dúvidas, ou envie suas sugestões.</p>
				</div> <!-- /.theme-title-one -->
				<div class="clearfix main-content no-gutters row">
					<div class="col-sm">
						<div class="form-wrapper">
							<form action="" method="POST" class="theme-form-one" id="form-contato" autocomplete="off" onsubmit="return false;">
								<div class="row">
									<div class="col-sm-6 col-12"><input type="text" placeholder="Nome *" name="nome"></div>
									<div class="col-sm-6 col-12"><input type="text" placeholder="Telefone *" name="telefone"></div>
									<div class="col-sm-6 col-12"><input type="text" placeholder="Email *" name="email"></div>
									<div class="col-sm-6 col-12"><input type="text" placeholder="Assunto *" name="assunto"></div>
									<div class="col-12"><textarea placeholder="Mensagem *" name="mensagem"></textarea></div>
								</div> <!-- /.row -->

								<button class="theme-button-one" id="bt-contato" onclick="enviarContato('<?= $urlAction; ?>','#form-contato');">Enviar Mensagem</button>
								<div id="resposta-contato" style="margin: 10px 0 10px 0; width: 50%;"></div>
							</form>
						</div> <!-- /.form-wrapper -->
					</div> <!-- /.col- -->
				</div> <!-- /.main-content -->
			</div> <!-- /.container -->
		</div>



		<!-- 
			=============================================
				Compnay Branch Address 
			============================================== 
			-->
		<div class="container">
			<div class="row" style="margin: 70px 0 70px 0; width: 100%;">
				<div class="theme-title-one" style="width: 100%; text-align: center;">
					<p style="font-size: 30px;">
						<?= $config["endereco"] ?>
					<p style="margin-top: -20px;">
						<?= $config["horario_funcionamento"] ?>
					</p>
					</p>
				</div> <!-- /.theme-title-one -->
			</div>
		</div> <!-- /.container -->



		<!--
			=====================================================
				Footer
			=====================================================
			-->
		<?php $this->loadview('templates/charles/includes/footer',$dados); ?>

		<!-- jQuery -->
		<?php $this->loadview('templates/charles/includes/scripts'); ?>

		<script>
			function enviarContato(urlServer, idForm) {

				//Recebendo dados do formulário
				var dados = $(idForm).serialize();

				//Desabilita botão
				$("#bt-contato").attr("disabled", true);
				$("#bt-contato").css({
					'cursor': 'default'
				});

				//Muda ícone botão
				$("#bt-contato").html("Aguarde enviado mensagem ...");

				//Enviando dados para o server
				$.ajax({
					url: urlServer,
					cache: false,
					dataType: "json",
					method: "POST",
					data: dados,
					success: function(e) {

						//Habilita botão
						$("#bt-contato").attr("disabled", false);
						$("#bt-contato").css({
							'cursor': 'pointer'
						});

						//Muda ícone botão
						$("#bt-contato").html("Enviar Mensagem");


						//Mensagem cliente de Sucesso
						if (e.tipo == "sucesso") {

							//Mensagem para o usuário
							$("#resposta-contato").html(
								"<div class='alert alert-dismissible alert-success fade show'>" +
								"<button type='button' class='close' data-dismiss='alert'>&times;</button>" +
								e.mensagem +
								"</div>"
							);

							//Limpa o form
							$(idForm).each(function() {
								this.reset();
							});

						}

						//Mensagem cliente de Error
						if (e.tipo == "error") {
							//Mensagem cliente
							$("#resposta-contato").html(
								"<div class='alert alert-dismissible alert-danger fade show'>" +
								"<button type='button' class='close' data-dismiss='alert'>&times;</button>" +
								e.mensagem +
								"</div>"
							);
						}
					}

				});

			}
		</script>

	</div> <!-- /.main-page-wrapper -->
</body>

</html>