<!DOCTYPE html>
<html lang="pt-br">
<?php $this->loadview('templates/charles/includes/head'); ?>

	<body>
		<div class="main-page-wrapper">

			<!-- ===================================================
				Loading Transition
			==================================================== -->
			<div id="loader-wrapper">
				<div id="loader"></div>
			</div>

			

			<!-- 
			=============================================
				Theme Header Two
			============================================== 
			-->
			<?php $this->loadview('templates/charles/includes/header'); ?>



			<!--
			=====================================================
				Google Map
			=====================================================
			-->
			<!-- Google Map -->
			<div class="google-map section-spacing" style="width: 100%; text-align: center;">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d113987.53551447827!2d-48.74816404473613!3d-26.772747876854485!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94d8d3812e92d1ad%3A0xf625ada4d9dce505!2sBalne%C3%A1rio%20Pi%C3%A7arras%20-%20SC!5e0!3m2!1spt-BR!2sbr!4v1651689155871!5m2!1spt-BR!2sbr" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>				
			</div>


			<!-- 
			=============================================
				Conatct us Section
			============================================== 
			-->
			<div class="contact-us-section">
				<div class="container">
					<div class="theme-title-one">
						<h2>FALE CONOSCO</h2>
						<p>Entre em contato conosco e tire suas dúvidas, ou envie suas sugestões.</p>
					</div> <!-- /.theme-title-one -->
					<div class="clearfix main-content no-gutters row">
						<div class="col-sm">
							<div class="form-wrapper">
								<form action="inc/sendemail.php" class="theme-form-one form-validation" autocomplete="off">
									<div class="row">
										<div class="col-sm-6 col-12"><input type="text" placeholder="Nome *" name="nome"></div>
										<div class="col-sm-6 col-12"><input type="text" placeholder="Whatsapp *" name="whatsapp"></div>
										<div class="col-sm-6 col-12"><input type="email" placeholder="Email *" name="email"></div>
										<div class="col-sm-6 col-12"><input type="text" placeholder="Assunto *" name="assunto"></div>
										<div class="col-12"><textarea placeholder="Mensagem" name="mensagem"></textarea></div>
									</div> <!-- /.row -->
									<button class="theme-button-one">ENVIAR MENSAGEM</button>
								</form>
							</div> <!-- /.form-wrapper -->
						</div> <!-- /.col- -->
					</div> <!-- /.main-content -->
				</div> <!-- /.container -->


				<!--Contact Form Validation Markup -->
				<!-- Contact alert -->
				<div class="alert-wrapper" id="alert-success">
					<div id="success">
						<button class="closeAlert"><i class="fa fa-times" aria-hidden="true"></i></button>
						<div class="wrapper">
			               	<p>Mensagem enviada com sucesso.</p>
			             </div>
			        </div>
			    </div> <!-- End of .alert_wrapper -->
			    <div class="alert-wrapper" id="alert-error">
			        <div id="error">
			           	<button class="closeAlert"><i class="fa fa-times" aria-hidden="true"></i></button>
			           	<div class="wrapper">
			               	<p>Desculpe! Problema ao enviar mensagem.</p>
			            </div>
			        </div>
			    </div> <!-- End of .alert_wrapper -->
			</div> <!-- /.contact-us-section -->



			<!-- 
			=============================================
				Compnay Branch Address 
			============================================== 
			-->
				<div class="container">
					<?php for($i=0; $i<2; $i++): ?>
					<div class="row" style="margin: 70px 0 70px 0; width: 100%;">
						<div class="theme-title-one" style="width: 100%; text-align: center;">
							<h2 style="font-size: 40px;">MATRIZ PIÇARRAS</h2>
							<p style="font-size: 30px;">
								<i class="fa fa-address-book-o" aria-hidden="true"></i>
								Rua: Manoel Correa, 996 - Piçarras,SC
							<p style="margin-top: -20px;">
								Seg à Sex das 08:00 às 11:30 e 13:00 às 18:00 / Sáb 08:00 às 12:00
							</p>
							</p>
						</div> <!-- /.theme-title-one -->
					</div>
					<?php endfor; ?>
				</div> <!-- /.container -->


			
			<!--
			=====================================================
				Footer
			=====================================================
			-->
			<?php $this->loadview('templates/charles/includes/footer'); ?>			


		<!-- Optional JavaScript _____________________________  -->

    	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    	<!-- jQuery -->
		<?php $this->loadview('templates/charles/includes/scripts'); ?>
		</div> <!-- /.main-page-wrapper -->
	</body>
</html>