<!DOCTYPE html>
<html lang="pt-br">
<?php $this->loadview('templates/charles/includes/head'); ?>

<body>
	<div class="main-page-wrapper">

		<!-- ===================================================
				Loading Transition
			==================================================== -->
		<div id="loader-wrapper">
			<div id="loader"></div>
		</div>



		<!-- 
			=============================================
				Theme Header Two
			============================================== 
			-->
		<?php $this->loadview('templates/charles/includes/header'); ?>


		<!-- 
			=============================================
				Theme Inner Banner
			============================================== 
			-->
		<div class="theme-inner-banner section-spacing">
			<div class="overlay">
				<div class="container">
					<h1>Dúvidas</h1>
				</div> <!-- /.container -->
			</div> <!-- /.overlay -->
		</div> <!-- /.theme-inner-banner -->


		<!--
			=====================================================
				Faq Page
			=====================================================
			-->
		<div class="faq-page section-spacing">
			<div class="container">
				<div class="theme-title-one">
					<h2>Perguntas e Respostas</h2>
					<p>Dúvidas frequentes dos nossos clientes. Abaixo tente encontrar a sua dúvida, caso não encontre entre em contato conosco.</p>
				</div> <!-- /.theme-title-one -->

				<div class="faq-panel">
					<div class="panel-group theme-accordion" id="accordion">

						<?php for ($i = 0; $i < 15; $i++) : ?>
							<div class="panel">
								<div class="panel-heading">
									<h6 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordion" href="#collapse<?= $i; ?>">
											At Vero Eos Et Accusamus Et Iusto Odio Dignissimos ?</a>
									</h6>
								</div>
								<div id="collapse<?= $i; ?>" class="panel-collapse collapse">
									<div class="panel-body">
										<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
										<p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu.
											vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi.
										</p>
										<a data-fancybox href="https://www.youtube.com/embed/r-AuLm7S3XE?rel=0&amshowinfo=0" class="theme-button-one" style="margin-top: 20px;">
											vídeo da dúvida
										</a>
									</div>
								</div>
							</div> <!-- /panel-->
						<?php endfor; ?>

					</div> <!-- end #accordion -->
				</div> <!-- /.faq-panel -->
			</div> <!-- /.container -->
		</div> <!-- /.faq-page -->


		<!--
			=====================================================
				Footer
			=====================================================
			-->
		<?php $this->loadview('templates/charles/includes/footer'); ?>


		<!-- Optional JavaScript _____________________________  -->

		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<!-- jQuery -->
		<?php $this->loadview('templates/charles/includes/scripts'); ?>
	</div> <!-- /.main-page-wrapper -->
</body>

</html>