<?php
	$dados["config"] = $config;
	$dados["layout"] = $layout;
	$dados["fraseMotivacional"] = $fraseMotivacional;
	$dados["paginasExtras"] = $paginasExtras;
	$dados["seo"] = $seo;
	$dados["menuTopo"] = $menuTopo;
	$dados["menuFooter"] = $menuFooter;
	$dados["menuTopo"] = $menuTopo;
	$dados["menuFooter"] = $menuFooter;
?>
<!DOCTYPE html>
<html lang="pt-br">
<?php $this->loadview('templates/charles/includes/head',$dados); ?>

<body>
	<div class="main-page-wrapper">

		<!-- ===================================================
				Loading Transition
			==================================================== -->
		<div id="loader-wrapper">
			<div id="loader"></div>
		</div>



		<!-- 
			=============================================
				Theme Header Two
			============================================== 
			-->
		<?php $this->loadview('templates/charles/includes/header',$dados); ?>


		<!-- 
			=============================================
				Theme Inner Banner
			============================================== 
			-->
		<div class="theme-inner-banner section-spacing">
			<div class="overlay">
				<div class="container">
					<h1><?=$menuPagina; ?></h1>
				</div> <!-- /.container -->
			</div> <!-- /.overlay -->
		</div> <!-- /.theme-inner-banner -->


		<!--
			=====================================================
				Faq Page
			=====================================================
			-->
		<div class="faq-page section-spacing">
			<div class="container">
				<div class="theme-title-one">
					<h2>Perguntas e Respostas</h2>
					<p>Dúvidas frequentes dos nossos clientes. Abaixo tente encontrar a sua dúvida, caso não encontre entre em contato conosco.</p>
				</div> <!-- /.theme-title-one -->

				<div class="faq-panel">
					<div class="panel-group theme-accordion" id="accordion">

						<?php foreach($duvidas as $i => $valor) : ?>
							<div class="panel">
								<div class="panel-heading">
									<h6 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordion" href="#collapse<?= $i; ?>">
											<?=$valor["titulo"]; ?></a>
									</h6>
								</div>
								<div id="collapse<?= $i; ?>" class="panel-collapse collapse">
									<div class="panel-body">
										<p><?=nl2br($valor["texto"]); ?></p>
										<div class="row" style="margin-top: 10px;">
											<?php foreach ($valor["galeria"] as $imagem) : ?>
											<div style="width: 22%; float: left; position: relative; margin: 10px;">
												<a href="<?= STATIC_URL; ?>/img/duvidas/<?=$valor["dir_galeria"];?>/thumb1200_<?=$imagem; ?>" data-fancybox="gallery-<?=$i;?>" class="fancybox">
													<img src="<?= STATIC_URL; ?>/img/duvidas/<?=$valor["dir_galeria"];?>/thumb300_<?=$imagem; ?>">
												</a>
											</div>
											<?php endforeach; ?>
										</div>
										<?php if(!empty($valor["url"])): ?>										
										<a data-fancybox href="<?=$valor["url"]; ?>" class="theme-button-one" style="margin-top: 20px;">
											vídeo da dúvida
										</a>
										<?php endif; ?>
									</div>
								</div>
							</div> <!-- /panel-->
						<?php endforeach; ?>

					</div> <!-- end #accordion -->
				</div> <!-- /.faq-panel -->
			</div> <!-- /.container -->
		</div> <!-- /.faq-page -->


		<!--
			=====================================================
				Footer
			=====================================================
			-->
		<?php $this->loadview('templates/charles/includes/footer',$dados); ?>


		<!-- Optional JavaScript _____________________________  -->

		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<!-- jQuery -->
		<?php $this->loadview('templates/charles/includes/scripts'); ?>
	</div> <!-- /.main-page-wrapper -->
</body>

</html>