<!DOCTYPE html>
<html lang="pt-br">
<?php $this->loadview('templates/charles/includes/head'); ?>

<body>
	<div class="main-page-wrapper">

		<!-- ===================================================
				Loading Transition
			==================================================== -->
		<div id="loader-wrapper">
			<div id="loader"></div>
		</div>



		<!-- 
			=============================================
				Theme Header Two
			============================================== 
			-->
		<?php $this->loadview('templates/charles/includes/header'); ?>


		<!-- 
			=============================================
				Theme Inner Banner
			============================================== 
			-->
		<div class="theme-inner-banner">
			<div class="overlay">
				<div class="container">
					<h1>Conheça a Querosite.digital</h1>
				</div> <!-- /.container -->
			</div> <!-- /.overlay -->
		</div> <!-- /.theme-inner-banner -->


		<!-- 
			=============================================
				CallOut Banner 
			============================================== 
			-->
		<div class="callout-banner callout-banner-institucional no-bg">
			<div class="container clearfix">
				<h3 class="title">High-Quality <br> Market Experinces</h3>
				<p>A tale of a fateful trip that started from this tropic port aboard this tiny ship today still wanted by the government they survive as soldiers of fortune to ever wondered the east side to a deluxe apartment.</p>
				<a href="<?= SITE_URL; ?>/contato" class="theme-button-one">FALE CONOSCO</a>
			</div>
		</div> <!-- /.callout-banner -->



		<!-- 
			=============================================
				About Company Stye Two
			============================================== 
			-->
		<div class="about-compnay no-bg section-spacing">
			<div class="overlay">
				<div class="container">
					<div class="row">
						<div class="col-lg-6 col-12 text order-lg-last">
							<div class="theme-title-one">
								<h2>DETALHES NOME DO PRODUTO</h2>
							</div> <!-- /.theme-title-one -->
							<div class="texto-plugin" style="text-align: justify;">
								<p>A tale of a fateful trip that started from this tropic port aboard this tiny ship today still wanted by the government they survive as soldiers of fortune to a deluxe you apartment in the sky to explore strange new worlds to seek out new life and new civilizations to boldly go where no man has gone.</p>
								<p>A tale of a fateful trip that started from this tropic port aboard this tiny ship today still wanted by the government they survive as soldiers of fortune to a deluxe you apartment in the sky to explore strange new worlds to seek out new life and new civilizations to boldly go where no man has gone.</p>
								<p>A tale of a fateful trip that started from this tropic port aboard this tiny ship today still wanted by the government they survive as soldiers of fortune to a deluxe you apartment in the sky to explore strange new worlds to seek out new life and new civilizations to boldly go where no man has gone.</p>
							</div>
						</div> <!-- /.col- -->
						<div class="col-sm order-lg-first imagem-company">
							<a href="<?= TEMPLATE_CHARLES; ?>/images/portfolio/7.jpg" data-fancybox="gallery" class="fancybox">
								<img src="<?= TEMPLATE_CHARLES; ?>/images/home/16.jpg">
							</a>
							<div class="wrapper" style="margin: 10px 0 0 0;">
								<div class="row">
									<?php for ($i = 0; $i < 4; $i++) : ?>
										<div class="col-3">
											<a href="<?= TEMPLATE_CHARLES; ?>/images/portfolio/7.jpg" data-fancybox="gallery" class="fancybox">
												<img src="<?= TEMPLATE_CHARLES; ?>/images/portfolio/7.jpg">
											</a>
										</div>
									<?php endfor; ?>
								</div>
							</div>
						</div>
					</div> <!-- /.row -->
				</div> <!-- /.container -->
			</div> <!-- /.overlay -->
		</div> <!-- /.about-compnay-two -->


		<!--
			=====================================================
				Why We Best
			=====================================================
			-->
		<div class="why-we-best">
			<div class="overlay">
				<div class="container">
					<div class="theme-title-one">
						<h2 class="titulo-missao">NOSSOS VALORES</h2>
						<p class="titulo-missao">Toda empresa é formada por seus valores, conheça abaixo os nossos</p>
					</div> <!-- /.theme-title-one -->

					<div class="wrapper row no-gutters">
						<div class="col-lg-6 col-12 order-lg-last">
							<div class="img-box">
								<a data-fancybox href="https://www.youtube.com/embed/r-AuLm7S3XE?rel=0&amshowinfo=0">
									<img src="<?= TEMPLATE_CHARLES; ?>/images/home/16.jpg">
								</a>
							</div>
						</div>
						<div class="col-lg-6 col-12 order-lg-first">
							<ul class="best-list-item">
								<li>
									<i class="icon flaticon-puzzle"></i>
									<h5 class="cor-m-v-v">MISSÃO</h5>
									<p class="cor-m-v-v">The Love Boat soon will be making another run plore strange tools enter new worlds.</p>
								</li>
								<li>
									<i class="icon flaticon-technology"></i>
									<h5 class="cor-m-v-v">VISÃO</h5>
									<p class="cor-m-v-v"> The Love Boat soon will be making another run plore strange tools enter new worlds.</p>
								</li>
								<li>
									<i class="icon flaticon-medal"></i>
									<h5 class="cor-m-v-v">VALORES</h5>
									<p class="cor-m-v-v">The Love Boat soon will be making another run plore strange tools enter new worlds.</p>
								</li>
							</ul>
						</div> <!-- /.col- -->
					</div> <!-- /.wrapper -->
				</div> <!-- /.container -->
			</div> <!-- /.overlay -->
		</div> <!-- /.why-we-best -->


		<!--
			=====================================================
				Theme Counter
			=====================================================
			-->
		<div class="theme-counter-two section-spacing">
			<div class="container">
				<div class="clearfix">
					<div class="cunter-wrapper">
						<div class="row">
							<div class="col-md-3 col-6">
								<div class="single-counter-box">
									<div class="number"><span class="timer" data-from="0" data-to="15" data-speed="1200" data-refresh-interval="5">0</span>+</div>
									<p>Anos de experiência</p>
								</div> <!-- /.single-counter-box -->
							</div> <!-- /.col- -->
							<div class="col-md-3 col-6">
								<div class="single-counter-box">
									<div class="number"><span class="timer" data-from="0" data-to="135" data-speed="1200" data-refresh-interval="5">0</span></div>
									<p>Sites Entregues</p>
								</div> <!-- /.single-counter-box -->
							</div> <!-- /.col- -->
							<div class="col-md-3 col-6">
								<div class="single-counter-box">
									<div class="number"><span class="timer" data-from="0" data-to="1554" data-speed="1200" data-refresh-interval="5">0</span></div>
									<p>Jobs Digitais Realizados</p>
								</div> <!-- /.single-counter-box -->
							</div> <!-- /.col- -->
							<div class="col-md-3 col-6">
								<div class="single-counter-box">
									<div class="number"><span class="timer" data-from="0" data-to="245" data-speed="1200" data-refresh-interval="5">0</span></div>
									<p>Clientes Satisfeitos</p>
								</div> <!-- /.single-counter-box -->
							</div> <!-- /.col- -->
						</div> <!-- /.row -->
					</div> <!-- /.cunter-wrapper -->
				</div> <!-- /.clearfix -->
			</div> <!-- /.container -->
		</div> <!-- /.theme-counter -->

		<div class="our-case section-spacing">
			<div class="container">
				<div class="view-all">
					<a href="<?=SITE_URL; ?>/equipe" class="theme-button-one">Conheça nossa Equipe</a>
				</div>
			</div>
		</div>

		<!--
			=====================================================
				Footer
			=====================================================
			-->
		<?php $this->loadview('templates/charles/includes/footer'); ?>


		<!-- Optional JavaScript _____________________________  -->

		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<!-- jQuery -->
		<?php $this->loadview('templates/charles/includes/scripts'); ?>
	</div> <!-- /.main-page-wrapper -->
</body>

</html>