<!DOCTYPE html>
<html lang="pt-br">
<?php $this->loadview('templates/charles/includes/head'); ?>

<body>
	<div class="main-page-wrapper">

		<!-- ===================================================
				Loading Transition
			==================================================== -->
		<div id="loader-wrapper">
			<div id="loader"></div>
		</div>



		<!-- 
			=============================================
				Theme Header Two
			============================================== 
			-->
		<?php $this->loadview('templates/charles/includes/header'); ?>


		<!-- 
			=============================================
				Theme Inner Banner
			============================================== 
			-->
		<div class="theme-inner-banner section-spacing">
			<div class="overlay">
				<div class="container">
					<h1>Equipe</h1>
				</div> <!-- /.container -->
			</div> <!-- /.overlay -->
		</div> <!-- /.theme-inner-banner -->



		<!--
			=====================================================
				Our Team
			=====================================================
			-->
		<div class="our-team section-spacing">
			<div class="container">
				<div class="wrapper">
					<div class="row">
						<?php for ($i = 0; $i < 10; $i++) : ?>
							<div class="col-lg-3 col-sm-6 col-12">
								<div class="team-member">
									<div class="image-box">
										<img src="<?= TEMPLATE_CHARLES; ?>/images/team/1.jpg" alt="João Ricardo Provezi">
										<div class="overlay">
											<div class="hover-content">
												<ul>
													<li>
														<a href="javascript:void(0);" data-toggle="modal" data-target="#modal-<?= $i; ?>">+</a>
													</li>
												</ul>
												<p>The government they survive as soldiers of fortune.</p>
											</div> <!-- /.hover-content -->
										</div> <!-- /.overlay -->
									</div> <!-- /.image-box -->
									<div class="text">
										<h6>Richards Mills</h6>
										<span>Sales Consultant</span>
									</div> <!-- /.text -->
								</div> <!-- /.team-member -->
							</div> <!-- /.col- -->

							<!-- Modal -->
							<div class="modal fade" id="modal-<?= $i; ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
								<div class="modal-dialog modal-dialog-centered" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<h5 class="modal-title" id="exampleModalLongTitle">Nome Completo</h5>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										</div>
										<div class="modal-body" style="text-align: justify;">
											<img src="<?= TEMPLATE_CHARLES; ?>/images/team/1.jpg" alt="Nome do colaborador" class="imagem-modal">
											Aqui o texto falando do membro da equipe. Aqui o texto falando do membro da equipe. Aqui o texto falando do membro da equipe. 
											Aqui o texto falando do membro da equipe. vAqui o texto falando do membro da equipe. Aqui o texto falando do membro da equipe. 
										</div>
										<div class="modal-footer">
											<button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
										</div>
									</div>
								</div>
							</div>


						<?php endfor; ?>
					</div> <!-- /.row -->
				</div> <!-- /.wrapper -->
			</div> <!-- /.container -->
		</div> <!-- /.our-team -->




		<!--
			=====================================================
				Footer
			=====================================================
			-->
		<?php $this->loadview('templates/charles/includes/footer'); ?>


		<!-- Optional JavaScript _____________________________  -->

		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<!-- jQuery -->
		<?php $this->loadview('templates/charles/includes/scripts'); ?>
	</div> <!-- /.main-page-wrapper -->
</body>

</html>