<?php
$dados["nomeControlador"] = $nomeControlador;
?>
<!DOCTYPE html>
<html lang="pt-br">
<?php $this->loadview('templates/charles/includes/head'); ?>

<body>
	<div class="main-page-wrapper">

		<!-- ===================================================
				Loading Transition
			==================================================== -->
		<div id="loader-wrapper">
			<div id="loader"></div>
		</div>



		<!-- 
			=============================================
				Theme Header Two
			============================================== 
			-->
		<?php $this->loadview('templates/charles/includes/header'); ?>


		<!-- 
			=============================================
				Theme Inner Banner
			============================================== 
			-->
		<div class="theme-inner-banner section-spacing">
			<div class="overlay">
				<div class="container">
					<h1>NOME DO ITEM</h1>
				</div> <!-- /.container -->
			</div> <!-- /.overlay -->
		</div> <!-- /.theme-inner-banner -->


			<!-- 
			=============================================
				Detalhes do item
			============================================== 
			-->
			<div class="project-details section-spacing">
				<div class="container">
					<div class="row">
						<div class="col-xl-4 col-lg-5 col-md-6 col-12 project-details-sidebar order-md-last">
							<div class="strategies" style="text-align: justify;">
								<p>A tale of a fateful trip that started from this tropic port aboard this tiny ship today still wanted by the government  apartment in the sky moving on up to the east side a family to explore strange to seek out new life and new civilizations.</p>
								<p>Boldly go where no man has gone before you would see the biggest gift would be from me and the card attached would say thank you.</p>
								<p>Boldly go where no man has gone before you would see the biggest gift would be from me and the card attached would say thank you.</p>
								<p>Boldly go where no man has gone before you would see the biggest gift would be from me and the card attached would say thank you.</p>
							</div>

							<!--BOTÃO VIDEO-->
							<div class="row" style="text-align: center; width: 100%; margin: 20px 0 40px 0;">
								<div class="col-12">
									<div>
										<a data-fancybox href="https://www.youtube.com/embed/r-AuLm7S3XE?rel=0&amshowinfo=0" class="theme-button-one">
											Carregar VÍDEO <i class="fa fa-youtube" aria-hidden="true"></i>
										</a>
									</div>
								</div>
							</div>
							
							<div class="container">
										<hr>
										<span style="font-size: 20px;">VALOR: <strong>R$ 399,00</strong></span>
										<hr>
										<img src="<?= TEMPLATE_CHARLES; ?>/images/shop/mercado-pago.jpg">
										<hr>
										<div class="view-all">
											<a href="javascript:void(0);" data-toggle="modal" data-target="#modal-pagamento" class="botao-pagamento theme-button-one">COMPRAR</a>
										</div>

										<!-- Modal -->
										<div class="modal fade" id="modal-pagamento" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
											<div class="modal-dialog modal-dialog-centered" role="document">
												<div class="modal-content">
													<div class="modal-header">
														<h5 class="modal-title" id="exampleModalLongTitle">CHECKOUT DE PAGAMENTO</h5>
														<button type="button" class="close" data-dismiss="modal" aria-label="Close">
															<span aria-hidden="true">&times;</span>
														</button>
													</div>
													<div class="modal-body" style="text-align: justify;">
														<p style="margin-bottom: 20px;">Insira seus dados de identificação antes de efetuar o pagamento!</p>
														<form action="" class="theme-form-one form-validation" autocomplete="off">
															<div class="row">
																<div class="col-sm-12 col-12"><input type="text" placeholder="Nome completo *" name="nome"></div>
																<div class="col-sm-6 col-12"><input type="text" placeholder="Whatsapp *" name="whatsapp"></div>
																<div class="col-sm-6 col-12"><input type="email" placeholder="Email *" name="email"></div>
															</div> <!-- /.row -->
														</form>
													</div>
													<div class="modal-footer">
														<button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
														<a href="https://mpago.la/1QCpNv9" class="theme-button-one botao-pagamento">EFETUAR PAGAMENTO</a>
													</div>
												</div>
											</div>
										</div>

									</div>							

						</div> <!-- /.project-details-sidebar -->
						<div class="col-xl-8 col-lg-7 col-md-6 col-12 order-md-first image-col">
						<a href="<?= TEMPLATE_CHARLES; ?>/images/portfolio/7.jpg" data-fancybox="gallery" class="fancybox">
							<img src="<?=TEMPLATE_CHARLES;?>/images/portfolio/16.jpg">
						</a>
						<a href="<?= TEMPLATE_CHARLES; ?>/images/portfolio/7.jpg" data-fancybox="gallery" class="fancybox">
							<img src="<?=TEMPLATE_CHARLES;?>/images/portfolio/17.jpg">
						</a>
						<a href="<?= TEMPLATE_CHARLES; ?>/images/portfolio/7.jpg" data-fancybox="gallery" class="fancybox">
							<img src="<?=TEMPLATE_CHARLES;?>/images/portfolio/18.jpg">
						</a>
						</div>
					</div> <!-- /.row -->
				</div> <!-- /.container -->
			</div> <!-- /.project-details -->

		

		<!--
			=====================================================
				Outros itens
			=====================================================
			-->
		<?php $this->loadview('templates/charles/includes/outros-itens',$dados); ?>



		<!--
			=====================================================
				Footer
			=====================================================
			-->
		<?php $this->loadview('templates/charles/includes/footer'); ?>


		<!-- Optional JavaScript _____________________________  -->

		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<!-- jQuery -->
		<?php $this->loadview('templates/charles/includes/scripts'); ?>
	</div> <!-- /.main-page-wrapper -->
</body>

</html>