<!DOCTYPE html>
<html lang="pt-br">
<?php $this->loadview('templates/charles/includes/head'); ?>

<body>
	<div class="main-page-wrapper">

		<!-- ===================================================
				Loading Transition
			==================================================== -->
		<div id="loader-wrapper">
			<div id="loader"></div>
		</div>



		<!-- 
			=============================================
				Theme Header Two
			============================================== 
			-->
		<?php $this->loadview('templates/charles/includes/header'); ?>


		<!-- 
			=============================================
				Theme Inner Banner
			============================================== 
			-->
		<div class="theme-inner-banner section-spacing">
			<div class="overlay">
				<div class="container">
					<h1>NOME DA PÁGINA</h1>
				</div> <!-- /.container -->
			</div> <!-- /.overlay -->
		</div> <!-- /.theme-inner-banner -->


		<!-- 
			=============================================
				detalhe produtos
			============================================== 
			-->
		<div class="about-compnay no-bg section-spacing detalhe-produtos">
			<div class="overlay">
				<div class="container">
					<div class="row">
						<!--<div class="col-lg-6 col-12 text order-lg-last">-->
						<div class="col-lg-12 col-12 text">
							<div class="texto-plugin" style="text-align: justify;">
								<p>
									Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
									The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
								</p>
							</div>
						</div>


						<div class="col-sm-12">
							<div class="wrapper" style="margin: 20px 0 0 0;">
								<div class="row">
									<?php for ($i = 0; $i < 8; $i++) : ?>
										<div class="col-sm-3">
											<a href="<?= TEMPLATE_CHARLES; ?>/images/portfolio/7.jpg" data-fancybox="gallery" class="fancybox">
												<img src="<?= TEMPLATE_CHARLES; ?>/images/portfolio/7.jpg">
											</a>
										</div>
									<?php endfor; ?>
								</div>
							</div>
						</div>

						<!--BOTÃO VIDEO-->
						<div class="row" style="text-align: center; width: 100%; margin-top: 20px;">
							<div class="col-12">
								<div>
									<a data-fancybox href="https://www.youtube.com/embed/r-AuLm7S3XE?rel=0&amshowinfo=0" class="theme-button-one">
										Carregar VÍDEO <i class="fa fa-youtube" aria-hidden="true"></i>
									</a>
								</div>
							</div>
						</div>




					</div> <!-- /.row -->
				</div> <!-- /.container -->
			</div> <!-- /.overlay -->
		</div> <!-- /.about-compnay-two -->

		<!--
			=====================================================
				Footer
			=====================================================
			-->
		<?php $this->loadview('templates/charles/includes/footer'); ?>


		<!-- Optional JavaScript _____________________________  -->

		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<!-- jQuery -->
		<?php $this->loadview('templates/charles/includes/scripts'); ?>
	</div> <!-- /.main-page-wrapper -->
</body>

</html>