<?php
	$dados["config"] = $config;
	$dados["layout"] = $layout;
	$dados["fraseMotivacional"] = $fraseMotivacional;
	$dados["paginasExtras"] = $paginasExtras;
	$dados["seo"] = $seo;
	$dados["menuTopo"] = $menuTopo;
	$dados["menuFooter"] = $menuFooter;
?>
<!DOCTYPE html>
<html lang="pt-br">
<?php $this->loadview('templates/charles/includes/head',$dados); ?>

<body>
	<div class="main-page-wrapper">

		<!-- ===================================================
				Loading Transition
			==================================================== -->
		<div id="loader-wrapper">
			<div id="loader"></div>
		</div>



		<!-- 
			=============================================
				Theme Header Two
			============================================== 
			-->
		<?php $this->loadview('templates/charles/includes/header',$dados); ?>


		<!-- 
			=============================================
				Theme Inner Banner
			============================================== 
			-->
		<div class="theme-inner-banner section-spacing">
			<div class="overlay">
				<div class="container">
					<h1><?=$paginaExtra["titulo"]; ?></h1>
				</div> <!-- /.container -->
			</div> <!-- /.overlay -->
		</div> <!-- /.theme-inner-banner -->


		<!-- 
			=============================================
				detalhe produtos
			============================================== 
			-->
		<div class="about-compnay no-bg section-spacing detalhe-produtos">
			<div class="overlay">
				<div class="container">
					<div class="row">
						<!--<div class="col-lg-6 col-12 text order-lg-last">-->
						<div class="col-sm-12">
							<?=$documento; ?>
						</div>

						<div class="col-sm-12" style="margin-top: 70px;">
							<div class="wrapper" style="margin: 20px 0 0 0;">
								<div class="row">
								<?php foreach ($galeria as $valor) : ?>
										<div class="col-sm-3">
											<a href="<?= Common::getImg("paginas-extras/{$paginaExtra['dir_galeria']}/thumb1200_{$valor}", "blog"); ?>" data-fancybox="gallery" class="fancybox">
												<img src="<?= Common::getImg("paginas-extras/{$paginaExtra['dir_galeria']}/thumb550_{$valor}", "blog"); ?>">
											</a>
										</div>
									<?php endforeach; ?>
								</div>
							</div>
						</div>

					</div> <!-- /.row -->
				</div> <!-- /.container -->
			</div> <!-- /.overlay -->
		</div> <!-- /.about-compnay-two -->

		<!--
			=====================================================
				Footer
			=====================================================
			-->
		<?php $this->loadview('templates/charles/includes/footer',$dados); ?>


		<!-- Optional JavaScript _____________________________  -->

		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<!-- jQuery -->
		<?php $this->loadview('templates/charles/includes/scripts'); ?>
	</div> <!-- /.main-page-wrapper -->
</body>

</html>