<?php
$dados["config"] = $config;
$dados["layout"] = $layout;
$dados["fraseMotivacional"] = $fraseMotivacional;
$dados["paginasExtras"] = $paginasExtras;
$dados["seo"] = $seo;
$dados["menuTopo"] = $menuTopo;
$dados["menuFooter"] = $menuFooter;
?>
<!DOCTYPE html>
<html lang="pt-br">
<?php $this->loadview('templates/charles/includes/head', $dados); ?>

<body>
	<div class="main-page-wrapper">

		<!-- ===================================================
				Loading Transition
			==================================================== -->
		<div id="loader-wrapper">
			<div id="loader"></div>
		</div>



		<!-- 
			=============================================
				Theme Header Two
			============================================== 
			-->
		<?php $this->loadview('templates/charles/includes/header', $dados); ?>


		<!-- 
			=============================================
				Theme Inner Banner
			============================================== 
			-->
		<div class="theme-inner-banner section-spacing">
			<div class="overlay">
				<div class="container">
					<h1><?= $menuPagina; ?></h1>
				</div> <!-- /.container -->
			</div> <!-- /.overlay -->
		</div> <!-- /.theme-inner-banner -->


		<!-- 
			=============================================
				Serviços / Produtos
			============================================== 
			-->
		<div class="our-case section-spacing">
			<div class="container">
				<div class="wrapper">
					<div class="row">
						<?php if (count($categorias) >= 1) : ?>
							<div class="col-sm-12 theme-sidebar-one">
								<div class="sidebar-box service-categories">
									<ul>
										<li class="col-sm-4 float-left <?=($busca == "") ? "active" : ""; ?>">
											<a href="<?=$urlAction;?>">Todos</a>
										</li>
										<?php foreach($categorias as $valor): ?>
										<li class="col-sm-4 float-left <?=($busca == $valor["id"]) ? "active" : ""; ?>">
											<a href="<?=$urlAction."/".$valor["id"];?>"><?=$valor["titulo"]; ?></a>
										</li>
										<?php endforeach; ?>
									</ul>
								</div> <!-- /.service-categories -->
							</div>
						<?php endif; ?>
						<div class="col-sm-9 col-sm-12">
							<?php foreach ($projetos as $i => $valor) : ?>
								<div class="col-sm-4 float-left" style="min-height: 500px;">
									<div class="single-case-block">
										<a href="<?= SITE_URL; ?>/<?= Common::slug($valor["titulo"]); ?>">
											<img src="<?= Common::getImg("projetos/{$valor['dir_galeria']}/thumb550_{$valor['capa']}", "blog"); ?>">
										</a>

										<div class="col-sm-12 float-left" style="min-height: 60px;">
											<a href="<?= SITE_URL; ?>/<?= Common::slug($valor["titulo"]); ?>">
												<h5><?=Common::reduzirTexto($valor["titulo"],100); ?> </h5>
											</a>
										</div>
									</div> <!-- /.single-case-block -->
								</div> <!-- /.col- -->
							<?php endforeach; ?>
						</div>

						<?php if (count($pageView) >= 2) : ?>
						<div class="theme-pagination" style="margin-left: 25px;">
							<ul>
								<?php foreach ($pageView as $valor) : ?>
									<li <?= $valor["active"]; ?>><a href="<?= $valor["url"]; ?>">
											<?= $valor["page_number"]; ?></a>
									</li>
								<?php endforeach; ?>
							</ul>
						</div>
						<?php endif; ?>						

					</div> <!-- /.row -->
				</div> <!-- /.wrapper -->
			</div> <!-- /.container -->
		</div> <!-- /.our-case -->


		<!--
			=====================================================
				Footer
			=====================================================
			-->
		<?php $this->loadview('templates/charles/includes/footer',$dados); ?>


		<!-- Optional JavaScript _____________________________  -->

		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<!-- jQuery -->
		<?php $this->loadview('templates/charles/includes/scripts', $dados); ?>
	</div> <!-- /.main-page-wrapper -->
</body>

</html>