<?php
$dados["config"] = $config;
$dados["layout"] = $layout;
$dados["seo"] = $seo;
$dados["menuTopo"] = $menuTopo;
$dados["menuFooter"] = $menuFooter;
?>
<!DOCTYPE html>
<html lang="pt-br">
<?php $this->loadview('templates/charles/includes/head', $dados); ?>
<style>
    body{
        background-color:#0b0b0b !important;
    }
	.error-page{
		margin-top: 100px;
		text-align: center;
	}

	.error-page img{
		margin: auto;
  		display: block;
	}
	p{
	    color:#fff !important;
	}

</style>

<body>
	<div class="main-page-wrapper">

		<!-- ===================================================
				Loading Transition
			==================================================== -->
		<div id="loader-wrapper">
			<div id="loader"></div>
		</div>



		<!-- 
			=============================================
				Theme Header Two
			============================================== 
			-->
		<?php //$this->loadview('templates/charles/includes/header', $dados); ?>

		<!-- 
			=============================================
				Error Page 
			============================================== 
			-->
		<!--<div class="container error-page">
			<img src="<?//= STATIC_URL; ?>/img/sistema/<?//=$config["dir_galeria"]."/thumb450_".$config["capa"]; ?>">
			<p><?//=$config["frase_site_construcao"]; ?></p>
		</div> -->
		
		<div style="position: relative; width: 100%; height: 0; padding-top: 56.2500%;
 padding-bottom: 0; box-shadow: 0 2px 8px 0 rgba(63,69,81,0.16); margin-top: 1.6em; margin-bottom: 0.9em; overflow: hidden;
 border-radius: 8px; will-change: transform;">
  <iframe loading="lazy" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0; border: none; padding: 0;margin: 0;"
    src="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGAiE9nUZM&#x2F;QFmgrTb5aBvxr10YKIzReQ&#x2F;view?embed" allowfullscreen="allowfullscreen" allow="fullscreen">
  </iframe>
</div>
<a href="https:&#x2F;&#x2F;www.canva.com&#x2F;design&#x2F;DAGAiE9nUZM&#x2F;QFmgrTb5aBvxr10YKIzReQ&#x2F;view?utm_content=DAGAiE9nUZM&amp;utm_campaign=designshare&amp;utm_medium=embeds&amp;utm_source=link" target="_blank" rel="noopener">Apresentação J6 Softwares para Internet</a> de Jota Provezi


		<!-- Optional JavaScript _____________________________  -->

		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<!-- jQuery -->
		<?php $this->loadview('templates/charles/includes/scripts'); ?>
	</div> <!-- /.main-page-wrapper -->
</body>

</html>