<!DOCTYPE html>
<html lang="pt-br">
<?php $this->loadview('templates/charles/includes/head'); ?>

	<body>
		<div class="main-page-wrapper">

			<!-- ===================================================
				Loading Transition
			==================================================== -->
			<div id="loader-wrapper">
				<div id="loader"></div>
			</div>

			

			<!-- 
			=============================================
				Theme Header Two
			============================================== 
			-->
			<?php $this->loadview('templates/charles/includes/header'); ?>


			<!-- 
			=============================================
				Theme Inner Banner
			============================================== 
			-->
			<div class="theme-inner-banner section-spacing">
				<div class="overlay">
					<div class="container">
						<h1>Conheça a Querosite.digital</h1>
					</div> <!-- /.container -->
				</div> <!-- /.overlay -->
			</div> <!-- /.theme-inner-banner -->



			
			<!--
			=====================================================
				Footer
			=====================================================
			-->
			<?php $this->loadview('templates/charles/includes/footer'); ?>			


		<!-- Optional JavaScript _____________________________  -->

    	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    	<!-- jQuery -->
		<?php $this->loadview('templates/charles/includes/scripts'); ?>
		</div> <!-- /.main-page-wrapper -->
	</body>
</html>