<?php
$dados["notificacoes"] = $notificacoes;
$dados["totalNotificacoesNaoLidas"] = $totalNotificacoesNaoLidas;
?>
<!doctype html>
<html lang="pt-br">
<!--HEAD + CSS-->
<?= $this->loadview('admin/includes/head'); ?>

<body>
    <!--TOPO + MENU-->
    <?= $this->loadview('admin/includes/header', $dados); ?>

    <!--CONTEÚDO-->
    <div class="wrapper">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-md-8">

                                <ol class="breadcrumb">
                                    <?php foreach ($breadcrumb as $indice => $valor) : ?>
                                        <?php if (!empty($valor["url"])) : ?>
                                            <li class="breadcrumb-item"><a href="<?= $valor["url"]; ?>"><?= $valor["nome"]; ?></a></li>
                                        <?php else : ?>
                                            <li class="breadcrumb-item active"><a><?= $valor["nome"]; ?></a></li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ol>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-body">

                            <!--Conteúdo-->
                            <section>
                                <form id="cadastroForm" enctype="multipart/form-data" action="" onsubmit="return false;">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="card border-light mb-3">
                                                    <div class="card-header">Dados do Menu</div>
                                                    <div class="card-body">
                                                        <div class="input-group mb-3">
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Nome do Menu">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-align-justify"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Nome do Menu *" id="nome" name="nome" value="<?= $dadosBanco["nome"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Ícone do menu">
                                                                        <span class="input-group-text">
                                                                            <i class="fab fa-fonticons-fi" id="icone-lista"></i>
                                                                        </span>
                                                                    </div>
                                                                    <select name="icone" class="custom-select" id="icone" onchange="javascript:mudarIcone(this.value);">
                                                                        <?php foreach($icones as $indice => $valor):?>
                                                                            <option value="<?=$valor["nome"]; ?>" <?= ($dadosBanco["icone"] == $valor["nome"]) ? "selected" : ""; ?>>
                                                                                <?=$valor["id"]; ?> : <?=$valor["nome"]; ?>
                                                                            </option>
                                                                        <?php endforeach; ?>
                                                                    </select>
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Url da rota do projeto">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-link"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Url *" id="url" name="url" value="<?= $dadosBanco["url"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="nome do controlador">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-code"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Controller *" id="controller" name="controller" value="<?= $dadosBanco["controller"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Posição do menu no sistema">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-cubes"></i>
                                                                        </span>
                                                                    </div>
                                                                    <select name="categoria" class="custom-select" id="categoria">
                                                                        <option value="" <?= ($dadosBanco["categoria"] == "") ? "selected" : ""; ?>></option>
                                                                        <option value="config" <?= ($dadosBanco["categoria"] == "config") ? "selected" : ""; ?>>Config</option>
                                                                        <option value="pai" <?= ($dadosBanco["categoria"] == "pai") ? "selected" : ""; ?>>Pai</option>
                                                                        <option value="unico" <?= ($dadosBanco["categoria"] == "unico") ? "selected" : ""; ?>>Único</option>
                                                                    </select>
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-3">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Se inserir um Id Pai, o menu será filho dele">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-sort-numeric-up"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Id menu Filho" id="idFilho" name="idFilho" value="<?=$dadosBanco["idFilho"];?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-3">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Ordem que o menu aparece no sistema">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-sort-numeric-up"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Ordem do Menu" id="ordem" name="ordem" value="<?=$dadosBanco["ordem"];?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-12">
                                                                <div class="input-group mb-12">
                                                                    <span class="input-group-text" data-toggle="tooltip" title="Informações para a busca do sistema">
                                                                        <i class="fas fa-tag"></i>
                                                                    </span>                                                                    
                                                                    <textarea name="tags" id="tags" rows="5" placeholder="Descreva para que serve o menu no sistema, irá ajudar na busca!" style="width: 100%;" class="form-control"><?=$dadosBanco["tags"]; ?></textarea>
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Fim Dados Menu-->

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <button type="button" class="btn btn-success float-right botao-efeito" id="bt-salvar" onclick="formSubmit('#cadastroForm','<?= $urlAction; ?>',false);">
                                                    Salvar <i class="mdi mdi-check"></i>
                                                </button>
                                                <div id="resposta-form" class="float-right" style="margin: 0 10px 0 0;">
                                                    <!--Resposta do Server-->
                                                    <p>Campos com * são obrigatórios</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </section>


                        </div>
                    </div>
                </div>



            </div> <!-- end container-fluid -->
        </div>
    </div>
    <!--CONTEÚDO-->


    <!--FOOTER-->
    <?= $this->loadview('admin/includes/footer'); ?>

    <!--JAVSCRIPT-->
    <?= $this->loadview('admin/includes/scripts'); ?>

    <script>
        $(document).ready(function() {
            $('#idFilho').mask('00');
            $('#ordem').mask('00');
        });

        function mudarIcone(valor){
            $("#icone-lista").removeClass().addClass(valor);
        }

        mudarIcone('<?=$dadosBanco["icone"];?>');

        //Lendo Enter do documento para chamar o form
        $("input[type='text']").on('keydown', function(event) {
            if (event.keyCode === 13){
                formSubmit('#cadastroForm','<?= $urlAction; ?>');
            }
        });        
    </script>
</body>

</html>