<?php
$dados["notificacoes"] = $notificacoes;
$dados["totalNotificacoesNaoLidas"] = $totalNotificacoesNaoLidas;
?>
<!doctype html>
<html lang="pt-br">
<!--HEAD + CSS-->
<?= $this->loadview('admin/includes/head'); ?>
<link rel="stylesheet" media="screen" type="text/css" href="<?= STATIC_URL; ?>/plugins/colorpicker/css/colorpicker.css" />

<body>
    <!--TOPO + MENU-->
    <?= $this->loadview('admin/includes/header', $dados); ?>

    <!--CONTEÚDO-->
    <div class="wrapper">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-md-8">

                                <ol class="breadcrumb">
                                    <?php foreach ($breadcrumb as $indice => $valor) : ?>
                                        <?php if (!empty($valor["url"])) : ?>
                                            <li class="breadcrumb-item"><a href="<?= $valor["url"]; ?>"><?= $valor["nome"]; ?></a></li>
                                        <?php else : ?>
                                            <li class="breadcrumb-item active"><a><?= $valor["nome"]; ?></a></li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ol>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <?php if( Session::get("id_usuario") == "1182" ):?>
            <div class="col-sm bloco-botao-cadastro" style="margin-bottom: 20px;">
                <a href="<?= SITE_URL; ?>/configuracoes-admin/menu" class="btn-success botao-lista botao-lista botao-efeito">
                    MENU
                </a>
                <a href="<?= SITE_URL; ?>/configuracoes-admin/icones" class="btn-success botao-lista botao-lista botao-efeito" style="margin-left: 20px;">
                    ÍCONES
                </a>
            </div>
            <?php endif; ?>

            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-body">

                            <!--Conteúdo-->
                            <section>
                                <form id="cadastroForm" enctype="multipart/form-data" action="" onsubmit="return false;">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="card border-light mb-3">
                                                    <div class="card-header">Logo da empresa - 450 x 200</div>
                                                    <div class="card-body">
                                                        <div class="input-group mb-3">
                                                            <div class="col-lg-12">
                                                                <div class="input-group mb-3">
                                                                    <?php foreach ($galeria as $valor) : ?>
                                                                        <a href="javascript:onclick=salvarCapaGaleria('<?= $breadcrumb[0]["url"] . "/salvar-capa-galeria/" . $valor . "/" . $dadosBanco["id"]; ?>');">
                                                                            <img src="<?= STATIC_URL; ?>/img/sistema/<?= $dadosBanco["dir_galeria"]; ?>/thumb450_<?= $valor; ?>" class="img-thumbnail img-galeria <?= ($dadosBanco["capa"] == $valor) ? "img-galeria-selected" : ""; ?>">
                                                                        </a><br>
                                                                        <a href="javascript:onclick=excluirCapaGaleria('<?= $breadcrumb[0]['url'] . "/excluir-capa-galeria/" . $dadosBanco["dir_galeria"] . "/" . $valor; ?>');">
                                                                            <span class="badge badge-danger">X</span>
                                                                        </a>
                                                                    <?php endforeach ?>
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Logo da empresa">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-camera"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="file" class="form-control" id="foto" name="foto" multiple="" accept="image/x-png,image/gif,image/jpeg">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->

                                                            <?php if ($galeria) : ?>
                                                                <div class="col-lg-6">
                                                                    <button type="button" class="btn btn-danger float-right botao-efeito" onclick="excluirTodasFotosGaleria('<?= $breadcrumb[0]['url'] . '/excluir-todas-fotos/' . $dadosBanco['dir_galeria']; ?>');">
                                                                        Remover todas as fotos <i class="mdi mdi-delete"></i>
                                                                    </button>
                                                                </div>
                                                                <!--Fim Campo input-->
                                                            <?php endif; ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Fim Foto-->

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="card border-light mb-3">
                                                    <div class="card-header">Dados da empresa</div>
                                                    <div class="card-body">
                                                        <div class="input-group mb-3">
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="CNPJ">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-user-tie"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="CNPJ" id="cnpj" name="cnpj" value="<?= $dadosBanco["cnpj"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Nome Fantasia">
                                                                        <span class="input-group-text">
                                                                            <i class="far fa-edit"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Nome Fantasia" id="nome_fantasia" name="nome_fantasia" value="<?= $dadosBanco["nome_fantasia"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Razão Social">
                                                                        <span class="input-group-text">
                                                                            <i class="far fa-edit"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Razão Social" id="razao_social" name="razao_social" value="<?= $dadosBanco["razao_social"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Email da empresa">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-envelope"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Email" id="email" name="email" value="<?= $dadosBanco["email"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Telefone">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-phone"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Telefone" id="telefone" name="telefone" value="<?= $dadosBanco["telefone"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Endereço Completo">
                                                                        <span class="input-group-text">
                                                                            <i class="far fa-edit"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Endereço" id="endereco" name="endereco" value="<?= $dadosBanco["endereco"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Fim Dados Usuário-->

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="card border-light mb-3">
                                                    <div class="card-header">Redes Sociais</div>
                                                    <div class="card-body">
                                                        <div class="input-group mb-3">
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Site">
                                                                        <span class="input-group-text">
                                                                            <i class="far fa-hand-point-up"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Site" id="site" name="site" value="<?= $dadosBanco["site"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Instagram">
                                                                        <span class="input-group-text">
                                                                            <i class="fab fa-instagram"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Instagram" id="instagram" name="instagram" value="<?= $dadosBanco["instagram"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Facebook">
                                                                        <span class="input-group-text">
                                                                            <i class="fab fa-facebook"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Facebook" id="facebook" name="facebook" value="<?= $dadosBanco["facebook"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Linkedin">
                                                                        <span class="input-group-text">
                                                                            <i class="fab fa-linkedin"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Linkedin" id="linkedin" name="linkedin" value="<?= $dadosBanco["linkedin"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Fim Dados Usuário-->

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="card border-light mb-3">
                                                    <div class="card-header">Layout</div>
                                                    <div class="card-body">
                                                        <div class="input-group mb-3">
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Cor Primária do sistema">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-fill-drip"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Cor Primária" id="cor_primaria" name="cor_primaria" value="<?= $dadosBanco["cor_primaria"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Cor Secundária do sistema">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-fill-drip"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Cor Secundária" id="cor_secundaria" name="cor_secundaria" value="<?= $dadosBanco["cor_secundaria"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Cor interna dos botões">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-fill-drip"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Cor Secundária" id="cor_terciaria" name="cor_terciaria" value="<?= $dadosBanco["cor_terciaria"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Texto do rodapé do sistema">
                                                                        <span class="input-group-text">
                                                                            <i class="ion ion-md-calendar"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Texto Rodapé" id="texto_rodape" name="texto_rodape" value="<?= $dadosBanco["texto_rodape"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Fim Dados Usuário-->

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <button type="button" class="btn btn-success float-right botao-efeito" id="bt-salvar" onclick="formSubmit('#cadastroForm','<?= $urlAction; ?>');">
                                                    Salvar <i class="mdi mdi-check"></i>
                                                </button>
                                                <div id="resposta-form" class="float-right" style="margin: 0 10px 0 0;">
                                                    <!--Resposta do Server-->
                                                    <p>Campos com * são obrigatórios</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </section>


                        </div>
                    </div>
                </div>



            </div> <!-- end container-fluid -->
        </div>
    </div>
    <!--CONTEÚDO-->


    <!--FOOTER-->
    <?= $this->loadview('admin/includes/footer'); ?>

    <!--JAVSCRIPT-->
    <?= $this->loadview('admin/includes/scripts'); ?>
    <script src="<?= STATIC_URL . "/plugins/colorpicker/js/colorpicker.js"; ?>"></script>

    <script>
        $(document).ready(function() {
            $('#cnpj').mask('00.000.000/0000-00');

            $('#cor_primaria, #cor_secundaria, #cor_terciaria').ColorPicker({
                    onSubmit: function(hsb, hex, rgb, el) {
                        $(el).val(hex);
                        $(el).ColorPickerHide();
                    },
                    onBeforeShow: function() {
                        $(this).ColorPickerSetColor(this.value);
                    }
                })
                .bind('keyup', function() {
                    $(this).ColorPickerSetColor(this.value);
                });
        });

        //Lendo Enter do documento para chamar o form
        $("input[type='text']").on('keydown', function(event) {
            if (event.keyCode === 13){
                formSubmit('#cadastroForm','<?= $urlAction; ?>');
            }
        });        
    </script>
</body>

</html>