<?php
$dados["notificacoes"] = $notificacoes;
$dados["totalNotificacoesNaoLidas"] = $totalNotificacoesNaoLidas;
?>
<!doctype html>
<html lang="pt-br">
<!--HEAD + CSS-->
<?= $this->loadview('admin/includes/head'); ?>

<body>
    <!--TOPO + MENU-->
    <?= $this->loadview('admin/includes/header', $dados); ?>

    <!--CONTEÚDO-->
    <div class="wrapper">
        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-md-8">

                                <ol class="breadcrumb">
                                    <?php foreach ($breadcrumb as $indice => $valor) : ?>
                                        <?php if (!empty($valor["url"])) : ?>
                                            <li class="breadcrumb-item"><a href="<?= $valor["url"]; ?>"><?= $valor["nome"]; ?></a></li>
                                        <?php else : ?>
                                            <li class="breadcrumb-item active"><a><?= $valor["nome"]; ?></a></li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ol>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-body">

                            <!--Conteúdo-->
                            <section>
                                <form id="cadastroForm" enctype="multipart/form-data" action="" onsubmit="return false;">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="card border-light mb-3">
                                                    <div class="card-header">Informações de reforça da empresa</div>
                                                    <div class="card-body">
                                                        <div class="input-group mb-3">
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Título">
                                                                        <span class="input-group-text">
                                                                            <i class="fas fa-align-justify"></i>
                                                                        </span>
                                                                    </div>
                                                                    <input type="text" class="form-control" placeholder="Título *" id="titulo" name="titulo" value="<?= $dadosBanco["titulo"]; ?>">
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-6">
                                                                <div class="input-group mb-3">
                                                                    <div class="input-group-prepend" data-toggle="tooltip" title="Ícone que irá aparecer no site" >
                                                                        <span class="input-group-text">
                                                                            <i class="fab fa-fonticons-fi" id="icone-lista"></i>
                                                                        </span>
                                                                    </div>
                                                                    <select name="icone" class="custom-select" id="icone" onchange="javascript:mudarIcone(this.value);">
                                                                        <?php foreach($icones as $indice => $valor):?>
                                                                            <option value="<?=$valor["nome"]; ?>" <?= ($dadosBanco["icone"] == $valor["nome"]) ? "selected" : ""; ?>>
                                                                                <?=$valor["id"]; ?> : <?=$valor["nome"]; ?>
                                                                            </option>
                                                                        <?php endforeach; ?>
                                                                    </select>
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                            <div class="col-lg-12">
                                                                <div class="input-group mb-12">
                                                                    <span class="input-group-text" data-toggle="tooltip" title="Descreva sobre o título criado">
                                                                        <i class="fas fa-text-width"></i>
                                                                    </span>                                                                    
                                                                    <textarea name="texto" id="texto" rows="5" placeholder="Descreva sobre o titulo criado" style="width: 100%;" class="form-control"><?=$dadosBanco["texto"]; ?></textarea>
                                                                </div>
                                                            </div>
                                                            <!--Fim Campo input-->
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!--Fim Dados Menu-->

                                        <div class="row">
                                            <div class="col-lg-12">
                                                <button type="button" class="btn btn-success float-right botao-efeito" id="bt-salvar" onclick="formSubmit('#cadastroForm','<?= $urlAction; ?>',false);">
                                                    Salvar <i class="mdi mdi-check"></i>
                                                </button>
                                                <div id="resposta-form" class="float-right" style="margin: 0 10px 0 0;">
                                                    <!--Resposta do Server-->
                                                    <p>Campos com * são obrigatórios</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </section>


                        </div>
                    </div>
                </div>



            </div> <!-- end container-fluid -->
        </div>
    </div>
    <!--CONTEÚDO-->


    <!--FOOTER-->
    <?= $this->loadview('admin/includes/footer'); ?>

    <!--JAVSCRIPT-->
    <?= $this->loadview('admin/includes/scripts'); ?>

    <script>
        $(document).ready(function() {
        });

        function mudarIcone(valor){
            $("#icone-lista").removeClass().addClass(valor);
        }
        
        mudarIcone('<?=$dadosBanco["icone"];?>');

        //Lendo Enter do documento para chamar o form
        $("input[type='text']").on('keydown', function(event) {
            if (event.keyCode === 13){
                formSubmit('#cadastroForm','<?= $urlAction; ?>');
            }
        });        
    </script>
</body>

</html>