<!DOCTYPE html>
<html lang="pt-br">

<?php $this->loadview('templates/buildstate/includes/head'); ?>

<body>

    <?php $this->loadview('templates/buildstate/includes/preloader'); ?>

    <!-- content wraper -->
    <div class="content-wrapper">

        <!-- nav -->
        <?php $this->loadview('templates/buildstate/includes/navbar'); ?>
        <!-- nav end -->

        <!-- slider -->
        <?php $this->loadview('templates/buildstate/includes/slider-home'); ?>
        <!-- slider end -->


        <!-- section destaques -->
        <section class="whitepage" id="about">

            <div class="container">
                <div class="row">

                    <div class="col-md-4">
                        <div class="wrap-news onStep" data-animation="fadeInLeft" data-time="300">
                            <a class="link-class" href="#">
                                <img alt="imageportofolio" class="img-responsive" src="<?= TEMPLATE_BUILDSTATE; ?>/img/img-news.jpg">
                            </a>
                            <h3>Topografia</h3>
                            <p>Através da Topografia é possível determinar analiticamente as medidas de área e perímetro, localização, orientação, variações no relevo e ainda representá-las graficamente em plantas topográficas.</p>
                            <a class="link-class" href="#">
                                SAIBA MAIS
                                <span class="devider"></span>
                            </a>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="wrap-news onStep" data-animation="fadeInRight" data-time="600">
                            <a href="">
                                <img alt="imageportofolio" class="img-responsive" src="<?= TEMPLATE_BUILDSTATE; ?>/img/img-news2.jpg">
                            </a>
                            <h3>Terraplenagem</h3>
                            <p>Terraplenagem de um terreno é primordial para uma obra ser iniciada, se feita sem a supervisão de bons profissionais, problemas como erosão e deslizamento de terra podem aparecer futuramente.</p>
                            <a class="link-class" href="#">
                                SAIBA MAIS
                                <span class="devider"></span>
                            </a>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="wrap-news onStep" data-animation="fadeInRight" data-time="900">
                            <a href="">
                                <img alt="imageportofolio" class="img-responsive" src="<?= TEMPLATE_BUILDSTATE; ?>/img/img-news1.jpg">
                            </a>
                            <h3>Escritura de Terrenos</h3>
                            <p>A escritura de terreno é  extremamente necessário. Afinal, se não tiver a documentação correta, ele deixa de ser uma posse legalizada e passa a ser considerado um terreno abandonado.</p>
                            <a class="link-class" href="#">
                                SAIBA MAIS
                                <span class="devider"></span>
                            </a>
                        </div>
                    </div>

                </div>
            </div>

        </section>
        <!-- section destaques end -->

        <section class="yellowpage">
            <div class="container">
                <div class="row">

                    <div class="col-md-7">
                        <h2><strong>Proprietário</strong> de área acima de 30 mil m², faça uma parceria com a <strong>J.Alves e multiplique</strong> seus lucros!</h2>
                    </div>

                    <div class="col-md-5">
                        <div class="right">
                            <div class="btn-content">
                                <a class="link-class " href="#">Clique e saiba mais</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>

        <!-- stepwork -->
        <section id="step-page" class="step-page">
            <div class="container">
                <div class="row">

                    <div class="col-md-12">
                        <div class="text-center">
                            <h2><strong>Como Trabalhamos</strong></h2>
                            <span class="devider-center"></span>
                            <div class="space-single"></div>
                        </div>
                    </div>

                    <!-- step menu -->
                    <div class="onStep" data-animation="fadeInUp" data-time="300">

                        <div class="step-mains">

                            <div class="col-md-3 step-main">
                                <div class="step-main">
                                    <a class="filt-step active" data-filter=".planing"><span><strong>01 PLANEJAMENTO</strong></span></a>
                                </div>
                            </div>

                            <div class="col-md-3 step-main">
                                <div class="step-main">
                                    <a class="filt-step" data-filter=".concept"><span><strong>02 PROJETO</strong></span></a>
                                </div>
                            </div>

                            <div class="col-md-3 step-main">
                                <div class="step-main">
                                    <a class="filt-step" data-filter=".construct"><span><strong>03 OBRAS</strong></span></a>
                                </div>
                            </div>

                            <div class="col-md-3 step-main">
                                <div class="step-main">
                                    <a class="filt-step" data-filter=".finish"><span><strong>04 ENTREGA</strong></span></a>
                                </div>
                            </div>

                        </div>
                        <!-- step menu end -->

                        <!-- step content -->
                        <div id="step-text" class="col-md-12">

                            <div class="cont planing">
                                <div class="text-center">
                                    <p>Nessa etapa é onde iremos analisar toda a área para construções dos lotes. Iremos também analisar se o terreno está apto para construção, viabilizado para obras e juridicamente legalizado aos órgãos competentes. No planejamento se exige uma grande concentração de análise da nossa equipe, só após esse processo, damos continuidade.</p>
                                </div>
                            </div>

                            <div class="cont concept">
                                <div class="text-center">
                                    <p>Aqui nossa equipe técnica entra em ação, a topografia irá fazer um estudo topográfico da área. A arquitetura irá projetar a melhor estrutura visual e ergonômica para construção dos lotes. Os Engenheiros irão executar as licenças necessárias e acompanhar o processo, e claro nosso marketing e vendas estarão de prontidão para realizar os seus sonhos.</p>
                                </div>
                            </div>

                            <div class="cont construct">
                                <div class="text-center">
                                    <p>Na etapa de obras toda equipe da J.Alves coloca literalmente a mão na massa. Nessa fase profissionais como, operadores de máquina, pedreiros, eletricistas, pintores, e toda a parte operacional trabalha. Claro sem esquecer que estão sendo acompanhadas por toda equipe técnica de perto, para tudo sair perfeito sempre.</p>
                                </div>
                            </div>

                            <div class="cont finish">
                                <div class="text-center">
                                    <p>Certamente é a parte que dá mais satisfação a J.Alves, e aos nossos clientes. É a fase que finalmente você poderá construir seu futuro lar, onde serão escritas as mais belas histórias sobre a sua vida.</p>
                                </div>
                            </div>

                        </div>
                    </div>
                    <!-- step content end -->

                </div>
            </div>
        </section>
        <!-- stepwork end -->


        <!-- loteamentos destaques -->
        <?php $this->loadview('templates/buildstate/includes/loteamentos'); ?>
        <!-- loteamentos destaques end -->

        <!-- footer -->
        <?php $this->loadview('templates/buildstate/includes/footer'); ?>
        <!-- footer end -->


    </div>
    <!-- content wraper end -->

    <?php $this->loadview('templates/buildstate/includes/scripts'); ?>

</body>

</html>