<section class="banner-one">
    <div class="particles-snow" id="banner-one-snow"></div><!-- /#cta-one-snow.particles-snow -->


    <div class="container">
        <div class="banner-one__image wow slideInUp" data-wow-duration="1500ms">
        <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/foguete-1.png" class="banner-one__bg-shape-2" alt="">
        <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/planeta-4.png" class="banner-one__bg-shape-3" alt="">
        <img src="<?=TEMPLATE_INOVEX;?>/images/shapes/planeta-5.png" class="banner-one__bg-shape-5" alt="">
        </div><!-- /.banner-one__image -->
        <div class="row">
            <div class="col-xl-7">
                <div class="banner-one__content">
                    <h3>Soluções Digitais para sua <span class="cor-destaque">empresa decolar</span> como um foguete.</h3>
                </div><!-- /.banner-one__content -->
            </div><!-- /.col-lg-7 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</section><!-- /.banner-one -->