<section class="blog-one blog-one__home-one">
    <div class="container">
        <div class="blog-one__top">
            <div class="block-title text-left">
                <p><span>Latest News</span></p>
                <h3>Learn Some New info from <br> <span>Our Latest News.</span></h3>
            </div><!-- /.block-title text-center -->

            <div class="blog-one__carousel-btn">
                <a href="#" class="blog-one__carousel-btn-left"><i class="far fa-angle-left"></i></a>
                <a href="#" class="blog-one__carousel-btn-right"><i class="far fa-angle-right"></i></a>
            </div><!-- /.blog-one__carousel-btn -->
        </div><!-- /.blog-one__top -->


        <div class="thm__owl-carousel blog-one__carousel owl-carousel owl-theme" data-carousel-prev-btn=".blog-one__carousel-btn-left" data-carousel-next-btn=".blog-one__carousel-btn-right" data-options='{
                    "items": 3, "margin": 40, "smartSpeed": 700, "autoplay": true, "autoplayTimeout": 5000,
                    "autoplayHoverPause": true, "nav": false, "dots": false, "loop": true, "responsive": {
                        "0": { "items": 1, "margin": 0},
                        "575": { "items": 1, "margin": 0},
                        "767": { "items": 1, "margin": 0},
                        "991": { "items": 2, "margin": 40},
                        "1199": { "items": 3, "margin": 40}
                    }
                }'>
            <div class="item">
                <div class="blog-one__single">
                    <div class="blog-one__image">
                        <img src="<?= TEMPLATE_INOVEX; ?>/images/blog/blog-1-1.jpg" alt="">
                        <a href="blog-details.html"><i class="fal fa-plus"></i></a>
                    </div><!-- /.blog-one__image -->
                    <div class="blog-one__content">
                        <div class="blog-one__meta">
                            <a href="blog-details.html">Sara dodly</a>
                            <span>-</span>
                            <a href="blog-details.html">Mar 15, 2020</a>
                        </div><!-- /.blog-one__meta -->
                        <h3><a href="blog-details.html">Additional Services that will Grow Your...</a></h3>
                        <a href="blog-details.html" class="thm-btn blog-one__btn"><span>Read More</span></a>
                        <!-- /.thm-btn blog-one__btn -->
                    </div><!-- /.blog-one__content -->
                </div><!-- /.blog-one__single -->
            </div><!-- /.item -->
            <div class="item">
                <div class="blog-one__single">
                    <div class="blog-one__image">
                        <img src="<?= TEMPLATE_INOVEX; ?>/images/blog/blog-1-2.jpg" alt="">
                        <a href="blog-details.html"><i class="fal fa-plus"></i></a>
                    </div><!-- /.blog-one__image -->
                    <div class="blog-one__content">
                        <div class="blog-one__meta">
                            <a href="blog-details.html">Sara dodly</a>
                            <span>-</span>
                            <a href="blog-details.html">Mar 15, 2020</a>
                        </div><!-- /.blog-one__meta -->
                        <h3><a href="blog-details.html">Additional Services that will Grow Your...</a></h3>
                        <a href="blog-details.html" class="thm-btn blog-one__btn"><span>Read More</span></a>
                        <!-- /.thm-btn blog-one__btn -->
                    </div><!-- /.blog-one__content -->
                </div><!-- /.blog-one__single -->
            </div><!-- /.item -->
            <div class="item">
                <div class="blog-one__single">
                    <div class="blog-one__image">
                        <img src="<?= TEMPLATE_INOVEX; ?>/images/blog/blog-1-3.jpg" alt="">
                        <a href="blog-details.html"><i class="fal fa-plus"></i></a>
                    </div><!-- /.blog-one__image -->
                    <div class="blog-one__content">
                        <div class="blog-one__meta">
                            <a href="blog-details.html">Sara dodly</a>
                            <span>-</span>
                            <a href="blog-details.html">Mar 15, 2020</a>
                        </div><!-- /.blog-one__meta -->
                        <h3><a href="blog-details.html">Additional Services that will Grow Your...</a></h3>
                        <a href="blog-details.html" class="thm-btn blog-one__btn"><span>Read More</span></a>
                        <!-- /.thm-btn blog-one__btn -->
                    </div><!-- /.blog-one__content -->
                </div><!-- /.blog-one__single -->
            </div><!-- /.item -->
            <div class="item">
                <div class="blog-one__single">
                    <div class="blog-one__image">
                        <img src="<?= TEMPLATE_INOVEX; ?>/images/blog/blog-1-4.jpg" alt="">
                        <a href="blog-details.html"><i class="fal fa-plus"></i></a>
                    </div><!-- /.blog-one__image -->
                    <div class="blog-one__content">
                        <div class="blog-one__meta">
                            <a href="blog-details.html">Sara dodly</a>
                            <span>-</span>
                            <a href="blog-details.html">Mar 15, 2020</a>
                        </div><!-- /.blog-one__meta -->
                        <h3><a href="blog-details.html">Additional Services that will Grow Your...</a></h3>
                        <a href="blog-details.html" class="thm-btn blog-one__btn"><span>Read More</span></a>
                        <!-- /.thm-btn blog-one__btn -->
                    </div><!-- /.blog-one__content -->
                </div><!-- /.blog-one__single -->
            </div><!-- /.item -->
            <div class="item">
                <div class="blog-one__single">
                    <div class="blog-one__image">
                        <img src="<?= TEMPLATE_INOVEX; ?>/images/blog/blog-1-5.jpg" alt="">
                        <a href="blog-details.html"><i class="fal fa-plus"></i></a>
                    </div><!-- /.blog-one__image -->
                    <div class="blog-one__content">
                        <div class="blog-one__meta">
                            <a href="blog-details.html">Sara dodly</a>
                            <span>-</span>
                            <a href="blog-details.html">Mar 15, 2020</a>
                        </div><!-- /.blog-one__meta -->
                        <h3><a href="blog-details.html">Additional Services that will Grow Your...</a></h3>
                        <a href="blog-details.html" class="thm-btn blog-one__btn"><span>Read More</span></a>
                        <!-- /.thm-btn blog-one__btn -->
                    </div><!-- /.blog-one__content -->
                </div><!-- /.blog-one__single -->
            </div><!-- /.item -->
            <div class="item">
                <div class="blog-one__single">
                    <div class="blog-one__image">
                        <img src="<?= TEMPLATE_INOVEX; ?>/images/blog/blog-1-6.jpg" alt="">
                        <a href="blog-details.html"><i class="fal fa-plus"></i></a>
                    </div><!-- /.blog-one__image -->
                    <div class="blog-one__content">
                        <div class="blog-one__meta">
                            <a href="blog-details.html">Sara dodly</a>
                            <span>-</span>
                            <a href="blog-details.html">Mar 15, 2020</a>
                        </div><!-- /.blog-one__meta -->
                        <h3><a href="blog-details.html">Additional Services that will Grow Your...</a></h3>
                        <a href="blog-details.html" class="thm-btn blog-one__btn"><span>Read More</span></a>
                        <!-- /.thm-btn blog-one__btn -->
                    </div><!-- /.blog-one__content -->
                </div><!-- /.blog-one__single -->
            </div><!-- /.item -->
            <div class="item">
                <div class="blog-one__single">
                    <div class="blog-one__image">
                        <img src="<?= TEMPLATE_INOVEX; ?>/images/blog/blog-1-7.jpg" alt="">
                        <a href="blog-details.html"><i class="fal fa-plus"></i></a>
                    </div><!-- /.blog-one__image -->
                    <div class="blog-one__content">
                        <div class="blog-one__meta">
                            <a href="blog-details.html">Sara dodly</a>
                            <span>-</span>
                            <a href="blog-details.html">Mar 15, 2020</a>
                        </div><!-- /.blog-one__meta -->
                        <h3><a href="blog-details.html">Additional Services that will Grow Your...</a></h3>
                        <a href="blog-details.html" class="thm-btn blog-one__btn"><span>Read More</span></a>
                        <!-- /.thm-btn blog-one__btn -->
                    </div><!-- /.blog-one__content -->
                </div><!-- /.blog-one__single -->
            </div><!-- /.item -->
            <div class="item">
                <div class="blog-one__single">
                    <div class="blog-one__image">
                        <img src="<?= TEMPLATE_INOVEX; ?>/images/blog/blog-1-8.jpg" alt="">
                        <a href="blog-details.html"><i class="fal fa-plus"></i></a>
                    </div><!-- /.blog-one__image -->
                    <div class="blog-one__content">
                        <div class="blog-one__meta">
                            <a href="blog-details.html">Sara dodly</a>
                            <span>-</span>
                            <a href="blog-details.html">Mar 15, 2020</a>
                        </div><!-- /.blog-one__meta -->
                        <h3><a href="blog-details.html">Additional Services that will Grow Your...</a></h3>
                        <a href="blog-details.html" class="thm-btn blog-one__btn"><span>Read More</span></a>
                        <!-- /.thm-btn blog-one__btn -->
                    </div><!-- /.blog-one__content -->
                </div><!-- /.blog-one__single -->
            </div><!-- /.item -->
            <div class="item">
                <div class="blog-one__single">
                    <div class="blog-one__image">
                        <img src="<?= TEMPLATE_INOVEX; ?>/images/blog/blog-1-9.jpg" alt="">
                        <a href="blog-details.html"><i class="fal fa-plus"></i></a>
                    </div><!-- /.blog-one__image -->
                    <div class="blog-one__content">
                        <div class="blog-one__meta">
                            <a href="blog-details.html">Sara dodly</a>
                            <span>-</span>
                            <a href="blog-details.html">Mar 15, 2020</a>
                        </div><!-- /.blog-one__meta -->
                        <h3><a href="blog-details.html">Additional Services that will Grow Your...</a></h3>
                        <a href="blog-details.html" class="thm-btn blog-one__btn"><span>Read More</span></a>
                        <!-- /.thm-btn blog-one__btn -->
                    </div><!-- /.blog-one__content -->
                </div><!-- /.blog-one__single -->
            </div><!-- /.item -->
            <div class="item">
                <div class="blog-one__single">
                    <div class="blog-one__image">
                        <img src="<?= TEMPLATE_INOVEX; ?>/images/blog/blog-1-10.jpg" alt="">
                        <a href="blog-details.html"><i class="fal fa-plus"></i></a>
                    </div><!-- /.blog-one__image -->
                    <div class="blog-one__content">
                        <div class="blog-one__meta">
                            <a href="blog-details.html">Sara dodly</a>
                            <span>-</span>
                            <a href="blog-details.html">Mar 15, 2020</a>
                        </div><!-- /.blog-one__meta -->
                        <h3><a href="blog-details.html">Additional Services that will Grow Your...</a></h3>
                        <a href="blog-details.html" class="thm-btn blog-one__btn"><span>Read More</span></a>
                        <!-- /.thm-btn blog-one__btn -->
                    </div><!-- /.blog-one__content -->
                </div><!-- /.blog-one__single -->
            </div><!-- /.item -->
            <div class="item">
                <div class="blog-one__single">
                    <div class="blog-one__image">
                        <img src="<?= TEMPLATE_INOVEX; ?>/images/blog/blog-1-11.jpg" alt="">
                        <a href="blog-details.html"><i class="fal fa-plus"></i></a>
                    </div><!-- /.blog-one__image -->
                    <div class="blog-one__content">
                        <div class="blog-one__meta">
                            <a href="blog-details.html">Sara dodly</a>
                            <span>-</span>
                            <a href="blog-details.html">Mar 15, 2020</a>
                        </div><!-- /.blog-one__meta -->
                        <h3><a href="blog-details.html">Additional Services that will Grow Your...</a></h3>
                        <a href="blog-details.html" class="thm-btn blog-one__btn"><span>Read More</span></a>
                        <!-- /.thm-btn blog-one__btn -->
                    </div><!-- /.blog-one__content -->
                </div><!-- /.blog-one__single -->
            </div><!-- /.item -->
            <div class="item">
                <div class="blog-one__single">
                    <div class="blog-one__image">
                        <img src="<?= TEMPLATE_INOVEX; ?>/images/blog/blog-1-12.jpg" alt="">
                        <a href="blog-details.html"><i class="fal fa-plus"></i></a>
                    </div><!-- /.blog-one__image -->
                    <div class="blog-one__content">
                        <div class="blog-one__meta">
                            <a href="blog-details.html">Sara dodly</a>
                            <span>-</span>
                            <a href="blog-details.html">Mar 15, 2020</a>
                        </div><!-- /.blog-one__meta -->
                        <h3><a href="blog-details.html">Additional Services that will Grow Your...</a></h3>
                        <a href="blog-details.html" class="thm-btn blog-one__btn"><span>Read More</span></a>
                        <!-- /.thm-btn blog-one__btn -->
                    </div><!-- /.blog-one__content -->
                </div><!-- /.blog-one__single -->
            </div><!-- /.item -->
        </div><!-- /.row -->

    </div><!-- /.container -->
</section><!-- /.blog-grid -->