<?php 
    $clientes = [
        [
            "nome" => "Alux Pro Sports",
            "img" => "alux.png",
        ],
        [
            "nome" => "MMReefer",
            "img" => "mmreefer.png",
        ],
        [
            "nome" => "Andiara Advogada",
            "img" => "andiara-advogada.png",
        ],
        [
            "nome" => "Postos Meta",
            "img" => "postos-meta.png",
        ],
        [
            "nome" => "Unikinder Clínica Pediatrica",
            "img" => "unikinder.png",
        ],
        [
            "nome" => "Capital Container",
            "img" => "capital-container.png",
        ],
        [
            "nome" => "King Mix",
            "img" => "king-mix.png",
        ],
        [
            "nome" => "Clínica de Análise LabTess",
            "img" => "labtess.png",
        ],
        [
            "nome" => "Imobiliária Mauro Imóveis",
            "img" => "mauro-imoveis.png",
        ],
        [
            "nome" => "Schwanke Casa",
            "img" => "schwanke-casa.png",
        ]
    ];
?>
<section class="brand-one brand-one__pricing-page brand-one__home-three" style="margin-top: 70px;">
    <div class="container">
        <div class="block-title text-center">
            <p class="color-2"><span>Clientes</span></p>
            <h3>Mais de 150 empresas <br> <span>que confiaram na J6 Soluções Digitais</span></h3>
        </div><!-- /.block-title text-center -->

        <div class="brand-one__carousel owl-carousel thm__owl-carousel owl-theme" data-options='{
            "items": 5, "margin": 95, "smartSpeed": 700, "loop": true, "autoplay": true, "autoplayTimeout": 5000, "autoplayHoverPause": false, "nav": false, "dots": false, "responsive": {"0": { "margin": 20, "items": 2 }, "575": { "margin": 30, "items": 3 },"767": { "margin": 40, "items": 4 },   "991": { "margin": 70, "items": 4 }, "1199": { "margin": 95, "items": 5 } } }'>
            <?php foreach($clientes as $cliente): ?>
            <div class="item">
                <img src="<?= TEMPLATE_INOVEX; ?>/images/brand/<?=$cliente["img"];?>" title="<?=$cliente["nome"];?>">
            </div><!-- /.item -->
            <?php endforeach; ?>
        </div><!-- /.brand-one__carousel owl-carousel thm__owl-carousel owl-theme -->
    </div><!-- /.container -->
</section><!-- /.brand-one -->