<footer class="site-footer site-footer__home-three" style="margin-top: 70px;">

    <div class="site-footer__upper">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="footer-widget footer-widget__about">
                        <h3 class="footer-widget__title">Sobre</h3>
                        <p>Nosso foco é levar a melhor solução digital para nossos clientes, com serviço de excelência e valores justo.</p>
                        <div class="footer-widget__social">
                            <a href="https://www.google.com/maps/place/J6+Solu%C3%A7%C3%B5es+Digitais/@-26.7306064,-48.6913196,15z/data=!4m5!3m4!1s0x0:0x90f4d0e4c1fbfa37!8m2!3d-26.7306064!4d-48.6913196"><i class="fab fa-google-plus"></i></a>
                            <a href="https://www.facebook.com/j6solucoesdigitais"><i class="fab fa-facebook-f"></i></a>
                            <a href="https://www.instagram.com/j6solucoesdigitais/"><i class="fab fa-instagram"></i></a>
                            <a href="https://www.linkedin.com/company/j6-solu%C3%A7%C3%B5es-digitais/?viewAsMember=true"><i class="fab fa-linkedin"></i></a>                            
                        </div><!-- /.footer-widget__social -->
                    </div><!-- /.footer-widget footer-widget__about -->
                </div><!-- /.col-lg-3 col-md-6 col-sm-12 -->
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="footer-widget footer-widget__links__1">
                        <h3 class="footer-widget__title">Soluções</h3>
                        <ul class="list-unstyled footer-widget__links-list">
                            <li><a href="#">Posts para Redes Sociais</a></li>
                            <li><a href="#">Campanha no Google ADS</a></li>
                            <li><a href="#">Criação de Artes Digital</a></li>
                            <li><a href="#">Site Express</a></li>
                            <li><a href="#">Site Personalizad</a></li>
                        </ul><!-- /.list-unstyled footer-widget__links-list -->
                    </div><!-- /.footer-widget -->
                </div><!-- /.col-lg-3 col-md-6 col-sm-12 -->
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="footer-widget footer-widget__links__2">
                        <h3 class="footer-widget__title">Acessos</h3>
                        <ul class="list-unstyled footer-widget__links-list">
                            <li><a href="#">Institucional</a></li>
                            <li><a href="#">Dúvidas</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">Portfólio</a></li>
                        </ul><!-- /.list-unstyled footer-widget__links-list -->
                    </div><!-- /.footer-widget -->
                </div><!-- /.col-lg-3 col-md-6 col-sm-12 -->
                <div class="col-lg-3 col-md-6 col-sm-12">
                    <div class="footer-widget footer-widget__contact">
                        <h3 class="footer-widget__title">Contato</h3>
                        <p>Balneário Piçarras <br> Santa Catarina, BR</p>
                        <p><a href="mailto:diretoria@j6.net.br">diretoria@j6.net.br</a></p>
                        <p><a href="tel:47997758281">+55 47 99775-8281</a></p>
                    </div><!-- /.footer-widget -->
                </div><!-- /.col-lg-3 col-md-6 col-sm-12 -->
            </div><!-- /.row -->
        </div><!-- /.container -->

    </div><!-- /.site-footer__upper -->
    <div class="site-footer__bottom">
        <div class="container">
            <p>® <?=date("Y"); ?> - J6 Soluções Digitais</p>
            <a href="index.html"><img src="<?= TEMPLATE_INOVEX; ?>/images/logo-1-1.png" alt=""></a>
            <ul class="list-unstyled site-footer__bottom-menu">
                <li><a href="javascript:void(0);">CNPJ: 47.189.708.0001-04 </a></li>
            </ul><!-- /.list-unstyled site-footer__bottom-menu -->
        </div><!-- /.container -->
    </div><!-- /.site-footer__bottom -->

</footer><!-- /.site-footer -->