<nav class="main-nav-one stricky">
    <div class="container-fluid">
        <div class="inner-container">
            <div class="logo-box">
                <a href="<?=SITE_URL; ?>">
                    <img src="<?= TEMPLATE_INOVEX; ?>/images/logo-1-2.png">
                </a>
                <a href="#" class="side-menu__toggler"><i class="fa fa-bars"></i></a>
            </div><!-- /.logo-box -->
            <div class="main-nav__main-navigation">
                <ul class="main-nav__navigation-box">
                    <li>
                        <a href="index.html">Institucional</a>
                    </li>
                    <li class="dropdown">
                        <a href="<?=SITE_URL; ?>/solucoes">Nossas Soluções</a>
                        <ul>
                            <li><a href="<?=SITE_URL; ?>/solucoes/posts-para-redes-sociais">Posts para Redes Sociais</a></li>
                            <li><a href="<?=SITE_URL; ?>/solucoes/campanha-no-google-ads">Campanha no Google ADS</a></li>
                            <li><a href="<?=SITE_URL; ?>/solucoes/criacao-de-artes-digital">Criação de Artes Digital</a></li>
                            <li><a href="<?=SITE_URL; ?>/solucoes/site-express">Site Express</a></li>
                            <li><a href="<?=SITE_URL; ?>/solucoes/site-personalizado">Site Personalizado</a></li>
                        </ul>
                    </li>
                    <li><a href="<?=SITE_URL; ?>/portfolio">Portfólio</a></li>
                    <li><a href="<?=SITE_URL; ?>/duvidas">Dúvidas</a></li>
                </ul><!-- /.main-nav__navigation-box -->
            </div><!-- /.main-nav__main-navigation -->
            <div class="main-nav__right">
                <a href="#" class="search-popup__toggler main-nav__search"><i class="far fa-search"></i></a>
                <a href="<?=SITE_URL; ?>/fale-conosco" class="thm-btn main-nav-one__btn"><span>Fale Conosco</span></a>
                <!-- /.thm-btn main-nav-one__btn -->
            </div><!-- /.main-nav__right -->
        </div><!-- /.inner-container -->
    </div><!-- /.container-fluid -->
</nav><!-- /.main-nav-one -->