<div class="side-menu__block">

    <a href="#" class="side-menu__toggler side-menu__close-btn"><i class="fa fa-times"></i>
        <!-- /.fa fa-close --></a>

    <div class="side-menu__block-overlay custom-cursor__overlay">
        <div class="cursor"></div>
        <div class="cursor-follower"></div>
    </div><!-- /.side-menu__block-overlay -->
    <div class="side-menu__block-inner ">

        <a href="index.html" class="side-menu__logo"><img src="<?=TEMPLATE_INOVEX;?>/images/logo-1-1.png" alt=""></a>
        <nav class="mobile-nav__container">
            <!-- content is loading via js -->
        </nav>
        <p class="side-menu__block__copy">® <?=date("Y"); ?> - <a href="<?=SITE_URL; ?>">J6 Soluções Digitais</a></p>
        <div class="side-menu__social">
            <a href="https://www.google.com/maps/place/J6+Solu%C3%A7%C3%B5es+Digitais/@-26.7306064,-48.6913196,15z/data=!4m5!3m4!1s0x0:0x90f4d0e4c1fbfa37!8m2!3d-26.7306064!4d-48.6913196"><i class="fab fa-google-plus"></i></a>
            <a href="https://www.facebook.com/j6solucoesdigitais"><i class="fab fa-facebook-f"></i></a>
            <a href="https://www.instagram.com/j6solucoesdigitais/"><i class="fab fa-instagram"></i></a>
            <a href="https://www.linkedin.com/company/j6-solu%C3%A7%C3%B5es-digitais/?viewAsMember=true"><i class="fab fa-linkedin"></i></a>
        </div>
    </div><!-- /.side-menu__block-inner -->
</div><!-- /.side-menu__block -->

<div class="search-popup">
    <div class="search-popup__overlay custom-cursor__overlay">
        <div class="cursor"></div>
        <div class="cursor-follower"></div>
    </div><!-- /.search-popup__overlay -->
    <div class="search-popup__inner">
        <form action="#" class="search-popup__form">
            <input type="text" name="search" placeholder="Escreva para procurar algo....">
            <button type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div><!-- /.search-popup__inner -->
</div><!-- /.search-popup -->

<div id="hi-whatsapp" onclick="location.href='https://whatsa.me/5547997758281/?t=Ol%C3%A1%20J6%20Solu%C3%A7%C3%B5es%20Digitais,%20preciso%20de%20uma%20ajuda.'">
    <i class="fab fa-whatsapp"></i>
</div>

<!-- template scripts -->
<script src="<?=TEMPLATE_INOVEX;?>/js/jquery.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/bootstrap.bundle.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/bootstrap-datepicker.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/bootstrap-select.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/isotope.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/jquery.ajaxchimp.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/jquery.circleType.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/waypoints.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/jquery.counterup.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/jquery.lettering.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/jquery.magnific-popup.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/jquery.validate.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/owl.carousel.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/TweenMax.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/wow.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/swiper.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/particles.min.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/particel-config.js"></script>
<script src="<?=TEMPLATE_INOVEX;?>/js/theme.js"></script>