<?php
$configuracoes = Session::get("config");
?>
<head>
    <meta charset="utf-8" />
    <title><?= TITULO_FRAMEWORK; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="<?= TITULO_FRAMEWORK; ?>" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link rel="icon" type="image/png" href="<?= STATIC_URL; ?>/img/sistema/<?=$configuracoes["dir_galeria"]."/thumb56_".$configuracoes["capa"]; ?>">

    <link href="<?= TEMPLATE_HEXZY; ?>/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="<?= TEMPLATE_HEXZY; ?>/css/icons.css" rel="stylesheet" type="text/css">
    <link href="<?= TEMPLATE_HEXZY; ?>/css/style.css" rel="stylesheet" type="text/css">
    <link href="<?= TEMPLATE_CHARLES; ?>/vendor/fancybox/dist/jquery.fancybox.min.css" rel="stylesheet" type="text/css">
    <link href="<?= STATIC_URL; ?>/css/style.css" rel="stylesheet" type="text/css">

    <style>
        #topnav .topbar-main{
            background-color: #fff;
        }
        .notification-icon-box{
            background-color: <?=$configuracoes["cor_secundaria"];?>;
        }
        .search-bar{
            background-color: <?=$configuracoes["cor_secundaria"]; ?> !important;
        }
        .profile .profile-username{
            color: #000 !important;
        }
        #topnav .navigation-menu > li .submenu li a i{
            color: <?=$configuracoes["cor_primaria"]; ?> !important;
        }
        #topnav .navbar-custom{
            background-color: <?=$configuracoes["cor_primaria"]; ?> !important;
        }
        #topnav .navigation-menu > li > a{
            color: <?=$configuracoes["cor_terciaria"]; ?> !important;
        }
        #topnav .navigation-menu > li > a i.mdi-drop{
            color: <?=$configuracoes["cor_terciaria"]; ?> !important;
        }
        #topnav .navbar-toggle span{
            background-color: <?=$configuracoes["cor_primaria"]; ?> !important;
        }
        #topnav .navigation-menu > li .submenu li a:hover {
            color: #3e445e;
            background-color: #f8f9fa !important;
        }
        .notifi-title{
            background-color: <?=$configuracoes["cor_secundaria"]; ?> !important;
        }
        a{
            color: <?=$configuracoes["cor_primaria"]; ?> !important;
        }
        .social-links li a{
            background-color: #fff !important;
        }
        .btn-sistema{
            background-color: <?=$configuracoes["cor_primaria"]; ?> !important;
            color: <?=$configuracoes["cor_terciaria"]; ?> !important;
            border-radius: 30px;
        }
        .btn-sistema-secundario{
            background-color: <?=$configuracoes["cor_secundaria"]; ?> !important;
            color: <?=$configuracoes["cor_terciaria"]; ?> !important;
            border-radius: 30px;
        }
        .btn-sistema-fechar{
            background-color: #5b5b5b !important;
            color: <?=$configuracoes["cor_terciaria"]; ?> !important;
            border-radius: 30px;
        }
        .btn-sistema:hover{
            opacity: 0.8;
        }
        .badge-secondary{
            background-color: <?=$configuracoes["cor_secundaria"]; ?> !important;
        }

        /** MOBILE */
        @media only screen and (max-width: 992px) {
            #topnav .navigation-menu > li > a{
                color: #000 !important;
            }
            #topnav .has-submenu.active > a, #topnav .submenu li.active > a, #topnav .navigation-menu > li > a:active, #topnav .navigation-menu > li > a:hover{
                color: #000 !important;
            }
        }
    </style>

</head>