<head>
    <meta charset="utf-8" />
    <title><?= TITULO_FRAMEWORK; ?> - Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="j6.net.br" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <link rel="icon" type="image/png" sizes="56x56" href="<?= TEMPLATE_HEXZY; ?>/images/icon.png">

    <link href="<?= TEMPLATE_HEXZY; ?>/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="<?= TEMPLATE_HEXZY; ?>/css/icons.css" rel="stylesheet" type="text/css">
    <link href="<?= TEMPLATE_HEXZY; ?>/css/style.css" rel="stylesheet" type="text/css">
    <link href="<?= STATIC_URL; ?>/css/style.css" rel="stylesheet" type="text/css">

</head>